### ISSUE TITLE
2.13.0 difference between maven (**Nov 9th**)  and github  (**Nov 15th**)  ?

### ISSUE THREAD

**Issue by lindenb** [samtools/htsjdk#1028]
### Subject of the issue

I've been using the library 2.13.0 on maven https://mvnrepository.com/artifact/com.github.samtools/htsjdk/2.13.0 released on **Nov 9th**

> (Nov 09, 2017) 

but 2.13.0 was **released yesterday** (**Nov 15th**)

https://github.com/samtools/htsjdk/releases/tag/2.13.0

what is the difference between those jars ?

**Comment by lbergelson** [comment]
I uploaded the maven release and the tag last week, but I forgot to upload the release notes to github at the same time. In remembered them yesterday. The 2.13.0 tagged commit is what's released on maven.

**Comment by lindenb** [comment]
ah ok thanks
