### ISSUE TITLE
How could I convert the htsjdk data to ga4gh schema data?

### ISSUE THREAD

**Issue by renyaoxiang** [samtools/htsjdk#1038]
Does the htsjdk could convert the htsjdk data to ga4gh schema data?
I did not find the functions in the source.
How could I convert the htsjdk data to ga4gh schema data?

**Comment by lindenb** [comment]
see https://github.com/googlegenomics/gatk-tools-java/blob/master/adding-ga4gh-support.md ?

**Comment by renyaoxiang** [comment]
Dear @lindenb 

Thank you!
