### ISSUE TITLE
Trouble loading bam file in IGV

### ISSUE THREAD

**Issue by sagnikbanerjee15** [samtools/htsjdk#1047]
Hello,

I work with Barley where most of the sequences are longer than 2^29-1. I have RNA-Seq data which map to regions beyond 2^29 on the chromosomes. I generally provide the .bam file to IGV. For this I need to generate the .bai file using samtools index. But this command fails since the there are regions which cannot be included in the bai index. Instead samtools recommends me to generate a .csi index file. IGV on the other hand cannot work with .csi index files. IGV used htsjdk for loading the files. Could you please suggest an alternative?

Thank you.

**Comment by yfarjoun** [comment]
THere's a CSI index PR in review. once that's in, and htsjdk is rev'ed in
IGV, it might "just work".

**Comment by sagnikbanerjee15** [comment]
Oh I see..Thank you.

**Comment by sagnikbanerjee15** [comment]
Hello,

Has htsjdk been updated to deal with issue discussed?

Thanks

**Comment by yfarjoun** [comment]
not yet. The person most appropriate to review the CSI PR was busy with the GATK4 release up until last week...but the good news is that he has much more time now to devote to htsjdk, and so there's a good likelihood that the PR will be reviewed and dealt with soon. I must warn you that it's a large PR and it will take time to get through...then once it's in there are a few more steps (release, and then rev htsjdk in IGV) before you'll be able to use it natively. 

if you want to try it out on your own more soon, you can do that:

1. Compile and "install" htsjdk locally, 
2. Modify the IGV source to use that version of htsjdk, 
3. Compile IGV it, and see if it works! 

It would actually be a valuable experiment if you do that...so please report back if you do!

**Comment by sagnikbanerjee15** [comment]
Oh cool. I will get my hands dirty. I will let you know how it turns out.

Thanks.

**Comment by yfarjoun** [comment]
That would be great! Thank-you! Feel free to ask questions and comment about the documentation if you find it less than helpful...

**Comment by sagnikbanerjee15** [comment]
Hello,

Thanks for updating the htsjdk to handle .csi files. There seems to be some problem with it though. I can load the bam files and the .csi files to IGV but I cannot view the alignments. Moreover, I keep getting the following error - "Error encountered querying alignments: htsjdk.samtools.SAMException: Unexpected number of metadata chunks 3". Please see the attached image.


![](https://user-images.githubusercontent.com/23457977/52816456-e4817e80-3066-11e9-9ec2-e3dfe5d3489e.png)

**Comment by lbergelson** [comment]
@sagnikbanerjee15 That sounds like a bug... Would it be possible to provide a tiny indexed snippet of the bam file that exhibits the problem?

**Comment by sagnikbanerjee15** [comment]
Hello,

Here is a small snippet of the bam file. The alignments were made with STAR. The genome is that of hordeum vulgare obtained from ensemble.

Thank you.

[alignments.zip](https://github.com/samtools/htsjdk/files/2872010/alignments.zip)

**Comment by lbergelson** [comment]
Thank you.  I'll take a look.

**Comment by lbergelson** [comment]
@sagnikbanerjee15 I can't replicate your exact error, but using your test file I identified an overflow error that was breaking querying on your file. One of the calculations for identifying index bins in CSI results in a number larger than `maxInt` which was causing queries to fail silently.  By doing the calculation with `longs` it looks like it solves that particular issue.  There may be more lurking though...

**Comment by lbergelson** [comment]
@sagnikbanerjee15 I believe I've fixed the bug you've discovered but I haven't integrated with IGV to be sure.  Please reopen this if it's not fixed when IGV updates.
