### ISSUE TITLE
FastaSequenceIndex not usable outside its package 

### ISSUE THREAD

**Issue by pabarcgar** [samtools/htsjdk#1049]
The class FastaSequenceIndex includes a _FastaSequenceIndexEntry getIndexEntry(contigName)_ method in its API, but that class is package protected. All the useful methods in FastaSequenceIndex are based in FastaSequenceIndexEntry, thus, if you are outside that package (I'm using HTSJDK as a library), the FastaSequenceIndex class does not have any real use.

FastaSequenceIndexEntry is inside FastaSequenceIndex file. Java only allows a public class per file, is that the reason that FastaSequenceIndexEntry is package protected? Maybe it was an inner class in the past... Would you consider making this class public (moving it outside FastaSequenceIndex.java) so it can be used by external modules?

Initially, I was trying to read the sequence dictionary for a fasta file, but I found that the SAMSequenceDictionary is empty if I create the fasta file like this:  `ReferenceSequenceFileFactory.getReferenceSequenceFile(fastaFile, true);`
I then tried to use the Fasta index, but I found that dead end with the package protected class. Is there any other turnaround to do this?

Thanks and Regards

**Comment by d-cameron** [comment]
My resolution was to lazily create a sequence dictionary if it didn't exist.
See https://github.com/PapenfussLab/gridss/blob/master/src/main/java/au/edu/wehi/idsv/GenomicProcessingContext.java#L95

**Comment by jigold** [comment]
I ran into this problem too.
