### ISSUE TITLE
Can we have a htsjdk release?

### ISSUE THREAD

**Issue by yfarjoun** [samtools/htsjdk#1062]
### Verify
Can you see anything in the logs? 
Make sure your issue is not already in the [htsjdk issue tracker](https://github.com/samtools/htsjdk/issues?q=)

### Subject of the issue
Describe your issue here.
Provide **screenshots** , **stacktrace** , **logs** where appropriate.

### Your environment
* version of htsjdk
* version of java
* which OS

### Steps to reproduce
Tell us how to reproduce this issue. If possible, include a short code snippet to demonstrate the problem.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by lbergelson** [comment]
2.14.0 has been released!
