### ISSUE TITLE
getPL Returning Incorrect Values

### ISSUE THREAD

**Issue by hakanEdico** [samtools/htsjdk#1097]
When using the getPL() function from genotype.java, I am getting incorrect values returned. 
For example in this VCF line: 
 
GL000206.1	6870	.	C	T	11.04	.	AC=1;AF=0.500;AN=2;DP=16;FS=6.990;MQ=39.29;MQRankSum=-1.036;QD=0.69;ReadPosRankSum=-2.383;SOR=3.258;FractionInformativeReads=0.625;R2_5P_bias=31.099	GT:AD:AF:DP:GQ:PL:GL:GP:PRI:SB:MB	0/1:6,4:0.400:10:45:45,0,50:-4.55,0.00,-5.00:7.864e-02,9.214e-01,4.618e-06:0.00,34.77,37.77:3,3,0,4:4,2,1,3

Where the PL is "45,0,50"
The getPL() function returns [0, 46, 50]

Its always the second highest value incremented by one... very weird. 

I am running on centos6/7
Version 2.0.1

EDIT: GL,GP,PRI were added recently, when they are removed this problem does not occur.

**Comment by yfarjoun** [comment]
Observation: Your GP and PL are inconsistent.

According to the GP you have [-4.55,0.00,-5.00] which would imply PL= [46,
0, 50], but you PL is [45, 0, 50].

I agree that this is a bug.. it seem to stem
from htsjdk/variant/vcf/AbstractVCFCodec.java:721 where the PL *derived* from
your GL overwrites the PL.

I'll submit a PR for this shortly.

Thanks!!

**Comment by yfarjoun** [comment]
I submitted a PR #1098  that fixes this issue and I used the VariantContext that you supplied. please let me know if that it not OK.

**Comment by hakanEdico** [comment]
I have downloaded/compiled your branch and the issue is still present for me.

**Comment by hakanEdico** [comment]
The fix works, thanks a lot! 

One unrelated question, in the past our project has used 
LineReaderUtil.fromBufferedStream(vcfIstream) where vcfIstream is a FileInputStream object. 

Looks like that is deprecated now, is it safe to use 
 AsciiLineReader.from(vcfIstream) instead?
