### ISSUE TITLE
Status of CSI support in HTS-JDK and downstream tools. 

### ISSUE THREAD

**Issue by WimSpee** [samtools/htsjdk#1099]
Hi,

Is there an ETA for this pull request to be reviewed and hopefully merged? 

https://github.com/samtools/htsjdk/pull/1040

Support for CSI indexes would be really useful for us in HTS-JDK and subsequently GATK4. 

I am deciding if I should wait for this pull request or cut some chromosomes in 2 pieces so that I can continue with just the BAI indexes.

Thank you.

**Comment by brainstorm** [comment]
That PR seems to be merged, so it should be safe to close this?

**Comment by lbergelson** [comment]
Initial support for csi indexes is in. There's an outstanding bug with long references but it should be fixed in the coming release.
