### ISSUE TITLE
NullPointerException FASTA getSequenceDictionary

### ISSUE THREAD

**Issue by hakanEdico** [samtools/htsjdk#1147]
### Subject of the issue
I am trying to get the sequences of a FASTA file. Calling getSequenceDIctionary() on the FASTA file returns null. 

- htsjsk version 2.14.3 (same error on 2.15.1) 
- Java 1.8 
- CentOS6/CentOS7/OSX 

```
ReferenceSequenceFile fastaSequenceFile = ReferenceSequenceFileFactory.getReferenceSequenceFile(new File(fasta), true, true);
logToStdOut("Is FASTA File Indexed: " + fastaSequenceFile.isIndexed());
logToStdOut("Reading FASTA File...");
SAMSequenceDictionary seqDict = fastaSequenceFile.getSequenceDictionary();
```

```
Exception in thread "main" java.lang.NullPointerException
	at dragen_tools.VCFValidation.VCF_VALIDATOR.<init>(VCF_VALIDATOR.java:133)
	at dragen_tools.Dragen_tools.main(Dragen_tools.java:275)
Java Result: 1
```
Whats weird is there are certain references (like hg19) which do not repro this error on some servers. Here is an example: 

### Run 1 ###
- OS: CentOS6 2.6.32-696.16.1.el6.x86_64
- Java: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.el6_9.x86_64/jre/bin/java
- Reference: hg19
- Result: NullPointerException 

### Run 2 ###
- OS: CentOS6 2.6.32-696.18.7.el6.x86_64
- Java: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.el6_9.x86_64/jre/bin/java (same exact one) 
- Reference: hg19 (same exact file, confirmed with md5sum) 
- Result: No null pointer, runs fine 

How is this possible?

**Comment by yfarjoun** [comment]
Is the dict file in the same place?

**Comment by hakanEdico** [comment]
Wow! As simple as that. Thank you, solved the issue it seems.
