### ISSUE TITLE
Is it intended that the allele parsing cache is thrown away for each line?

### ISSUE THREAD

**Issue by spullara** [samtools/htsjdk#1166]
This maps things like "0/0" to [0, 0], etc. I think it should be completely immutable but it is cleared here and thus reparsed for each line of a VCF file. The name of the variable where it is used is "cache" but it really only effectively caches if there are many samples per line.

https://github.com/samtools/htsjdk/blob/e0bf651c3122190134d0ea72b940b59567f0a31e/src/main/java/htsjdk/variant/vcf/AbstractVCFCodec.java#L680

It is about a 5-10% performance boost if you remove it.

**Comment by yfarjoun** [comment]
I think that the problem is that the map points to an actual allele, and
not to 0 or 1...so that changes from one line to the next.

**Comment by spullara** [comment]
I see. So the solution here would be to cache the parsing of the genotypes but not the actual selected Allele.

**Comment by spullara** [comment]
Would this change the behavior? I'm on windows and I don't have the tests running here but will try it out on another system shortly.

https://github.com/spullara/htsjdk/commit/238d062ad1451acd6fdfecde4daf13c9b419a552

**Comment by spullara** [comment]
After testing this appears to work well. I'll propose a pull request for the change.

**Comment by spullara** [comment]
After doing a bunch more performance tests it isn't really worth it. Closing the ticket.
