### ISSUE TITLE
Zero-length read without FZ, CS or CQ tag

### ISSUE THREAD

**Issue by nh13** [samtools/htsjdk#1174]
@tfenne @lbergelson @yfarjoun I wanted to get your thoughts on relaxing this validation, which I think is stricter than the SAM spec.  I have a use case to represent some data in SAM/BAM/CRAM, but with the bases and qualities removed, with an example below with most extraneous information removed (i.e. other tags).  The bases and qualities are `*`, so  no assumptions should be made about how the bases and cigar relate.  There was a bug fixed here: 9d724c3a2dfd6928ea24a91443cd7f2bf6eb6c09.  But I think that requiring FZ/CS/CQ tags when the bases are empty is not warranted (McCowan!):
https://github.com/samtools/htsjdk/blob/master/src/main/java/htsjdk/samtools/SAMRecord.java#L2081-L2109

Example:

<details>

```
htsjdk.samtools.SAMFormatException: Error parsing text SAM file. Zero-length read without FZ, CS or CQ tag; File ...
Line: name	0	chr1	1	60	7M	*	0	0	*	*	RG:Z:Id
   at htsjdk.samtools.SAMLineParser.reportErrorParsingLine(SAMLineParser.java:457)
   at htsjdk.samtools.SAMLineParser.parseLine(SAMLineParser.java:355)
   at htsjdk.samtools.SAMTextReader$RecordIterator.parseLine(SAMTextReader.java:268)
   at htsjdk.samtools.SAMTextReader$RecordIterator.next(SAMTextReader.java:255)
   at htsjdk.samtools.SAMTextReader$RecordIterator.next(SAMTextReader.java:228)
   at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:576)
   at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:548)
```
</details>

**Comment by yfarjoun** [comment]
Do you need this to pass ValidateSamFile, or are you having trouble reading/writing the file?

There has been discussions in HTS-Spec about SAM-valid and SAM-strict specifications and I would tend to agree that this falls in the "sam-strict" side of things, but my sense is that for normal use of BAM this would indicate a problem that I'd like to know about...

**Comment by tfenne** [comment]
I think the problem is that the reader in STRICT mode (which generally you want), doesn't allow reads that are missing bases, qualities _and_ don't have color-space related tags.

@nh13 Have you tried putting in all `=` for your bases?  I know it's a bit of a hack, but I think it would work if you did that (i.e. 50 x `=` for a 50bp record), and would compress pretty well.

@yfarjoun I think Nils is essentially trying to use SAM as a super-BED file, i.e. recording information about intervals on a genome that are heavily annotated and thus using SAM with all the tag support works better.  As such there is no real sequence/qualities to be stored.

I think in general I'd favor changing things so that it's valid to have a record with no bases _and_ no qualities, but invalid if it's missing one or the other as that seems more like an error than intent.  What do others think?

**Comment by nh13** [comment]
Just to restart this thread, I have a second separate use-case for a record with no bases and no qualities, but the cigar is present!  I think @tfenne is on-board, how about you @yfarjoun?

**Comment by nh13** [comment]
Also, the fun hack for when the bases are _much_ longer is just to put in a dummy value for the `FZ` tag, since if that's present, that whole section of validation is skipped.

**Comment by yfarjoun** [comment]
I think that it would be good to make sam MORE useful. 

Given that the logic of the zero-length bases implies flow-based sequencing is rooted in a mistaken assumption, we could probably relax that requirement. I wonder though if we should put something else instead, for example, a flag in the @RG tag, or something like that...

thoughts?

**Comment by nh13** [comment]
@tfenne there's a check that the length of bases and qualities match, and if they don't that there are bases but no qualities (ex. FASTA->SAM).  See: https://github.com/samtools/htsjdk/blob/77b3b8ff94a47f5601684beead2d2b499863c840/src/main/java/htsjdk/samtools/SAMRecord.java#L2076-L2081

@yfarjoun I think the ship has sailed on adding information to the specification of the read group to indicate if color space or flow signal data should be expected.  If there is someone sufficiently motivated to add that to the SAM spec, I'd support it, but I think that concern can be divorced from this issue. 

I have made a PR #1360 to address this issue.

**Comment by yfarjoun** [comment]
I think that the ideal solution would be to have a list of validation errors that need be ignored and that the Reader is aware of this list (possibly via default options of the factory) that will allow for the casual users to continue getting an error when they screw up their files, but also permit advanced users to have fine-tuned control over the validation errors that they get. It's more code change than you did in #1360 but I feel that it would better serve the needs of the entire community.

**Comment by nh13** [comment]
I like the ideal solution, and I think long-term that it would be nice anyhow.

However, I write tools for casual users, some of which use tools for which I can't control the default options to the factory.  I don't want to open the can of worms to (1) explain to them command line options to ignore the validation errors, and (2) why we are doing so each time.  I then need to update every toolset they use that relies on htsjdk to add such a command line option. Also, I don't think the removal of these validation errors is going to cause a lot of screwed up files to pass, and I think the original implementation is wrong to begin with (it is spec-compliant).

**Comment by nh13** [comment]
@yfarjoun would it make sense to ask a few other maintainers (@jmarshall and @jkbonfield) given htsjdk is a "flagship" implementation?

**Comment by nh13** [comment]
Fixed in https://github.com/samtools/htsjdk/pull/1360

**Comment by jkbonfield** [comment]
Not only is there nothing in the spec that forbids this, there are actually examples (representing assembly annotations, SAMv1.pdf section 3) that have no seq, no qual and none of those tags.  So this shouldn't be enforced - strict or otherwise.
