### ISSUE TITLE
Indefinite loop caused by condition in SeekableHTTPStream

### ISSUE THREAD

**Issue by dtitov** [samtools/htsjdk#1181]
### Subject of the issue
Hi! I believe there's a bug in `SeekableHTTPStream`, but I'm not completely sure - at least there's some strange and unexpected (for me) behavior. 

When I try to read `SeekableHTTPStream` with Apache Commons IO (`IOUtils#copyLarge`), it hangs with an indefinite loop... I debugged what is happening under the hood and it appeared that there's a condition in `read` method of `SeekableHTTPStream`:
```java
        if (len == 0 || position == contentLength) {
            return 0;
        }
```
I'm convinced that this condition actually violates the contract of the `read` method of an `InputStream`: when we have no more bytes to read we should return `-1` as a result, signalizing the reader of the `EOF` event. But if we return `0`, like above, the reader will never know that we reached the end of the stream and will indefinitely try to read further. At least this is my understanding of the problem: please, correct me if I'm wrong.

### Your environment
* htsjdk version: 2.16.1
* Java version: 1.8
* OS: MacOS

### Steps to reproduce
```java
SeekableStream inputStream = new SeekableHTTPStream(new URL("someFileURL));
OutputStream outputStream = ... //some output stream
IOUtils.copyLarge(inputStream, outputStream);
```

### Expected behaviour
The input stream is copied to the output stream and the execution finishes successfully.

### Actual behaviour
The input stream is copied to the output stream, but in the end, execution ends up with an endless loop.

**Comment by kusalananda** [comment]
If `len == 0`, then zero is the correct thing to return (but only if `position != contentLength`). If `position == contentLength`, there should be a minus one returned (as all data has been read).

**Comment by lbergelson** [comment]
@dtitov @kusalananda This definitely looks like a bug, returning -1 in the case where we're at the end of the file should be result.  

@jacarey You added this condition, was there a reason to return 0 and not -1 which seems to be right result?

**Comment by jacarey** [comment]
None that I can remember. -1 seems correct to me
