### ISSUE TITLE
Question: SamReaderFactory + https + authentication

### ISSUE THREAD

**Issue by lindenb** [samtools/htsjdk#1190]
Not an issue but a question: I need to (random-) access some **BAM** files behind a https site with **authentication**.

 Is there any already-existing class open a SamReader with a login/password ?

( I see UserPasswordInput is used in SeekableFTPStream.java but I cannot find it used elsewhere)

Thanks,

P.

**Comment by lbergelson** [comment]
That's a good question... I wonder what IGV does...  Maybe you can pass the password/username as part of the URL?   

@magicDGS Does your https path provider support authentication?

**Comment by lindenb** [comment]
a quick test using jjs and https://jigsaw.w3.org/HTTP/ . java.net.URL doesn't seem to understand 'login:password' in the URL like in  the browsers.

```
 echo 'var u = new java.net.URL("https://guest:gest@jigsaw.w3.org/HTTP/Basic/").openStream();' | jjs
jjs> java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 401 for URL: https://guest:gest@jigsaw.w3.org/HTTP/Basic/

```

**Comment by lbergelson** [comment]
Hmn... That's too bad. I don't know how http authentication usually works.   If it doesn't accept it in the url does it get set as keys in the header?

**Comment by lindenb** [comment]
yes, the basic authentication works as a extra http header user +password encoded as base64.  https://en.wikipedia.org/wiki/Basic_access_authentication#Client_side

It wouldn't be too hard to detect the pattern http//login:password@host/path in HttpUtils which, as far as I understand open the streams from SeekableHTTPStream which calls HttpUtils. Do you think I can write a PR and allowing this by default  ?

**Comment by lbergelson** [comment]
Lets check to make sure we're not missing something first.  @jrobinso How does IGV support authenticated http requests?  Does it do it through htsjdk or have some other mechanism for it?

**Comment by lindenb** [comment]
@lbergelson  go it. If I'm not wrong, I think I can implement it as a custom SeekableStreamFactory on my side. 

closing.

**Comment by jrobinso** [comment]
It might be secure enough for some situations,  that's a subjective call,  I just don't see much demand for it (compared to oAuth for example).

**Comment by lindenb** [comment]
@jrobinso I'm currently working with  ~500 WGS behing https +  basic auth ...  :smiley:

**Comment by jrobinso** [comment]
OK!  I stand corrected.     That should work with IGV, although I'm not
sure I've tested   https: + basic auth together.

**Comment by magicDGS** [comment]
@lbergelson - sorry for the late response, but I am not planning to support yet authentication. I am planning to come back to that project this week, and release 0.1.0 if I can, with basic HTTP/S filesystems. In a following iteration, I can explore different ways of introducing authentication but it is not a major requirement at the moment (I am more focus in supporting filesystems in case the server support it); but it can become a major requirement if users ask for it (probably htsjdk-next-beta users will be the primary user, if we base it uniquely in java.nio).

**Comment by lindenb** [comment]
For the records: I created a FUSE (Filesystem in Userspace) to  access my remote files  like if they were stored in my hard drive https://github.com/lindenb/htsfuse . I haven't tested it with htsjdk but it works with samtools.

It should fulfill my needs.
