### ISSUE TITLE
Remove JAXB dependency for better java 9+ compatibility.

### ISSUE THREAD

**Issue by jrobinso** [samtools/htsjdk#1204]
As you know JAXB is not included with Java 9 and above.   It can be used with command line switches, for now, but introduces another dependency.     I have removed all uses of JAXB from IGV, and am looking at the htsjdk now.   It looks like the only place it is used is the class SAMSequenceDictionary, however I'm not sure what its purpose is there.   Are objects of that class serialized from somewhere?   It would be strange to serialize this class only but it is the only class I can find with JAXB annotations.

**Comment by jrobinso** [comment]
BTW we are using the htsjdk with Java 11 with no issues,  but would like to drop the JAXB switches.

**Comment by lindenb** [comment]
I wrote the jaxb bindings because I had the idea to use htshdk for webservices. But in the end, I did not use it . Unless someone else use it, I don't see any reason to keep the jaxb stuff in htsjdk.

I only see my code in github (or some forks..) : https://github.com/search?q=Unmarshaller+htsjdk&type=Code

**Comment by lbergelson** [comment]
@jrobinso Sounds like we should remove it.

**Comment by jrobinso** [comment]
@lindenb Pierre is that you?  You're everywhere.     

I can remove these and send a PR if you want,   I just removed several hundred of them from IGV.

**Comment by lbergelson** [comment]
@jrobinso You should be able to replace the Dataconverter.printHexBinary with StringUtil.bytesToHexString()
