### ISSUE TITLE
Broken index with igvtools (?)

### ISSUE THREAD

**Issue by jean-philippe-martin** [samtools/htsjdk#1237]
### Verify

I don't see anything in logs, and didn't find the same issue.

### Subject of the issue

Index generated with igvtools doesn't load properly with htsjdk.

It shows only a single block for chr10: chr10:2905571559-3157362959
but in fact there are many more entries in chr10, including one at chr10:60001

### Your environment
* version of htsjdk: 2.18.1
* version of igvtools: Program: igvtools. IGV Version 2.4.16 11/17/2018 10:33 PM
* version of java: 8
* which OS: linux

### Steps to reproduce

1. Download gs://genomics-public-data/platinum-genomes/vcf/NA12877_S1.genome.vcf
2. Index with igvtools:
    java -jar igvtools.jar NA12877_S1.genome.vcf
3. Use the following code:
```
Index index = IndexFactory.loadIndex("NA12877_S1.genome.vcf.idx");
for (Block b : index.getBlocks("chr10",0,999999999)) {
              System.out.println("  Checking " + b.getStartPosition() + "-" + b.getEndPosition());
```

### Expected behaviour
Multiple blocks listed, starting from chr10:60001

### Actual behaviour
A single line of output:
```
  Checking chr10:2905571559-3157362959
```

Am I doing something wrong, is that not how we're supposed to use htsjdk?

**Comment by cmnbroad** [comment]
@jpmartin A`Block` contains a file offset and size for a section of the file that contains records that satisfy the query, not the records themselves. If you want the actual records, use a FeatureReader (i.e. VCFFileReader).

**Comment by jpmartin** [comment]
Wrong @jean-philippe-martin.

**Comment by jean-philippe-martin** [comment]
I understand the Block only has offsets, @cmnbroad. What is surprising here is that the vcf file has data starting at chr10:6001, yet there is no index Block for it. As far as the index is concerned, chromosome 10 appears to start at offset 290 million.

So it looks like the index is wrong.

**Comment by cmnbroad** [comment]
@jean-philippe-martin "chr10:6001" is a genomic location, right ? But the Block has file offsets. So I'd expect the variant with loc chr10:6001 to appear at the file offset given by the Block start (290 million).

**Comment by jean-philippe-martin** [comment]
Thank you very much @cmnbroad, this clears up that confusion!
