### ISSUE TITLE
CRAM to support interval querying

### ISSUE THREAD

**Issue by nh13** [samtools/htsjdk#124]
Before we release, we would like to support interval range querying of CRAM files.  @vadimzalunin could this be supported?
```
CloseableIterator<SAMRecord> query(final QueryInterval[] intervals,
                                              final boolean contained)
```

**Comment by nh13** [comment]
@vadimzalunin any movement on this?

**Comment by nh13** [comment]
@vadimzalunin: please submit all pull request with this feature supported, and write one or more units that tests this support with SAM, BAM, and CRAM, if one does not already exist.

**Comment by vadimzalunin** [comment]
fixed in https://github.com/samtools/htsjdk/pull/224

**Comment by superbobry** [comment]
This seems to be implemented. Close?

**Comment by cmnbroad** [comment]
@vadimzalunin Can we close this ?
