### ISSUE TITLE
CRAMFileReader enableFileSource is not propagated to SAMRecords consistently

### ISSUE THREAD

**Issue by cmnbroad** [samtools/htsjdk#1293]
Setting `INCLUDE_SOURCE_IN_RECORDS` on a SamReaderFactory when creating a CRAM file doesn't work in most (all ?) cases because the `CRAMFileReader` implementation doesn't cache the SamReader locally. Instead, it propagates it directly to the `CRAMIterator` object in existence at the time `enableFileSource` is called. Subsequently, `CRAMFileReader` almost always replaces the primed `CRAMIterator` with a new iterator whenever an iterator is requested, losing knowledge of the original SamReader.

`CRAMFileReader` should cache the SamReader locally and propagate it on a record-by-record basis as the records are returned from the iterator.

**Comment by jmthibault79** [comment]
A test which demonstrates this: 59009a9baa1be1688e485af316869047da4cdfb9

**Comment by cmnbroad** [comment]
Fixed in refactoring branch (enableFileSource isn't relevant for CRAM records).
