### ISSUE TITLE
*CramCompressionRecord getAlignmentSpan() and getAlignmentEnd() don't reflect changed state

### ISSUE THREAD

**Issue by jmthibault79** [samtools/htsjdk#1301]
### Subject of the issue
`getAlignmentSpan()` / `getAlignmentEnd()` only calculate their values once, via `initializeAlignmentBoundaries()`.  If the underlying data changes, callers will see stale span and end values.

My preferred solution would be to make CramCompressionRecord immutable.

Noticed in #1284 but the problem existed prior to that.

**Comment by cmnbroad** [comment]
Fixed in refactoring branch. (CramCompressionrecord, now CRAMRecord, is immutable).

**Comment by cmnbroad** [comment]
Closed via https://github.com/samtools/htsjdk/pull/1440.
