### ISSUE TITLE
CramHeader ID does not clear its buffer on set or construction

### ISSUE THREAD

**Issue by jmthibault79** [samtools/htsjdk#1307]
### Subject of the issue
CramHeader construction with ID (and `setId()`) do not simply set the ID value.  Instead they copy up to 20 bytes of the desired value into a 20-byte buffer.  As a result, extra bytes remain in the buffer.  If there was a previous longer ID set, the stale bytes past the new limit remain.  As a result, `setID()` and `getId()` do not round-trip.

Is there a reason for this behavior?

**Comment by cmnbroad** [comment]
I doubt there is any reason for it - sounds like a bug. The contents of the 20 byte space reserved in the header is not defined by the spec, and is left up to the implementation. htsjdk uses the first 20 bytes of the file name (which has it's [own problems](https://github.com/samtools/hts-specs/issues/144#issuecomment-356974951)). We should fix it.

**Comment by cmnbroad** [comment]
@jmthibault79 Is this still an issue, or was this fixed in one of your PRs ?

**Comment by jmthibault79** [comment]
Addressed in #1306 which needs review

**Comment by cmnbroad** [comment]
Fixed in refactor branch.

**Comment by cmnbroad** [comment]
Fixed in CramHeader in #1440.
