### ISSUE TITLE
invalid uncompressedLength

### ISSUE THREAD

**Issue by wavefancy** [samtools/htsjdk#1335]
### Verify
Can you see anything in the logs?  Yes
Make sure your issue is not already in the [htsjdk issue tracker](https://github.com/samtools/htsjdk/issues?q=)

### Subject of the issue
htsjdk (2.19/2.18.2) read tabix indexed vcf reported invalid uncompressedLength.
Re-index by tabix (1.3.1) or GATK 4 IndexFeatureFile no help. But the files work great by tabix. 

### Your environment
* version of htsjdk
* version of java 8
* which Linux

Thanks much for the help.

Best regards
Wallace

**Comment by cmnbroad** [comment]
@wavefancy Can you provide any more context for this, ie., a call stack, and the input file if possible (please see the issue template for more information). Is this issue by any chance related to https://github.com/samtools/htsjdk/issues/1335 ? This is the kind of error you might see if you tried to use a query iterator in parallel.

**Comment by wavefancy** [comment]
Hi Chris,

This is a misleading error caused by call  VCFReader.query in parallel. Close the parallel call solved the problem. 

Thanks much for your help.

Best regards
Wallace
