### ISSUE TITLE
Call vcfreader.query in in parallel having strange unpredicted behaviors.

### ISSUE THREAD

**Issue by wavefancy** [samtools/htsjdk#1336]
Hi Developers,

It seems vcfreader.query cannot be used in parallel. Below two ways will cause strange unpredicted behaviors. Any ideas on how to fix it in a parallel calling.

```
 vcfreader.query(chr, min_pos, max_pos).stream()
           .parallel()
           .forEach()
```
OR
```
.parallel()
.forEach(group->{
     vcfreader.query(chr, min_pos, max_pos).stream()
           .parallel()
           .forEach();
});
```

Best regards
Wallace

**Comment by cmnbroad** [comment]
The iterators returned from VCF queries are backed by an underlying input stream, and generally maintain state that precludes being able to split them for use in parallel.
