### ISSUE TITLE
VariantContextBuilder : putAttributes fails if Map cannot be modified

### ISSUE THREAD

**Issue by lindenb** [samtools/htsjdk#1365]
### Subject of the issue

I got an exception with `VariantContextBuilder.putAttributes`: UnsupportedOperationException

in https://github.com/samtools/htsjdk/blob/master/src/main/java/htsjdk/variant/variantcontext/VariantContextBuilder.java#L273

if `this.attributes` is not null and was created from `public VariantContextBuilder(final VariantContext parent)` , as far as I can see `this.attributes` is **unmodifieable**.

I could write a PR but I don't really understand this `attributesCanBeModified`.

### Your environment
* version of htsjdk  2.2.4
* version of java 1.8
* which OS linux

**Comment by yfarjoun** [comment]
Thanks @lindenb. I think that this might be related to #1344. I'm adding your usecase as a test to check it. be happy to get your review on that PR if you're interested.
