### ISSUE TITLE
Trying to replace SAMFileReader in FastQC: htsjdk.samtools.util.RuntimeIOException: java.io.IOException: Stream closed

### ISSUE THREAD

**Issue by daissi** [samtools/htsjdk#1373]
Hi,
This is the following of https://github.com/samtools/htsjdk/issues/767. To be able to build FastQC in Debian, we updated the FastQC code related to SAMFileReader to use the new API of htsjdk with this [patch](https://salsa.debian.org/med-team/fastqc/blob/master/debian/patches/htsjdk-api.patch). Now, the FasQC package builds fine but it is not able to process SAM/BAM files anymore ([#897109](https://bugs.debian.org/897109), [#923428](https://bugs.debian.org/923428)) and it crashes with:

> htsjdk.samtools.util.RuntimeIOException: java.io.IOException: Stream closed
> 	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:448)
> 	at uk.ac.babraham.FastQC.Sequence.BAMFile.<init>(BAMFile.java:64)
> 	at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:100)
> 	at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:62)
> 	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.processFile(OfflineRunner.java:152)
> 	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.<init>(OfflineRunner.java:121)
> 	at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:316)
> Caused by: java.io.IOException: Stream closed
> 	at java.base/java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:165)
> 	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
> 	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
> 	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
> 	at htsjdk.samtools.util.BlockCompressedInputStream.readBytes(BlockCompressedInputStream.java:583)
> 	at htsjdk.samtools.util.BlockCompressedInputStream.isValidFile(BlockCompressedInputStream.java:443)
> 	at htsjdk.samtools.SamStreams.isBAMFile(SamStreams.java:51)
> 	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:374)
> 	... 6 more

The full log can be found [here](https://ci.debian.net/data/autopkgtest/unstable/amd64/f/fastqc/2395508/log.gz). I guess our patch is not enough but, I have no clue what to do to fix this bug. Do you have any suggestion?

### Your environment
* version of htsjdk: 2.18.2
* version of java: openjdk 11.0.3
* Debian (testing/unstable)

### Steps to reproduce
Try to process SAM or BAM files using FastQC from the Debian package.

Best,
Dylan

**Comment by cmnbroad** [comment]
@daissi Based on the diff it looks like you removed the line of code that opens the stream in the first place:
`-		fis = new FileInputStream(file);`

**Comment by daissi** [comment]
Indeed, I re-added it and this solves the problem. Thanks :-)
