### ISSUE TITLE
Tribble parsing error message

### ISSUE THREAD

**Issue by jrobinso** [samtools/htsjdk#1462]
Parsing errors in Tribble result in the following error message

```
Error parsing line at byte position: LineIteratorImpl(SynchronousLineReader), for input source: /Users/jrobinso/Downloads/ARHI0A_peaks_std_500.bed
```

This is not helpful, and even if the "byte position" were displayed it would be only slightly more helpful.  I think either the line number, or the text of the line itself, should be displayed.   

This is related but more narrow than https://github.com/samtools/htsjdk/issues/709

**Comment by jrobinso** [comment]
Thanks @yfarjoun , this is a big improvement!

**Comment by yfarjoun** [comment]
my pleasure! anything we can do for our most visible user!

**Comment by lbergelson** [comment]
@yfarjoun I noticed after the fact, there's another nearly identical error message in the QueryingIterator directly below this one.    Maybe we should update that too?
