### ISSUE TITLE
BAMFileReader constructors not public; not accessible from library import

### ISSUE THREAD

**Issue by pshultes** [samtools/htsjdk#1488]
## Before you submit
Make sure your issue is not already in the [htsjdk issue tracker](https://github.com/samtools/htsjdk/issues?q=)

### Description of the issue:
Describe your issue here.
Provide **screenshots** , **stacktraces** , or **logs** where appropriate.

I have imported htsjdk as an external library in an IntelliJ project (java 11/1.8, most recent htsjdk version) but I am unable to construct FileReaders for BAMFiles, only SAMFiles. All of my data are stored as BAMs and are far too large to convert to SAM files. Is there a version of the constructor or work-around I should be using? Is there a different class that I have overlooked that is used to read BAM files?

### Your environment:
* version of htsjdk
* version of java
* which OS

OS= Windows 10
java = 1.8 or 11
htsjdk= current

### Steps to reproduce
If you're reporting a bug, tell us how to reproduce this issue. If possible, include a short **code snippet** or attach **test data** to demonstrate the problem.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

**Comment by lindenb** [comment]
did you try to use a SamReaderFactory https://samtools.github.io/htsjdk/javadoc/htsjdk/htsjdk/samtools/SamReaderFactory.html ?

**Comment by lbergelson** [comment]
@pshultes as @lindenb suggested the recommended way to load bam/sam/cram files is with the SamReaderFactory which figures out what sort of reader you need based on your file type and returns you an initialized reader.  

It's understandably confusing to get started with htsjdk though.  We could really use a good tutorial somewhere.  Take a look at  `PrintReadsExample.java` to see some usage examples.

**Comment by yfarjoun** [comment]
For an example take a look at `htsjdk/src/main/java/htsjdk/samtools/example/ExampleSamUsage.java`

**Comment by lbergelson** [comment]
@pshultes I think this was answered so I'm closing it.  Feel free to reopen if you have further questions.
