### ISSUE TITLE
Include Mjson as a depedency

### ISSUE THREAD

**Issue by lbergelson** [samtools/htsjdk#1493]
As part of support for htsget, we need to be able to read incoming json blobs.  I'm proposing we include the lightweight [Mjson](https://bolerio.github.io/mjson/). It's not super feature rich, but it should enable us to parse the result of web requests without implementing a bunch of code ourself.  ( @andersleung has already prototype htsget support using it) The benefit of this particular json parser is that it's unlikely to conflict with any downstream projects.  It has no dependencies itself.

A more feature rich json library like jackson is likely to be included in many downstream projects and have it's own dependencies.  I don't want to cause dependency conflicts.  We could right our own json parsing code, but that seems like a lot of effort to avoid including a small dependency.  

Since it's a single file we could also just embed the whole thing in our codebase.  

@tfenne @yfarjoun @jrobinso @pshapiro4broad Please let me know if you have comments or objections.

**Comment by tfenne** [comment]
I think this is reasonable.  I really appreciate the effort put into finding a library that is both lightweight and has no dependencies of it's own.  For a library like HTSJDK I think this is very important.  👍 from me.

**Comment by jrobinso** [comment]
No objection here.  IGV uses Googles "gson",  I think we use other google
stuff so its just there for us.    If you use Mjson I can look into
switching to that to be consistent.

**Comment by lbergelson** [comment]
@jrobinso No need to switch.  GSON is a much more powerful library and I'd probably keep using it.  I just want to be sure we're not adding something to will cause dependency issues.

**Comment by lbergelson** [comment]
Thanks for the comments everyone.  Going to close this since it seems like there's no objection.
