### ISSUE TITLE
CRAM code base coding style

### ISSUE THREAD

**Issue by jacarey** [samtools/htsjdk#150]
Update CRAM code base to our code standards. This mostly involves code
style, variable names and standard conventions.

**Comment by nh13** [comment]
@vadimzalunin any movement on this?

**Comment by nh13** [comment]
@vadimzalunin : please submit a pull request with the changes for this fix for our review.  Once we approve, we can close this issue.

**Comment by jacarey** [comment]
https://github.com/samtools/htsjdk/pull/258
Is up to date with java standards for variable names and style.
