### ISSUE TITLE
CRAM code base javadoc and code documentation.

### ISSUE THREAD

**Issue by jacarey** [samtools/htsjdk#151]
There are a number of classes that are lacking documentation. In general any public API methods should be documented (unless they are self explanatory). Also any complicated control logic should be properly commented.

**Comment by nh13** [comment]
@vadimzalunin any movement on this?

**Comment by nh13** [comment]
@vadimzalunin please submit a pull request with changes so we can review.

**Comment by vadimzalunin** [comment]
hopefully fixed in https://github.com/samtools/htsjdk/pull/224

**Comment by jacarey** [comment]
https://github.com/samtools/htsjdk/pull/258

All set and ready to go.
