### ISSUE TITLE
Improve error message "An index is required, but none found"

### ISSUE THREAD

**Issue by juhawilppu** [samtools/htsjdk#1512]
I was trying to run RenameSampleInVcf with files called
- file.vcf
- file.vcf.tbi (index)

and it was failing with error message "An index is required, but none found".

After looking at the source code, it turns out the index file needs to be named as "file.vcf.idx". I'm not sure if this was obvious to others, but the error message could be improved and mention the specific file ending.

### Your environment:
* Picard version: 2.16.0-SNAPSHOT

### Steps to reproduce
```
java -Xms3000m -jar /usr/gitc/picard.jar RenameSampleInVcf \
    INPUT=file.vcf \
    OUTPUT=output.vcf \
    NEW_SAMPLE_NAME=test
```

### Expected behaviour
Command fails with message "An index is required, but none found with file ending .idx".

### Actual behaviour
Command fails with message "An index is required, but none found".

**Comment by yfarjoun** [comment]
tbi is an index for the block-gzipped version of vcf. you'll need to
generate an index off of the vcf itself using IndexFeatureFile (GATK) or
igvtools

**Comment by lbergelson** [comment]
It does seem reasonable to state which index it's looking for though to prevent tbi / idx confusion.
