### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sjaenick** [samtools/htsjdk#1515]
Hi there,

I wasn't able to find a release schedule - any chance we might get a new release soon? 
We're mostly interested in https://github.com/samtools/htsjdk/pull/1495 (which has been merged some time ago, but is not yet part of any htsjdk release)

Thanks in advance.

**Comment by brainstorm** [comment]
I would say that the already merged in htsget support is partially blocking me on https://github.com/igvteam/igv/pull/850.

Also it would be super nice(tm) to get https://github.com/samtools/htsjdk/pull/1529 and https://github.com/samtools/htsjdk/pull/1249 in the upcoming release as well... just my personal #wishlist, I understand if there are other priorities and pressures, keep the good work folks! ;)
