### ISSUE TITLE
CRAM code base test cases.

### ISSUE THREAD

**Issue by jacarey** [samtools/htsjdk#152]
Test cases need to be converted to testng and additional coverage added. A fair amount of
the tests are currently run by main()s. These tests should be converted to
a full testng test suite such that our automated builds can run them. This
is also a good time to look at code coverage. Once the tests are converted
to testng we can run some code coverage plugins to get a good sense of how
well this is currently covered.

**Comment by nh13** [comment]
@vadimzalunin any movement on this?

**Comment by nh13** [comment]
@vadimzalunin we would like the following to accept completion of this issue:
* all CRAM tests use testng
* code coverage report produced on CRAM code
* add any tests to uncovered classes as directed by htsjdk Java developers
* code review accepted by htsjdk Java developers members

**Comment by vadimzalunin** [comment]
added in https://github.com/samtools/htsjdk/pull/224

**Comment by jacarey** [comment]
https://github.com/samtools/htsjdk/pull/258

Cram code coverage is 89%
