### ISSUE TITLE
Are csi-indexed VCF files supported?

### ISSUE THREAD

**Issue by tayabsoomro** [samtools/htsjdk#1556]
### Description of the issue:
Not as much of an issue as it is a question. I am trying to perform variant calling, and I would like to know if CSI indexed VCF files are supported?

**Comment by lbergelson** [comment]
Sorry, CSI indexes are only supported for BAM right now.  Is your reference compatible with tbi indexes?

**Comment by tayabsoomro** [comment]
Yes, I have resorted to using TBI. Thanks for prompt response.
