### ISSUE TITLE
Request that Feature have getters for start/end that use a consistent coordinate system

### ISSUE THREAD

**Issue by bbimber** [samtools/htsjdk#156]
Feature is a very useful interface when dealing with different input file types.  However, the Feature interface explicitly states: "The coordinate conventions for start and end are implementation dependent, no specific contact is specified here."  As a feature request, I would propose that the interface provide some method to obtain the start/end coordinates with a known coordinate scheme, such that every type of feature will give you the same value.  This way you know whether you're getting 0- or 1- based numbers.  This could be either:

1) create get1BasedStart()/get1BasedEnd() methods

2) Create some sort of CoordinateType enum, with 1- and 0-based values.  add a getCoordinateType() method.  

or there are plenty of other options.  Doesnt really matter what, so long as it always returns the same value from any implementation of Feature.

Apologies if there's already a way to get at this problem...

**Comment by magicDGS** [comment]
The `Feature` interface extends [`Locatable`](https://github.com/samtools/htsjdk/blob/909381a31321deb1e411a34fca3d1f75e4fc2410/src/main/java/htsjdk/samtools/util/Locatable.java), and the contract of them says that `getStart()`/`getEnd()`are 1-based. In addition, `BEDCodec` is handling this to convert from 0-based to the `Feature` specifications.

It is this still an issue?

**Comment by lbergelson** [comment]
We changed the contract of `Feature` when we made it implement `Locatable` so it should all be 1-based closed on both ends.  Features in HTSJDK should this contract, but there are existing features in the wild that may not.
