### ISSUE TITLE
aux.bam and aux.sam is not valid file names on windows

### ISSUE THREAD

**Issue by nnordborg** [samtools/htsjdk#157]
Hello,

I have previously been doing some work on Picard and Htsjdk, but now when I try to update to the latest master branch in htsjdk there is a problem with the aux.bam and aux.sam files in the testdata/htsjdk/samtools directory. Apparently it seems like files named 'aux' are forbidden in Windows due to some restrictions since the MSDOS times!!! (https://social.technet.microsoft.com/Forums/windows/en-US/e22c021d-d188-4ff2-a4dd-b5d58d979c58/the-specified-device-name-is-invalid)

Would it be possible for you to change the file names of those two files?

**Comment by jmarshall** [comment]
FYI we recently had to rename test files similarly in htslib (samtools/htslib@9b1cb948e78a51b93473fc1dbd5e05a9c5fddf8b).  Stupid Windows!

**Comment by nnordborg** [comment]
Thanks!
