### ISSUE TITLE
Switching to Python3

### ISSUE THREAD

**Issue by pgrt** [samtools/htsjdk#1582]
Hello,

I am one of the Debian maintainers of htsjdk.

You might be interested in switching to Python3 for the Python scripts in htsjdk. If so, please find the enclosed patch which can help to achieve it.

Best,

Pierre
[80-2to3.txt](https://github.com/samtools/htsjdk/files/7589586/80-2to3.txt)

**Comment by lbergelson** [comment]
@pgrt Thank you, this is a good idea.
