### ISSUE TITLE
Would it be OK to remove the Travis app from the Samtools organisation?

### ISSUE THREAD

**Issue by daviesrob** [samtools/htsjdk#1608]
I'm not sure about the best venue for this discussion, but this seems as good as anywhere...

Following the recent [OAUTH breach](https://github.blog/2022-04-15-security-alert-stolen-oauth-user-tokens/), it seems like a good idea to have a tidy up.  SAMtools dropped Travis in samtools/samtools#1365 and I see htsjdk switched to GitHub Actions in #1572.  As no active repository in the organisation is using it, would anyone mind if I deleted the Travis app?

**Comment by jmarshall** [comment]
:+1: from **samtools/hts-specs** (which has never used Travis CI).

**Comment by lbergelson** [comment]
👍 from samtools/htsjdk

**Comment by daviesrob** [comment]
OK, based on those votes, I've suspended it in the organisation app settings.  If there's no fall-out from that I'll try to remember to uninstall it later.
