### ISSUE TITLE
add getBackingResourceName() to SAMReader

### ISSUE THREAD

**Issue by lbergelson** [samtools/htsjdk#161]
There is currently no way to get information about the datasource backing the SAMReader.  This makes it difficult to return useful error messages when there is any sort of exception.  

It should return a `String` which sufficiently describes the resource  enough that a human could identify which file, url, database, etc was the problem.

**Comment by nh13** [comment]
Would ```SamReader.Type``` help?  Could you give a concrete example? Since you are in the same room, I would be happy to discuss in person.

**Comment by mattsooknah** [comment]
Should be resolved by https://github.com/samtools/htsjdk/pull/168.
