### ISSUE TITLE
EdgeReadIterator (used in Picard's CollectWgsMetrics) doesn't handle intervals correctly

### ISSUE THREAD

**Issue by michaelgatzen** [samtools/htsjdk#1615]
When running Picard's CollectWgsMetrics with an IntervalList, only the start and end coordinates of the first interval in that list are considered. This can be traced back to a bug in EdgeReadIterator and AbstractLocusInfo.

**Comment by michaelgatzen** [comment]
I can't assign this to myself because I'm not a contributor, but I'm working on this issue.

**Comment by lbergelson** [comment]
closed by #1616
