### ISSUE TITLE
What is the non-deprecated replacement for acceptableAlleleBases?

### ISSUE THREAD

**Issue by danking** [samtools/htsjdk#1623]
### Description of the issue:
Hail is trying to update to htsjdk 3.x.x. We currently use `Allele.acceptableAlleleBases`. This fails our build system because its deprecated. Is there a replacement for this method or is it being intentionally removed from the public API?

### Your environment:
htsjdk==3.0.1

### Steps to reproduce
Compile something that uses `htsjdk.variant.variantcontext.Allele.acceptableAlleleBases` with warnings are errors (`-Xfatal-warnings`).

**Comment by lbergelson** [comment]
@danking This is a good question.  I think the reasoning for deprecating that method has been lost in the extremely long time the PR sat and perhaps should not have been deprecated.  It seems like it got caught in the drive to remove the awkwardly named "wouldBe" methods.    I don't see any reasonable replacement at the moment other than trying to create an Allele and catching the inevitable exception which is not a good workflow.    I'm going to de-deprecate  it for 3.0.2.

**Comment by danking** [comment]
Thanks @lbergelson !

**Comment by lbergelson** [comment]
@danking 3.0.2 is on it's way to maven central and should be visible with in the next hour or so.

**Comment by danking** [comment]
Thank you!
