### ISSUE TITLE
Maven central?

### ISSUE THREAD

**Issue by dakl** [samtools/htsjdk#163]
Hi, 

Are you planning on distributing htsjdk on maven central? I can only see 1.118 there, from user "seqdoop" which I expect isn't you guys. 

(The scenario is that I'm using the GATK-framework to develop custom walker but need to update htsjdk from the supplied version 1.120).

thanks

Daniel

**Comment by nh13** [comment]
See: https://github.com/samtools/htsjdk/pull/115 and https://repo1.maven.org/maven2/com/github/samtools/htsjdk/1.128/

Enjoy!
