### ISSUE TITLE
The last-but-one argument of test testQueryAlignmentStart in HtsCRAMCodec30And21QueryTest.java is long

### ISSUE THREAD

**Issue by pgrt** [samtools/htsjdk#1631]
Hello,

In the test file HtsCRAMCodec30And21QueryTest.java, the last-but-one argument of  testQueryAlignmentStart is long but the alignmentStartQueries data provider returns an int instead, leading to test failures on my side.

The attached patch provides a straightforward fix.

[data-types-in-tests.txt](https://github.com/samtools/htsjdk/files/9932465/data-types-in-tests.txt)

Cheers,

Pierre

**Comment by cmnbroad** [comment]
@pgrt Yes, thanks for reporting this!
