### ISSUE TITLE
Move Picard's CompareSAMs functionality into HTSJDK

### ISSUE THREAD

**Issue by mattsooknah** [samtools/htsjdk#165]
The ability to compare two *AM files seems generally useful, especially for unit tests.

There is currently a Picard CLP named CompareSAMs that tests the equality of two such files, and collects more detailed statistics as well. Many unit tests in Picard instantiate this class in a non-CLP context, making dangerous assumptions about mutated fields and such.

It could easily be refactored into a standalone class that takes two SamReaders and returns an object with various collected metrics, with the Picard tool being a thin wrapper. 

Alternatively, if such functionality already exists in HTSJDK, the Picard tool should be using it...

(see also the SamFileValidator / ValidateSamFile duality)

**Comment by nh13** [comment]
I would ask for more clarity around the statement "returns an object with various collected metrics".  Is this object already created, is this proposed, what is the definition (or is that the task)?  Like you said, it could overlap with the ```SamFileValidator```.

**Comment by mattsooknah** [comment]
After talking to several people, I'm no longer convinced that this should be moved to HTSJDK. It has a fairly rudimentary view of whether two SAMRecords are "equal", and seems more useful as a quick command line "diff"-style tool. Let's close this issue for now.
