### ISSUE TITLE
Get coveralls working with Travis CI

### ISSUE THREAD

**Issue by nh13** [samtools/htsjdk#167]
I would like to see code coverage here: https://coveralls.io/r/samtools/htsjdk

**Comment by akiezun** [comment]
I think this is blocked by the transition away from ant. Nothing supports ant anymore.

**Comment by droazen** [comment]
We'll be looking at the ant -> gradle branch in the next code review party

**Comment by tfenne** [comment]
That's great to hear @droazen !

**Comment by yfarjoun** [comment]
I think that this is done! right @droazen

**Comment by droazen** [comment]
Yes, done -- closing
