### ISSUE TITLE
Merging out of order sequence headers results in error

### ISSUE THREAD

**Issue by arahuja** [samtools/htsjdk#169]
Recently, I got an error
```
Cannot merge sequence dictionaries because sequence chrM and chrY are in different orders in two input sequence dictionaries.
```
Can someone explain this error further?

Does this need to be an error or is this case not implemented yet?  Is there a downstream problem if sequence header that are in different orders are still added?

**Comment by nh13** [comment]
Could you post the two sequence dictionaries here so we can compare.  The order in which chromosomes (or reference sequences) are specified is important to how the files are sorted.  Many tools rely on the sort order for performance.  You will need to rectify the order before continuing.

**Comment by arahuja** [comment]
I can post the sequence dictionary, but there there is no question they are in different orders - one places `chrM` first and the other last

```
@SQ	SN:chrM	LN:16571
@SQ	SN:chr1	LN:249250621
@SQ	SN:chr2	LN:243199373
```
vs
```
@SQ	SN:chrX	LN:155270560
@SQ	SN:chrY	LN:59373566
@SQ	SN:chrM	LN:16571
```

My question really was this doesn't seem to be an issue in actually *merging* the the sequence dictionaries but removes other guarantees on the BAM?

**Comment by nh13** [comment]
Order is important, even in sequence dictionaries when merging.

**Comment by MatthewRalston** [comment]
For the sake of posterity, I've encountered this same issue when merging unmapped tophat reads with sorted mapped reads. The solution was to instead merge the tophat outputs accepted_hits.bam and unmapped.bam with Picard MergeSamFiles, using Validation_Stringency=LENIENT.
