### ISSUE TITLE
Ambiguous assertions in the tests

### ISSUE THREAD

**Issue by pgrt** [samtools/htsjdk#1695]
Hello,

While packaging htsjdk 4.0.2 into Debian, I noticed that some tests fail due to ambiguous assertions:

/<<PKGBUILDDIR>>/src/test/java/htsjdk/samtools/SAMRecordUnitTest.java:345: error: reference to assertEquals is ambiguous
        Assert.assertEquals(0L, record.getUnsignedIntegerAttribute(stringTag));
              ^
  both method assertEquals(Object,Object) in Assert and method assertEquals(long,long) in Assert match
/<<PKGBUILDDIR>>/src/test/java/htsjdk/samtools/SAMRecordUnitTest.java:346: error: reference to assertEquals is ambiguous
        Assert.assertEquals(0L, record.getUnsignedIntegerAttribute(binaryTag));
              ^
  both method assertEquals(Object,Object) in Assert and method assertEquals(long,long) in Assert match
/<<PKGBUILDDIR>>/src/test/java/htsjdk/samtools/SAMRecordUnitTest.java:349: error: reference to assertEquals is ambiguous
        Assert.assertEquals(BinaryCodec.MAX_UINT, record.getUnsignedIntegerAttribute(stringTag));
              ^
  both method assertEquals(Object,Object) in Assert and method assertEquals(long,long) in Assert match
/<<PKGBUILDDIR>>/src/test/java/htsjdk/samtools/SAMRecordUnitTest.java:350: error: reference to assertEquals is ambiguous
        Assert.assertEquals(BinaryCodec.MAX_UINT, record.getUnsignedIntegerAttribute(binaryTag));
              ^
  both method assertEquals(Object,Object) in Assert and method assertEquals(long,long) in Assert match

and so on...

The attached patch fixes this.

Best,

Pierre

[180-ambiguous-assertions.txt](https://github.com/samtools/htsjdk/files/13670875/180-ambiguous-assertions.txt)

**Comment by lbergelson** [comment]
@pgrt Interesting.  I wonder why you see an issue here and I don't.  Is it possible you're building against a different version of TestNG or Java?

With Java 17 and TestNG 7.7.0 I don't get any ambiguities.
