### ISSUE TITLE
OldDbSNPFeature uses 0-based locations

### ISSUE THREAD

**Issue by lbergelson** [samtools/htsjdk#181]
Other features return 1-based locations.  This should be fixed.  Or we should delete OldDbSNPFeature.

Does anyone use this?

**Comment by vdauwera** [comment]
I'm not aware that anyone uses this anymore, and it has been deprecated for a while. So I would recommend deleting it. If someone complains we can always necromance it back.

**Comment by nh13** [comment]
:+1:

**Comment by nenewell** [comment]
CountRecords.getFeatureCodec() in tribble.example returns an OldDbSNPCodec for .snp and .rod feature files. How should we handle? Just comment out the if statement as was done for VCFCodecs and SoapSNPCodecs in this method? Thank you.

**Comment by vdauwera** [comment]
Yes, please comment out those lines in the same way. Usually we'd delete rather than comment out but in this case I think it's probably good to have a conveniently accessible record of the different formats (as opposed to having it buried in the git history).

**Comment by nenewell** [comment]
Will do.
