### ISSUE TITLE
Support VN:1.5

### ISSUE THREAD

**Issue by jeremiahsavage** [samtools/htsjdk#183]
I've used biobambam to merge some files, and it ouputs
`@HD VN:1.5 SO:coordinate`
using https://github.com/gt1/libmaus/blob/master/src/libmaus/bambam/BamCatHeader.hpp#L116

According to the spec ( http://samtools.github.io/hts-specs/SAMv1.pdf ), 1.5 is the current version, but picard ValidateSamFile gives an error, which the diff below eliminates.

```
diff --git a/src/java/htsjdk/samtools/SAMFileHeader.java b/src/java/htsjdk/samtools/SAMFileHeader.java
index 2e237c4..ac361b1 100644
--- a/src/java/htsjdk/samtools/SAMFileHeader.java
+++ b/src/java/htsjdk/samtools/SAMFileHeader.java
@@ -46,9 +46,9 @@ public class SAMFileHeader extends AbstractSAMHeaderRecord
     public static final String VERSION_TAG = "VN";
     public static final String SORT_ORDER_TAG = "SO";
     public static final String GROUP_ORDER_TAG = "GO";
-    public static final String CURRENT_VERSION = "1.4";
+    public static final String CURRENT_VERSION = "1.5";
     public static final Set<String> ACCEPTABLE_VERSIONS =
-            new HashSet<String>(Arrays.asList("1.0", "1.3", "1.4"));
+            new HashSet<String>(Arrays.asList("1.0", "1.3", "1.4", "1.5"));

     /**
      * These tags are of known type, so don't need a type field in the text representation.
```

**Comment by vdauwera** [comment]
@nh13 Do I understand correctly that this is just a matter of adding "1.5" to the list of acceptable versions? Or is there any actual dev/validation work required?

**Comment by yfarjoun** [comment]
It would be good to know what the differences are between 1.4 and 1.5 and
make sure (i.e. test?) that we actually support 1.5 before we do this...

no?

**Comment by vdauwera** [comment]
You tell me, I don't have a sense of how much changes between spec versions. Would be awfully convenient if there was an official release corresponding to each version of the spec, with exotic things like, say, release notes spelling out the important differences.

**Comment by jmarshall** [comment]
That would indeed be convenient (and is samtools/hts-specs#47), but like many convenient things it is temporarily thwarted by the existence of day jobs.

Fortunately a minute or two with `git log -S1.5 SAMv1.tex` brings you to samtools/hts-specs@80bc68f7619da60eaa4f43a16878c4675e930570, showing that **1.5** corresponds to the addition of the `0x800 SUPPLEMENTARY` flag and the `SA:Z` optional field.

**Comment by nh13** [comment]
@vdauwera given those two changes, we should have a test case that has a read with the `0x800 SUPPLEMENTARY` flag (see @jmarshall link above for a good example contained in the actual spec doc) and another read with the `SA:Z` optional field, and make sure that they pass ```ValidateSamFile```.  Those may already be there, given the spec

**Comment by vdauwera** [comment]
Hah, fair enough. Those pesky day jobs. So thanks for the git trick, that's pretty handy! 

Considering that commit is dated from 2013, I'm inclined to assume things are probably ok, but we can run a few tests to be sure. I guess we just need a bam snippet with a couple of supplementary alignments and the new field.

**Comment by vdauwera** [comment]
Well, this will teach me to leave a comment unfinished and finally post it without looking for updates. 

OK @nh13, we'll get this tested.

**Comment by vdauwera** [comment]
Closing as this was finished in #285
