### ISSUE TITLE
How to work with BED or vcf files

### ISSUE THREAD

**Issue by aiirtime** [samtools/htsjdk#187]
Hello,
I'm unsure if this is the right way to ask a developing question. But I searched for examples how to use the htsjdk and for the SamReader/SamReaderFactory there are nice examples.
Is there also some available examples how to read BED or vcf files?

Best Air

**Comment by aiirtime** [comment]
for example like that:
BEDCodec bed_c = new BEDCodec();
TribbleIndexedFeatureReader bed_file = new TribbleIndexedFeatureReader("/x.bed", bed_c, false);
CloseableTribbleIterator<BEDFeature> tribble_it = bed_file.iterator();
while(tribble_it.hasNext()){
BEDFeature bed_entrie = tribble_it.next();}

**Comment by abaumann** [comment]
Every example I observe of this makes use of the AbstractFeatureReader: 

```java
BEDCodec codec = new BEDCodec();
AbstractFeatureReader reader = AbstractFeatureReader.getFeatureReader(filepath, codec, false);
```

This has the advantage of being more generally useful to return either a `TribbleIndexedFeatureReader` like you used, or a `TabixFeatureReader` if you are reading a tabix indexed file.  

Additionally, you can also use the for-each syntax:
```java
Iterable<BEDFeature> iter = reader.iterator();
int count = 0;
for (BEDFeature feat : iter) {
    // do something here
}

**Comment by vdauwera** [comment]
@aiirtime Can you indicate whether this answered your question? If so we'd like to close this issue.
