### ISSUE TITLE
Bug when parsing spliced BAM record with very large intron

### ISSUE THREAD

**Issue by s-andrews** [samtools/htsjdk#196]
I've had a bug report against our software which appears to be an underlying bug in the htsjdk parser for BAM files.  The read which fails to parse is a spliced read with a huge intron in it (226Mbp).  When parsing the cigar string htsjdk corrupts this value (it looks like it overflows so I get a negative value), but if I use samtools to convert the bam file to sam, then htsjdk reads it just fine.

I've put the example files I used (only 1 read in them) up at:

http://ftp2.babraham.ac.uk/ftpusr68/

Some code which illustrates the problem is below.  For the sam file I get:
Cigar is 109M226643263N25M17S Start=10002 End=226653398

..but for the equivalent BAM file I get:
Ignoring SAM validation error: ERROR: Record 1, Read name GR_10257_idx_5/2, bin field of BAM record does not equal value computed based on alignment start and end, and length of sequence to which read is aligned
Cigar is 109M-41792193N25M17S Start=10002 End=-41782058

This is using htsjdk-1.129.jar

import java.io.File;

import htsjdk.samtools.SAMRecord;
import htsjdk.samtools.SamReader;
import htsjdk.samtools.SamReaderFactory;
import htsjdk.samtools.ValidationStringency;

public class PicardCigarBug {
	
	public static void main (String [] args) {
		
		File smallBugBam = new File("C:/Users/andrewss/Desktop/Bug/small.bam");
//		File smallBugBam = new File("C:/Users/andrewss/Desktop/Bug/small.sam");
		
		SamReaderFactory samFactory = SamReaderFactory.makeDefault().validationStringency(ValidationStringency.LENIENT);
		SamReader inputSam = samFactory.open(smallBugBam); 

		
		for (SAMRecord samRecord : inputSam) {
			System.err.println("Cigar is "+samRecord.getCigarString()+" Start="+samRecord.getAlignmentStart()+" End="+samRecord.getAlignmentEnd());
		}
	}
}

**Comment by vdauwera** [comment]
Oops, didn't mean to close this -- wrong button. 

@s-andrews I agree this looks like an overflow. Forgive the naive question, but does it make biological sense to want to try to handle such a large intron? To be honest my instinct would be to treat this as a bad input and filter out this read.

@nh13 Has any thought been put into setting specific thresholds for what size elements are acceptable in CIGARs, or are we just using some variable type's max value? Would be good to do the former if only so we could document what are the limitations. Unless we do want to be able to handle insanely large introns (no offense @s-andrews)?

**Comment by s-andrews** [comment]
I don't actually think this makes any biological sense, but if there are programs which are generating these long splices (which apparently there are) then the program should parse them correctly, or give a sensible error if the value is too long, rather than just overflowing.

Personally I'd have thought an int (31 bits) should be enough for this.  I don't know of any examples of individual chromosomes which are longer than this, which is the ultimate limit.  Internally picard must be using something like this anyway since parsing the same data from a sam file works - it's only the BAM parser which is affected.

**Comment by jmarshall** [comment]
The practical limit on this is the way CIGAR is encoded in the BAM format.  It gets 28 bits: there is a `uint32_t`, but the bottom four bits are used to encode the `MIDN`… operator.

Your N operator has a length > 2<sup>27</sup> so sets the top/"sign" bit of that `unit32_t`, so probably the htsjdk bug is that it is doing an arithmetic shift to unpack the cigar length rather than a logical shift.

**Comment by nh13** [comment]
Looks like an arithmetic shift (```>>```) is being used rather than a logical shift (```>>>```): https://github.com/samtools/htsjdk/blob/master/src/java/htsjdk/samtools/BinaryCigarCodec.java#L84

@vdauwera looks like a bug to me, but we should also fix the other arithmetic shifts in this code too.

**Comment by vdauwera** [comment]
Ah ok, thanks all for the very helpful clarifications. This looks like a very secon-friendly task. 

I'll put in a separate task to find & fix other instances of injudicious arithmetic shifts since that's a broader scope than this particular bug fix.

**Comment by nh13** [comment]
@vdauwera only need to look for incorrect arithmetic shifts in this class as it affects the cigar decoding and encoding, so probably not worth another task.

**Comment by vdauwera** [comment]
To be clear, the work for this issue consists of:

1. Fix the shift type that is causing the bug  
2. Add a test to check that the test case included above gets handled correctly

**Comment by vdauwera** [comment]
Oh I thought you meant throughout the codebase -- so it's just the operations on lines 50 and 86 then?

**Comment by nh13** [comment]
Ah, now you have made me think about it.  Line 50 shouldn't matter since it is shifting up not down.

**Comment by vdauwera** [comment]
@s-andrews Do we have your permission to use your bam snippet in the integration test set?

**Comment by vdauwera** [comment]
Thanks Nick!
