### ISSUE TITLE
Minimum Java Version Policy

### ISSUE THREAD

**Issue by nh13** [samtools/htsjdk#209]
In an effort to support development on modern platforms as well as giving the community sufficient notice of migrations, I would like to propose the following plan for minimum Java version for HTSJDK.  I will welcome comments until April 6th 2015 at which a time we will make a decision based upon the communities feedback and discussion. 

> We will support all Java SE versions supported by Oracle until at least six months after Oracle's Public > Updates period has ended (see: http://www.oracle.com/technetwork/java/eol-135779.html).
> 
> Below is a handy chart that I would like us to put in our README.md:
> 
> Java SE Major Release | End of Java SE Oracle Public Updates | Proposed End of Support in HTSJDK | Actual End of Support in HTSJDK
> ----- | ----- | ----- | ----- | -----
> 6 |	Feb 2013 | Aug 2013 | Oct 2015
> 7 | Apr 2015 | Oct 2015 | Oct 2015
> 8** | Mar 2017 | Sep 2017 | Sep 2017
> ** to be finalized

**Comment by lbergelson** [comment]
:+1:

**Comment by jrobinso** [comment]
This looks good.   We have dropped support for 6 in IGV as of the latest release,  so if you're maintaining support through Oct for our sake you don't need to.    Hopefully Oracle is better at keeping Macs up to date than Apple was.

**Comment by akiezun** [comment]
Jim, what Java version are you on now?

On Monday, March 23, 2015, Jim Robinson <notifications@github.com> wrote:

> This looks good. We have dropped support for 6 in IGV as of the latest
> release, so if you're maintaining support through Oct for our sake you
> don't need to. Hopefully Oracle is better at keeping Macs up to date than
> Apple was.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/samtools/htsjdk/issues/209#issuecomment-85239684>.
>


-- 
Sent from Gmail Mobile

**Comment by jrobinso** [comment]
1.7
> Jim, what Java version are you on now?
>

**Comment by vdauwera** [comment]
April 6th 2015 has come and gone. Considering the lack of uproar I suggest we go ahead with the proposed policy.

**Comment by nh13** [comment]
Already done, added to the README.md.
