### ISSUE TITLE
IndexFactory.createTabixIndex() not working for .vcf.gz files?

### ISSUE THREAD

**Issue by bbimber** [samtools/htsjdk#210]
I find that calls to IndexFactory.createTabixIndex() are consistently failing for VCF files with an error along the lines of "ERROR: Your input file has a malformed header: We never saw the required CHROM header line (starting with one #) for the input VCF file".  I was trying to see where this might be going wrong.  Should IndexFactory.initStream() account for the potential of GZ input files?

**Comment by jmthibault79** [comment]
Duplicate of #184
