### ISSUE TITLE
A bug in LiftOver?

### ISSUE THREAD

**Issue by superbobry** [samtools/htsjdk#213]
Hello, we've discovered an issue with the way `LiftOver` works. Consider remapping an interval from `hg18` to `hg19`:

``` java
final LiftOver liftOver = new LiftOver(hg18ToHg19);
final Interval query = new Interval("chr1", 2475276, 2475390);
final Interval remapped = liftOver.liftOver(query, .8);
```

`LiftOver` remaps the query interval to [2499028, 2499127] on the negative strand, while the correct interval seems to be [2499028, 2499142]. Below are the sequences corresponding to query, remapped and correct intervals:

```
agatcgtgaccaggagggcaatggccaggcctcggcctcagccccctgcctggcctgcactggcacagagcaggggaggtgcaggccgaccttgaaggcgcaggagtggaggggg

gggcaatggccaggcctcggcctcagccccctgcctggcctgcactggcacagagcaggggaggtgcaggccgaccttgaaggcgcaggagtggaggggg

agatcgtgaccaggagggcaatggccaggcctcggcctcagccccctgcctggcctgcactggcacagagcaggggaggtgcaggccgaccttgaaggcgcaggagtggaggggg
```

It's easy to see that the remapped interval is trimmed.

**Comment by ronlevine** [comment]
@superbobry Since the query is 115 bases and the remapped bases exactly match 100 of the query bases, the fraction of remapping bases = 100/115 = 0.87, which is greater than 0.80. So, the tool looks like it working as advertised. If in fact there is a better remap, then the tool can be improved. How did you find the "correct" interval?

**Comment by iromeo** [comment]
@ronlevine We had our own implementation based on ucsc chain files. After we had switched to 'htsjdk' some our tests failed, so we noticed this difference. We agree, that tool "works as advertised" here, but if you simply extend the interval you've get much more better mapping. We expect liftover no to trim reads and provide mapping as long as possible

**Comment by ronlevine** [comment]
I ran UCSC's web based LiftOver with the same parameters as your test case and got the same interval as htsjdk's implementation.
![screen shot 2017-06-30 at 9 10 24 am](https://user-images.githubusercontent.com/8916428/27737116-f97490b4-5d74-11e7-95d5-f4cfc55638ed.png)

If you would like to enhance the current implementation, please submit a patch.

**Comment by ronlevine** [comment]
@iromeo I would like to close this issue. Otherwise, please provide a patch for this tool.
