### ISSUE TITLE
addMetaDataLine duplicates sequence dictionary of VCF header

### ISSUE THREAD

**Issue by sndrtj** [samtools/htsjdk#214]
Hi there,

When adding an info field to a VCF header with the sequence dictionary of the header gets duplicated. Specifically, `addMetaDataLine` duplicates the sequence dictionary. This leads to an `IllegalArgumentException` when using that header later to specify the reference dictionary for a `VariantContextWriterBuilder`. I've created a gist [here](https://gist.github.com/sndrtj/5ea8451da628cf51ce3e) that illustrates the problem. 

In intellij's debug mode it becomes apparant that the  `contigMetaData` ArrayList gets duplicated upon calling `addMetaDataLine`. 

Screenshot of the debugger just before `addMetaDataLine`: 
![Just before `addMetaDataLine`](https://cloud.githubusercontent.com/assets/7782240/7052148/03639a26-de2d-11e4-8935-07309a492834.png)

And just after `addMetaDataLine`:
![screenshot from 2015-04-08 20 27 14](https://cloud.githubusercontent.com/assets/7782240/7052232/96d836a4-de2d-11e4-9a14-9faf4e300dc3.png)

Is this intended behaviour? This seems like an unintended side-effect of adding an info field?

**Comment by abaumann** [comment]
This looks like an unintended side effect of the addMetaDataLine call - I tracked this down to find that the contigMetaData gets duplicated when you add a metadata line - which is not intended and causes that sequence dictionary failure (addMetadataLine(...) calls loadMetaDataMaps() which adds to lists that already contain items) - I will talk to someone familiar with this code to see if there was some sort of intention here or if it is simply a mistake...

**Comment by sndrtj** [comment]
Any more updates on this issue?

**Comment by abaumann** [comment]
Sorry for the delay, this should be resolved by https://github.com/samtools/htsjdk/pull/215

**Comment by sndrtj** [comment]
Oh wow, thanks!
