### ISSUE TITLE
CRAM 3.0 Support in HTSJDK

### ISSUE THREAD

**Issue by nh13** [samtools/htsjdk#222]
Current branch being proposed:https://github.com/samtools/htsjdk/tree/cam3_update

Acceptance tests:
- issues #124, #148, #150, #151, and #152 are closed
- Be able to read and write all CRAM 3.0 test files/cases as specified by Vadim: CRAM implementors standard acceptance files.  @vadimzalunin I believe that you have these somewhere; ew would like to include them here.

**Comment by nh13** [comment]
@vadimzalunin, from James Bonfield, here are the test files and a test script: https://github.com/samtools/htslib/tree/develop/test

These should be unit tests within htsjdk.

**Comment by vadimzalunin** [comment]
Added tests for the sam file. Not sure if C-generated CRAM files should be added as well.

**Comment by jacarey** [comment]
https://github.com/samtools/htsjdk/pull/258

This has been rebased to master and is undergoing final review.

**Comment by cmnbroad** [comment]
@vadimzalunin Can this be closed ?
