### ISSUE TITLE
Increase number of likelihoods allowed in PL field

### ISSUE THREAD

**Issue by vdauwera** [samtools/htsjdk#229]
Needed to fix https://github.com/broadinstitute/gsa-unstable/issues/937

There is a bug occurring in GATK (reported independently several times already) due to large numbers (hundreds) of alternative alleles in the processed loci in some users' GVCF files. Assuming there are N alleles in diploid organism, then VCF file stores N * (N - 1) / 2 likelihoods in the PL field. However, htsjdk reads only first 10,000 likelihoods:

LINE 755-766 in htsjdk.variant.vcf.AbstractVCFCoded.java:

    private final String[] INT_DECODE_ARRAY = new String[10000];
    private final int[] decodeInts(final String string) {
    final int nValues = ParsingUtils.split(string, INT_DECODE_ARRAY, ',');
    final int[] values = new int[nValues];
    try {
    for ( int i = 0; i < nValues; i++ )
    values[i] = Integer.valueOf(INT_DECODE_ARRAY[i]);
    } catch (final NumberFormatException e) {
    return null;
    }
    return values;
    }

Since GATK assumes that there are N * (N - 1) / 2 likelihoods, then it eventually jumps out of the 10,000 array.

Unless there is a good reason for hardcoding a 10K limit, we'd like to relax this to allow considering larger numbers of alternate alleles, which becomes more likely to happen now that we're calling indels in very large cohorts.

**Comment by nh13** [comment]
@vdauwera gsa-unstable is not public, do you want to link that here?

**Comment by vdauwera** [comment]
I'm including the link for the internal team's convenience. Unless it's frowned upon to do this, I don't see the harm?

**Comment by nh13** [comment]
It doesn't allow the community to comment or be involved when the details are hidden. 

N

Thumb typed for added typos

**Comment by vdauwera** [comment]
Well that's why I copied the issue description almost verbatim. There are no details hidden/missing. 

If people want to see the original bug reports, see the support forum here: http://gatkforums.broadinstitute.org/discussion/comment/20470#Comment_20470

**Comment by nh13** [comment]
Perfect thank you!

Thumb typed for added typos

**Comment by vdauwera** [comment]
@ronlevine is taking this one via fork

**Comment by ronlevine** [comment]
Do you have the original input variant from the user?

**Comment by vdauwera** [comment]
Yep, see filepath in https://github.com/broadinstitute/gsa-unstable/issues/856

**Comment by ronlevine** [comment]
Work being done on the fork https://github.com/ronlevine/htsjdk.git on the branch rhl_increase_num_likelihoods.

**Comment by ronlevine** [comment]
Added the pull request from the fork: https://github.com/samtools/htsjdk/pull/241

**Comment by johnwallace123** [comment]
I've also been hit by this issue, and I was wondering if it's worthwhile to add a split method in the ParsingUtils that returns its tokens via Vector<String>.  This would allow theoretically unlimited splitting with the same efficiency (given careful preallocation).  The downside is that wherever we want to utilize theoretically unlimited splitting, we would need to change the function call.

I've noticed in the AbstractVCFCodec, there are a few other places that this could come up, as GTValueArray, genotypeKeyArray, infoFieldArray and infoValueArray all have hard coded limits (of 100,100,1000,1000, respectively)

**Comment by ronlevine** [comment]
This seems like it's reinventing the wheel. From org.apache.commons, we already have commons-jexl, why not commons-lang3? It's a powerfull library and would save a lot of coding effort in the future.

**Comment by johnwallace123** [comment]
Can't say I disagree with you on that front.  It's not a terribly difficult
function to add, but I don't want to have to write all those test cases!  I
assumed that there was a specific need to implement the ParsingUtils.split,
but it's possible that the commons-lang3 library obviates that need.  I
have seen in the past that rewriting a text parser incorporating
assumptions can be substantially faster than the "generic" versions, but it
should only be done if profiling indicates that's where the bottleneck is.

If we do go with using the commons-lang3 library, would it be beneficial to
replace the ParsingUtils.split code with the corresponding
StringUtils.split function?  This way, we wouldn't have to count the number
of delimiters, and as an added bonus, the StringUtils.split function will
collapse repeated delimiters and in general, do the Right Thing.

**Comment by bpow** [comment]
Note that the issue of having a custom `StringUtils.split` instead of using `String.split` for performance reasons is likely moot in versions of java from 7 and beyond, so when support for jdk 6 is dropped this code can be substantially cleaned up (see my comment in #246 )
