### ISSUE TITLE
Subtracting one interval list from another

### ISSUE THREAD

**Issue by niruchennagiri-claritas** [samtools/htsjdk#234]
I am trying to subtract one interval list from another using pseudo-code below:
IntervalList testIntervals1 = new IntervalList(someHeader);
testIntervals1.add(a-few-intervals);
IntervalList testIntervals2 = new IntervalList(someHeader);
testIntervals2.add(a-few-intervals);
IntervalList.subtract(testIntervals1, testIntervals2);

This should work according to the documentation but when I implement it my compiler says I have to pass Collection<IntervalList> instead of IntervalList to subtract.

What is the easiest way to subtract using htsjdk?
Thanks.

**Comment by yfarjoun** [comment]
Hmm. there is a function with the signature you are looking for:


*public static IntervalList subtract(final IntervalList lhs, final
IntervalList rhs)*
perhaps you need to update your HTSJDK?

**Comment by niruchennagiri-claritas** [comment]
The only version available on Maven is 1.118. Should that version have this method implemented?
Thanks.

**Comment by yfarjoun** [comment]
I'm not sure why you are not seeing the other methods, but if you like you
can wrap your IntervalList's with a singelton:

Collections.singletonList(lhs)

Y.

**Comment by lbergelson** [comment]
Version 1.130 is available in maven central.  [See here](http://search.maven.org/#artifactdetails%7Ccom.github.samtools%7Chtsjdk%7C1.130%7Cjar)

if you're using maven this is the right dependency to use

```
<dependency>
    <groupId>com.github.samtools</groupId>
    <artifactId>htsjdk</artifactId>
    <version>1.130</version>
</dependency>
```

**Comment by niruchennagiri-claritas** [comment]
Thanks.
I got the above maven repository and my code is below:
IntervalList test1 = new IntervalList(new SAMFileHeader());
        test1.add(new Interval("chr1", 1000, 2000));
        IntervalList test2 = new IntervalList(new SAMFileHeader());
        test2.add(new Interval("chr1", 900, 2000));
   
       IntervalList minus1 = IntervalList.subtract(test1, test2);
        IntervalList minus2 = IntervalList.subtract(test2, test1);
        System.out.println(minus1.getUniqueBaseCount());
        System.out.println(minus2.getUniqueBaseCount());

I get 0 for both base counts. Do you know what could be happening? Does it need the correct header to work?

**Comment by yfarjoun** [comment]
Yes, this seems to indicate that more input checking is required...please
add "chr1" to your header (and use the same header for both lists).

**Comment by niruchennagiri-claritas** [comment]
It worked after I supplied the header. Thanks for your help.
