### ISSUE TITLE
Bug in DuplicateScoringStrategy

### ISSUE THREAD

**Issue by mattsooknah** [samtools/htsjdk#256]
DuplicateScoringStrategy.compare() compares two records, essentially returning score(rec2) - score(rec1). However, it has:

``` java
// always prefer paired over non-paired
if (rec1.getReadPairedFlag() != rec2.getReadPairedFlag()) return rec1.getReadPairedFlag() ? 1 : -1;
```

The signs are flipped. Luckily, the only place where this method is called (in MarkQueue) does the correct version of the comparison earlier on, so currently I think this is a no-op bug. But it should still be fixed.

**Comment by nh13** [comment]
https://github.com/samtools/htsjdk/blob/919e901557258db71501d825a4aaeb031759e76e/src/java/htsjdk/samtools/DuplicateScoringStrategy.java#L94
