### ISSUE TITLE
Change of HashMap to LinkedHashMap in AbstractSAMHeaderRecord.java may be responsible for major slowdowns in GATK tools

### ISSUE THREAD

**Issue by vdauwera** [samtools/htsjdk#257]
A GATK user is complaining that a job that took 19 hours with GATK 3.3 is now taking 75 hours with 3.4 (reproducibly, not a system issue), and has tentatively traced the runtime increase to SAMReadRecordGroup.

@jacarey suggests the following change in AbstractSAMHeaderRecord may be responsible:

    -    private final Map<String,String> mAttributes = new HashMap<String, String>();
    +    private final Map<String,String> mAttributes = new LinkedHashMap<String, String>();

As part of commit https://github.com/samtools/htsjdk/commit/f668a5b3b1d576d493b5122acfc051a5b2b83c5a

This Issue was generated from your [forums] 
[forums]: http://gatkforums.broadinstitute.org/discussion/comment/21373#Comment_21373

**Comment by droazen** [comment]
Discussed in person, but going to go on record here as expressing my skepticism that this change could be responsible for the performance regression -- `LinkedHashMap` adds only a small amount of overhead to the basic `HashMap`, and is actually faster for some operations (such as iterating over all the elements in the map, which is something that `Map.equals()` does).

Recommend running a profiler to see what's really going on.

**Comment by vdauwera** [comment]
User has proposed a patch to GATK that seems to resolve the problem, so I'm closing this and following up in GATK
