### ISSUE TITLE
ReferenceSequenceFileWalker uses IndexedFastaSequenceFile which is rather inefficient

### ISSUE THREAD

**Issue by tfenne** [samtools/htsjdk#269]
I'll start by saying that I'm happy to submit a PR for this, but am looking to have a bit of discussion about the right way to fix the problem first.

I'm running into problems where Picard's CollectMultipleMetrics (and other programs) are running very slowly on one system that I have access to.  Running on a tiny BAM (2MB) CollectMultipleMetrics is taking over half an hour on the system I'm having trouble on.  When I monitor it with thread dumps, every single dump shows the main thread stuck in this spot:

```
java.lang.Thread.State: RUNNABLE
  at sun.nio.ch.FileDispatcherImpl.pread0(Native Method)
  at sun.nio.ch.FileDispatcherImpl.pread(FileDispatcherImpl.java:52)
  at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:220)
  at sun.nio.ch.IOUtil.read(IOUtil.java:197)
  at sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:708)
  at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:694)
  at htsjdk.samtools.reference.IndexedFastaSequenceFile.getSubsequenceAt(IndexedFastaSequenceFile.java:202)
  at htsjdk.samtools.reference.IndexedFastaSequenceFile.getSequence(IndexedFastaSequenceFile.java:164)
  at htsjdk.samtools.reference.ReferenceSequenceFileWalker.get(ReferenceSequenceFileWalker.java:89)
  at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:110)
```

The filesystem the reference fasta is on is quite slow - simpling cat'ing the file into WC take ~3 minutes.  But reading the file with htsjdk's ReferenceSequenceFileWalker is taking ~30 minutes.  Digging a little deeper I noticed that things are a little strange.

SinglePassSamProgram (which CollectMultipleMetrics extends) uses a ReferenceSequenceFileWalker to access the reference, because it assumes it will need most/all of the sequence at some point and it will traverse the genome in order.  ReferenceSequenceFileWalker in turn uses ReferenceSequenceFileFactory to create a ReferenceSequenceFile to access the underlying reference.  RSFF _always_ returns an Indexed reader if there is a .fai file present.  So when ReferenceSequenceFileWalker wants to load the next chromosome it vectors [eventually] to `IndexedFastaSequenceFile.getSubsequenceAt( String contig, long start, long stop )`

That method uses FileChannels and Buffers and ends up doing thousands or millions of 128kb file channel reads.  It is far from the most efficient way to read an entire large fasta linearly, which is what ReferenceSequenceFileWalker wants.

A quick change to RSFW to force use of the non-indexed fasta reader speeds things up about 13-fold in my hands.

The question is how best to enact this change.  Some options include:
1. Simply change ReferenceSequenceFileWalker to call new FastaReferenceSequenceFile(file) instead of using the factory. The downside is that this doesn't check extensions (like the factory) and would break any future support for other file types that the factory might provide.
2. Change the factory to add methods indicating whether or not an indexed reader is desirable, and change ReferenceSequenceFileWalker to request non-indexed readers
3. Change IndexFastaSequenceReader to be more efficient when reading whole contigs (or just large subsequences?) maybe using seekable streams instead of file channels and buffers
4. Something else?

**Comment by lbergelson** [comment]
Would [CachingIndexFastaSequenceFile](https://github.com/broadinstitute/hellbender/blob/af16a71d2c76c57d00112da3694f8e5fcd0e1b73/src/main/java/org/broadinstitute/hellbender/utils/fasta/CachingIndexedFastaSequenceFile.java) help with this?  We're happy to push it down to htsjdk.  It caches chunks of reference so iterating over the whole file in order is very fast.

**Comment by tfenne** [comment]
Taking a quick look, I don't think it would help.  The reference is read only once in the use case described, but that the code in IndexedFastaSequenceFile is very inefficient if you want to just load all of each chromosome in order.  It looks like CachingIndexFastaSequenceFile delegates the actual I/O to IndexFastaSequenceFile but then puts a cache around it, so I can't see that helping unfortunately.

**Comment by nh13** [comment]
Is there a possibility of increasing the read size from 128kb?  In any case, it seems like having control over configuring the factory before returning a walker seems reasonable.

**Comment by tfenne** [comment]
@nh13 Upping the buffer size doesn't help much.  Running some tests this morning, using the streaming read from the non-index fasta reader my test takes ~30 seconds; using the indexed reader and the default 128kb buffer takes 6 minutes; upping the buffer to 4MB (about as high as I'm willing to go since it effects all buffers in samjdk) still took 6 minutes.

I'll take a look at changing the factory so that I can request the non-indexed reader by choice.

**Comment by magicDGS** [comment]
Could this be closed, @tfenne?
