### ISSUE TITLE
Builds are failing a lot because of failed FTP tests

### ISSUE THREAD

**Issue by lbergelson** [samtools/htsjdk#276]
All of the tests that make FTP connections seem to be failing at a very high rate since I switched us to travis container builds.  I'm talking with travis to figure out what is going on, but we might want to switch back to non-container build until it's resolved.

**Comment by jacarey** [comment]
These tests have always been a bit fritzy. Ideally we should have an embedded ftp server that comes up and serves files locally. I wouldn't be surprised if we are hitting some kind of connection throttling on the ftp server (I think we open and close a connection with each test)

**Comment by lbergelson** [comment]
Should we move tests to use something like http://mockftpserver.sourceforge.net/ ?
