### ISSUE TITLE
Start brainstorming updates for the switch java 8

### ISSUE THREAD

**Issue by lbergelson** [samtools/htsjdk#290]
I think it would be a good time to start compiling at list of compelling TODO's for the upcoming transition to java 8.  This might also be a good time to think about areas of the API that have become outdated and could be updated.  

Some thoughts:
+ Refactor the `SamRecordFilter` to be a functional interface with a default implementation of `filterOut(first, second)`.
+ Remove all pre-java 8 date/time references and replace with the new saner Java 8 versions.  
+ Add default methods to `Locatable` for things like `overlaps`

In terms of API changes that aren't directly related to the java update but maybe it's a good time to start thinking about them:

+ harmonize accessor names across htsjdk (`getContig` vs `getReference` etc)
+ update the naming in `SamRecord` to reflect the new nomenclature in the SAM spec  (Mate vs Template etc), and try to be compatible with GA4G nomenclature when it makes sense to be
+ fix or suppress the warnings
+ switch to semantic versioning so people can tell when we've made backwards incompatible changes

What do other people think?

**Comment by akiezun** [comment]
@lbergelson what's the next step here?

**Comment by lbergelson** [comment]
No one else seemed interested in this, so I guess we close it?  I think the things I suggested are all good things to do if not particularly high priority.  I'll open tickets for them.  We already have #443

**Comment by vdauwera** [comment]
Assuming the title is misleading and you're talking about enhancements not related to switching to java 8 (seems to me that ship has long sailed) I support opening specific issues and closing this one.

**Comment by lbergelson** [comment]
The idea was to brainstorm improvements that would be enabled by switching to java 8.  We've already switched, and there hasn't been a rush to refactor things, so it seems like no one is interested.
