### ISSUE TITLE
Update VCF version header line to 4.2

### ISSUE THREAD

**Issue by vdauwera** [samtools/htsjdk#291]
Originally raised in http://gatkforums.broadinstitute.org/discussion/5893/gatk-3-4-46-producing-v4-2-vcfs and discussed in https://github.com/broadinstitute/gsa-unstable/issues/1084

In a nutshell: we are now emitting VCFs that have features introduced in the 4.2 version. We should update the version header line accordingly.

Relevant code is right at the top of VCFWriter.java

**Comment by nh13** [comment]
@vdauwera see #292

**Comment by droazen** [comment]
Resolved in https://github.com/samtools/htsjdk/pull/292
