### ISSUE TITLE
TestNG verbosity change hides test failures

### ISSUE THREAD

**Issue by droazen** [samtools/htsjdk#314]
In https://github.com/samtools/htsjdk/pull/306, `testng.verbosity` in `build.xml` was changed from 2 to 1 to prevent the logs from hitting the travis log file size limit. Unfortunately, now we can no longer see which tests are actually failing (with the corresponding stack trace) when there are test failures.

We may need to implement a custom TestNG listener to get the level of verbosity we want.

**Comment by yfarjoun** [comment]
I will not be able to get to this for at least 10 days. if you think this
is more urgent then that, let me know.

**Comment by droazen** [comment]
I've fixed this -- closing.
