### ISSUE TITLE
Usage of SAMRecord.validateCigar

### ISSUE THREAD

**Issue by dariober** [samtools/htsjdk#316]
Hello,
I'm surely missing something trivial here... I can't make `validateCigar` to actually capture errors in a `SAMRecord`. In the example below I create a `SAMRecord` with nonsensical cigar. Still, `validateCigar` returns null instead of a list of errors. This is on htsjdk-1.130 and Java 1.6.

Thanks!
Dario

```
package validateSAMRecord;

import htsjdk.samtools.SAMRecord;
import htsjdk.samtools.SAMValidationError;
import htsjdk.samtools.SamReader;
import htsjdk.samtools.SamReaderFactory;
import htsjdk.samtools.ValidationStringency;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;

public class ValidateSAMRecord {

	public static void main(String[] args) throws IOException {
		
		// Read dummy header
		SamReaderFactory sf = SamReaderFactory.
				makeDefault().
				validationStringency(ValidationStringency.STRICT);
		SamReader sam= sf.open(new File("/tmp/header.sam"));
		
		// Create nonsense record
		SAMRecord rec= new SAMRecord(sam.getFileHeader());
		rec.setCigarString("nonsense");

		// Validate record
		ArrayList<SAMValidationError> err= 
				(ArrayList<SAMValidationError>) rec.validateCigar(-1);
		
		System.out.println(err); // Returns null!!
		
		sam.close();
	}
}
```

**Comment by yfarjoun** [comment]
@dariober, sorry it took so long to get to your issue. I added a test in PR #405. As you can see there, the problem with your code is that the default validationStringency for a SamRecord is SILENT. So, before you validate you have to setValidationStringency to STRICT and then the validation will indeed fail.
