### ISSUE TITLE
uint32_t is a valid BAM type but blows up CRAM

### ISSUE THREAD

**Issue by mp15** [samtools/htsjdk#322]
```
ref1_grp2_p003  99  ref1    11  5   10M =   35  34  ACCCGGGGAT  &&&&&&&&&&  ia:i:4294967295 MD:Z:10 NM:i:0  RG:Z:grp2
```

This line from the standard Samtools test suite blows up HTSJDK and thus GATK. Given that Java 8 has explicit support for unsigned arithmetic on the Integer type it might be good to fix this. I am told it originates here:
https://github.com/samtools/htsjdk/blob/3d13016bef282595328d4eb6eed9c71d885a0347/src/java/htsjdk/samtools/cram/structure/ReadTag.java#L380

**Comment by mp15** [comment]
Specifically I suggest you use:
http://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html#parseUnsignedInt-java.lang.String
When you do migrate to 8 but in the mean time use a long?

**Comment by vadimzalunin** [comment]
see PR https://github.com/samtools/htsjdk/pull/339, blocked by travis failure irrelevent to the PR, issue https://github.com/samtools/htsjdk/issues/341

**Comment by droazen** [comment]
Fixed in https://github.com/samtools/htsjdk/pull/339 -- closing!
