### ISSUE TITLE
Remove deprecated methods in SequenceUtil

### ISSUE THREAD

**Issue by mattsooknah** [samtools/htsjdk#330]
SequenceUtil contains deprecated versions of the following methods:
- countMismatches
- sumQualitiesOfMismatches
- calculateSamNmTag

The main difference is that `referenceBases` is passed in as a `char[]` in the deprecated versions, rather than a `byte[]`. Due to the structure of the code, it is not easy to factor out the internal logic without a performance hit, so the code is mostly duplicated (and as a result, the deprecated implementations are out-of-date).

Apparently GATK used to pass in a char array, but has since been updated, so removing the deprecated versions will not affect GATK.

Would anyone else object to removing the deprecated methods?

**Comment by eitanbanks** [comment]
If they are deprecated AND not being supported (so are out-of-date) then my vote would be to remove.  It's much more dangerous to keep them around as people might still be using them.

**Comment by magicDGS** [comment]
I think that this is already fixed.

**Comment by yfarjoun** [comment]
fixed by #728
