### ISSUE TITLE
bug:  hasBlockCompressedExtension fails for URLs with parameters

### ISSUE THREAD

**Issue by jrobinso** [samtools/htsjdk#331]
The method "AbstractFeatureReader.hasBlockCompressedExtension" does not take into account url parameters and thus fails for resources such as the following because it doesn't end in ".gz"

https://www.googleapis.com/download/storage/v1/b/deflaux-public-test/o/NA12877.vcf.gz?alt=media

**Comment by jrobinso** [comment]
The following version of the method fixes the problem

    public static boolean hasBlockCompressedExtension(final String path) {

        final String fileName = (path.startsWith("http://") || path.startsWith("https://")) ?
                path.split("\\?", 2)[0] :
                path;

        for (final String extension : BLOCK_COMPRESSED_EXTENSIONS) {
            if (fileName.toLowerCase().endsWith(extension))
                return true;
        }
        return false;
    }

**Comment by cmnbroad** [comment]
I made a somewhat different fix than the one proposed above (I added an overload that accepts a URI) but let me know if for some reason thats not adequate.
