### ISSUE TITLE
CI failed: github unavailable

### ISSUE THREAD

**Issue by vadimzalunin** [samtools/htsjdk#337]
travis/push failed on the branch https://github.com/samtools/htsjdk/pull/336

fatal: unable to access 'https://github.com/samtools/htsjdk.git/': Couldn't resolve host 'github.com'

is this an intermittent issue?

**Comment by lbergelson** [comment]
It should be.  I've restarted the build manually.

**Comment by lbergelson** [comment]
Closing this since it seems to have gone beyond that point in the rebuild.
