### ISSUE TITLE
Unexpected failures in travis: not a regular file: /dev/null

### ISSUE THREAD

**Issue by vadimzalunin** [samtools/htsjdk#341]
See build errors in https://github.com/samtools/htsjdk/pull/339

Basically build seems to fail on things unrelated to the PR: 
Cannot create MD5 file for BAM because output file is not a regular file: /dev/null
Cannot create index for BAM because output file is not a regular file: /dev/null

**Comment by vadimzalunin** [comment]
https://github.com/samtools/htsjdk/pull/355 build fails as well

**Comment by droazen** [comment]
Closing as invalid -- as explained in a comment to https://github.com/samtools/htsjdk/pull/339, the test failure in that branch is very much related to the contents of the PR.
