### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by superbobry** [samtools/htsjdk#351]
I've tried cloning the repo and opening it as IDEA project, but it didn't work due to SBT errors.

 Can you please add "How to contribute" section to the `README.md` covering setting up the project, running tests, code style guidelines etc?

**Comment by lbergelson** [comment]
Hi @superbobry

The sbt script is only used for publishing htsjdk to maven.  Builds are handled through ant.  This is a confusing situation and we should clarify it.  

The following commands should help get you started:

`ant`
`ant test`
`ant single-test -Dname=AbstractFeatureReaderTest`
`ant clean`
and
`ant htsdjk-jar`

There's an intellij project file checked into the repo that you can use for an initial project set up.  I find that I need to manually add the `lib` folder as a module dependency after opening it, but others have reported that it works fine as is for them.    (likely intellij version differences)  Once set up correctly you should be able to compile and run individual tests in intellij.  Hopefully that can help you get started.

**Comment by superbobry** [comment]
Thank you very much for explaining. 

I think this is worth adding to `README.md` or project [Wiki](https://github.com/samtools/htsjdk/wiki).

**Comment by fathersson** [comment]
@lbergelson, it's not common practice to push specific IDE files into the repository. Some people using Eclipse, NetBeans and other IDEs. Even if people use Intellij Idea, their set up might be different from the one that's committed. 
What I see right now is inconvenient. As soon as I imported project into my Intellij Idea, some of the files under .idea/ are changed. But I am really not sure I may commit them. 
Is it possible to remove these files from the repo?

**Comment by lbergelson** [comment]
Hi @fathersson .  I agree with you completely.  It's extremely inconvinient for almost all users right now.  These will be removed in the near future as part of #383.

**Comment by magicDGS** [comment]
This can be close, no?
