### ISSUE TITLE
In maven central pom file lists compile time dependency on org.testng:testng:6.8.8

### ISSUE THREAD

**Issue by priimak** [samtools/htsjdk#360]
Looking at this file https://repo1.maven.org/maven2/com/github/samtools/htsjdk/1.140/htsjdk-1.140.pom you can see compile scope dependency on org.testng:testng:6.8.8

```xml
<dependency>
<groupId>org.testng</groupId>
<artifactId>testng</artifactId>
<version>6.8.8</version>
</dependency>
```

but as far as I can see there is no compile time dependency on testng. If so, could that be resolved in a next version of htsjdk?

**Comment by magicDGS** [comment]
This is fixed now, no?

**Comment by lbergelson** [comment]
This was fixed in the move to gradle.
