### ISSUE TITLE
Require all CRAM files to have a reference

### ISSUE THREAD

**Issue by cmnbroad** [samtools/htsjdk#362]
Currently its possible to create a CRAMFileReader that doesn't have an associated reference, which can result in several downstream problems (NPE, failure to locate contigs, etc). I have some changes to lock this down tighter but its unclear how strict we should be.

@vadimzalunin - is there *any* valid use case/operations for reading CRAM files without the accompanying reference, or are there cases where we need to allow this ?

**Comment by vadimzalunin** [comment]
I think this has been fixed in https://github.com/samtools/htsjdk/pull/339 but perhaps needs testing.

CRAM supports unmapped readds as well as embedded reference, and in both cases ref file is not required. 
Also there is a feature of downloading a sequence on demand from ENA ref service.

**Comment by cmnbroad** [comment]
@vadimzalunin - we still have several cases where we have bad failure modes if a reference isn't provided (including NPEs). Do you have any suggestions for how we can validate the referenceSource at creation time (ie., in CRAMFileReader, Writer and Iterator) that isn't overly constraining? Verifying that the referenceSource is backed by a file is too stringent (and breaks some tests that use fake or in memory sources), but the common case of using the SAMFileWriter and Reader factories on CRAM files can lead to problems if the reference isn't provided or is bad.

Currently, CRAMFileReader and Writer do no checking, and CRAMIterator checks for a null referenceSource, but thats ineffective since the default referenceSource is almost always used, but it points to the null DEFAULT_FASTA. So you get NPEs further on.

Some examples and stacks:

Create a CRAMFIleWriter with no reference:
			at htsjdk.samtools.cram.build.Sam2CramRecordFactory.addSubstitutionsAndMaskedBases(Sam2CramRecordFactory.java:295)
			at htsjdk.samtools.cram.build.Sam2CramRecordFactory.createVariations(Sam2CramRecordFactory.java:239)
			at htsjdk.samtools.cram.build.Sam2CramRecordFactory.checkedCreateVariations(Sam2CramRecordFactory.java:184)
			at htsjdk.samtools.cram.build.Sam2CramRecordFactory.createCramRecord(Sam2CramRecordFactory.java:139)
			at htsjdk.samtools.CRAMFileWriter.flushContainer(CRAMFileWriter.java:201)
			at htsjdk.samtools.CRAMFileWriter.writeAlignment(CRAMFileWriter.java:353)


Create a CRAMFIleWriter with a non-null but  not valid reference:

	htsjdk.samtools.util.RuntimeEOFException: java.lang.NullPointerException
				at htsjdk.samtools.CRAMIterator.hasNext(CRAMIterator.java:262)
				at htsjdk.samtools.SamReader$AssertingIterator.hasNext(SamReader.java:567)
				.
				.
			Caused by: java.lang.NullPointerException
				at htsjdk.samtools.CRAMIterator.nextContainer(CRAMIterator.java:166)
				at htsjdk.samtools.CRAMIterator.hasNext(CRAMIterator.java:255)

**Comment by droazen** [comment]
I think that we should require a reference for CRAM at construction time if both of the following are true: `Defaults.USE_CRAM_REF_DOWNLOAD` is `false`, **and** the CRAM has no embedded reference. Thoughts?

**Comment by cmnbroad** [comment]
Ideally that sounds right. And for the factory APIs (where the currency is reference files) I think that would work. However the CRAM apis themselves accept other forms of reference sources, and the htsjdk tests use these. Take a look at the code starting  [here](https://github.com/samtools/htsjdk/blob/f18740b15378e31af23e0f8765c63e0de31ace44/src/tests/java/htsjdk/samtools/CramFileWriterTest.java#L112). We'd need a test that allows those reference sources.

In just looking at this more, It might be that if we stopped creating these [default references](https://github.com/samtools/htsjdk/blob/bd92747fd3672635de96473fea6d4b38e8635c8e/src/java/htsjdk/samtools/SamReaderFactory.java#L265) which we do in a few places then at least we could check for null references in the CRAM code. These default reference sources are currently never not null but they result in NPEs downstream since there is nothing real backing them. I'd propose that.

**Comment by vadimzalunin** [comment]
@droazen @cmnbroad 
Reference is not required in two cases: 
1. unmapped reads
2. embedded reference

But they cannot be reliably determined at construction time. 

Also I don't see why null should propagate into CRAM code.If a ref is required but not found (for any reason) then an error should be raised. Would it help if there is a specific exception instead of NPE?

**Comment by droazen** [comment]
@vadimzalunin We can't allow NPEs to propagate to our users -- they just result in confused bug reports when most of the time the problem is just that the user needed to specify a reference. I'd rather err on the side of caution and just require a reference up-front for CRAM in most cases, as chasing down all the possible sources of NPEs in the code would be difficult. Can you not determine up-front whether there is an embedded reference in a CRAM file? Is this information not in the header?

**Comment by vadimzalunin** [comment]
@droazen 
> Can you not determine up-front whether there is an embedded reference in a CRAM file? Is this information not in the header?
This is per container, so file header won't help unfortunately. 

It looks like users need some way of telling what to do when a reference is required, for example default behavior could be: scan a fasta file(s) if given, then local cache, then ENA ref service and then fail/skip if not found. 

There is not much we can do about it other than make it user friendly. It seems that ReferenceSequenceNotFoundException should be thrown instead of NPE, and then higher level code would be able to present it better.

**Comment by cmnbroad** [comment]
@vadimzalunin - A couple of questions about embedded references: does the current htsjdk implementation support them ? Also, how do you create such a CRAM, and are there any test files with embedded references in the repo now ?

**Comment by vadimzalunin** [comment]
@cmnbroad 
Embedded refs are not supported by htsjdk yet. I haven't seen any files in the wild but scramble from io_lib can produce them.

**Comment by droazen** [comment]
@vadimzalunin If embedded references are not supported in htsjdk, then let's just require an external reference for crams at construction time for now (if reference auto-download is off). We can relax this restriction later if support for embedded references is added. Getting NPEs and other cryptic errors from the cram classes is a major usability issue for us currently, so I think an up-front reference requirement is the right solution for now.

**Comment by vadimzalunin** [comment]
@droazen making reference source required is fine but still we need to replace NPE with something meaningful. After all, sequences may be missing from the provided fasta file.

**Comment by cmnbroad** [comment]
Right, ideally we would do both, since in the end getReferenceBases can always fail even if a reference has been provided, and the NPE isn't great in that case. Are there any cases where the code can reliably recover from a null return from getReferenceBases ? If not we maybe it should just have it throw if its going to return null.

I'll do another PR and change the SAM* factory classes to throw unless they can create a ReferenceSource from an actual reference file (including from the env var) or the download service is enabled. Then I can add a null pointer check in CRAMFileWriter, CRAMFileReader and CRAMIterator. I think that will strike the right balance and allow the test cases that use fake/in-memory references to continue work.

One other independent suggestion is to turn the cram ReferenceSource class into an interface or abstract class, and have implementations for the various cases of local file, download service, etc., and then when we support embedded refs we can just add one that represents "assume fallback to the embedded ref" with appropriate recovery.

**Comment by vadimzalunin** [comment]
@cmnbroad 
> Are there any cases where the code can reliably recover from a null return from getReferenceBases ?

Don't think so. Some information like flag stats can still be obtained from a CRAM file but not SAM/BAM equivalent. 

> I'll do another PR and change the SAM* factory classes to throw unless they can create a ReferenceSource from an actual reference file (including from the env var) or the download service is enabled. Then I can add a null pointer check in CRAMFileWriter, CRAMFileReader and CRAMIterator. I think that will strike the right balance and allow the test cases that use fake/in-memory references to continue work.

I agree :+1: 

> One other independent suggestion is to turn the cram ReferenceSource class into an interface or abstract class, and have implementations for the various cases of local file, download service, etc., and then when we support embedded refs we can just add one that represents "assume fallback to the embedded ref" with appropriate recovery.

Absolutely! Sounds like this is up to me :)

**Comment by cmnbroad** [comment]
Closing via #400.
