### ISSUE TITLE
round-tripping a SAMRecord through CRAM changes getInferredInsertSize 

### ISSUE THREAD

**Issue by akiezun** [samtools/htsjdk#364]
Look at the first read in the sam file here.
If you write the file as CRAM (using the writer factory) and then read back again, the inferredInsertSize changes from 201 (in the sam file) to 202 

[print_reads.sorted.sam.txt](https://github.com/samtools/htsjdk/files/26529/print_reads.sorted.sam.txt)
[print_reads.fasta.txt](https://github.com/samtools/htsjdk/files/26530/print_reads.fasta.txt)

**Comment by droazen** [comment]
@vadimzalunin Can you please take a look at this cram bug?

**Comment by vadimzalunin** [comment]
@droazen @akiezun see https://github.com/samtools/htsjdk/pull/384

**Comment by droazen** [comment]
Fixed by https://github.com/samtools/htsjdk/pull/384 -- closing.
