### ISSUE TITLE
more VariantContext attribute getters

### ISSUE THREAD

**Issue by ldgauthier** [samtools/htsjdk#371]
@yfarjoun thinks it "would be nice to have utility functions getAttributeAs<*>List for \* in String,Integer,Long,Double...."

**Comment by yfarjoun** [comment]
and @ldgauthier  "agrees"

**Comment by d-cameron** [comment]
Are there any plans to optionally enforce header typing on VariantContext attributes? It'd be nice if we could assume that the type in the header actually round-trips and matches the type defined in the header for that field. Currently we have to do something along the lines of [this](https://github.com/PapenfussLab/gridss/blob/master/src/main/java/au/edu/wehi/idsv/AttributeConverter.java) to get usable attributes.

**Comment by yfarjoun** [comment]
@ldgauthier ask and ye shall recieve! thanks @magicDGS!!
