### ISSUE TITLE
Request: SamLocusIterator including indel and pair information

### ISSUE THREAD

**Issue by magicDGS** [samtools/htsjdk#387]
SamLocusIterator is a great class to provide "pileup" information, but it lacks insertion and deletions that could be useful for develop tools for indel calling at the same time as SNP calling. On the other hand, pair-end information in the iterator could be very useful to use linkage in the calling procedure.

If the problem for indel calling is solve somehow with a different class or the pair-end information could be retrieved in a different way, I apologize for opening the issue.

Thank you very much.

**Comment by yfarjoun** [comment]
pair-end information can be found by processing the data with either
MergeBamAlignment or FixMateInformation (Picard tools). This will place the
mate CIGAR string in each read in a MC: tag. I think this could provide
much of the information you require.

Regarding indels I need to look further into the issue, perhaps someone
else can respond.

**Comment by magicDGS** [comment]
I was thinking more on developing new tools (independent of Picard), but it could be a requirement to pre-process the BAM file to add the MC tag. Thank you very much for the suggestion.

**Comment by tfenne** [comment]
@yfarjoun I think including, in LocusInfo, the sets of reads that have insertions and/or deletions at that position would be relatively straightforward.  I think it would involve:
1. Either modifying `LocusInfo` to have separate collections of records for 'covered with base', 'deleted in record', and 'insertion in record' _or_ modifying `RecordAndOffset` to have a discriminator type.
2. Deciding at which locus insertions should be presented (base before or base after)
3. Modifying `SamLocusIterator.accumulateSamRecord()` to also process insertions/deletions and not just alignment blocks.

**Comment by magicDGS** [comment]
@tfenne That idea sounds great and it could help a lot. With respect to the second point, the base before is more reasonable for my point of view, as in the output from samtools mpileup. Thank you very much.

**Comment by yfarjoun** [comment]
This is a great request, but I'm not sure at all who will get around to
actually doing it..is there a downstream tool that would greatly benefit
from having this option?

**Comment by magicDGS** [comment]
@yfarjoun I'm developing now a tool that needs that information, so I could try to implement in the way suggested by @tfenne: adding to `LocusInfo` two lists (deletedInRecord and insertionInRecord) and methods to retrieve them and a modified accumulator (accumulateSamRecordWithIndels) for processing indels. Some minor changes will be include a boolean field for the indel option and setter/getter methods for it in a similar way as the filters or quality threshold.

Nevertheless, after looking into details the `SamLocusIterator.accumulateSamRecord()` I found that the method rely on the `SAMRecord.getAlignmentBlocks()` avoiding re-computation of the `AlignmentBlock`s. Do you think that re-computing the blocks for alignment and indels will affect the performance too much?

**Comment by yfarjoun** [comment]
getAlignmentBlocks avoids calculating deletions and insertions indeed, but
not for performance. You will break many things if you change that as the D
and I blocks are not considered "AlignmentBlocks". If you need something
akin to getAlignmentBlocks that will also return the D and I blocks, I'd
recommend you add an option paramter (leaving the default signature that
will keep the old behavior).



On Mon, Nov 16, 2015 at 10:02 AM, magicDGS <notifications@github.com> wrote:
>
> @yfarjoun I'm developing now a tool that needs that information, so I
could try to implement in the way suggested by @tfenne: adding to LocusInfo
two lists (deletedInRecord and insertionInRecord) and methods to retrieve
them and a modified accumulator (accumulateSamRecordWithIndels) for
processing indels. Some minor changes will be include a boolean field for
the indel option and setter/getter methods for it in a similar way as the
filters or quality threshold.
>
> Nevertheless, after looking into details the
SamLocusIterator.accumulateSamRecord() I found that the method rely on the
SAMRecord.getAlignmentBlocks() avoiding re-computation of the
AlignmentBlocks. Do you think that re-computing the blocks for alignment
and indels will affect the performance too much?

**Comment by magicDGS** [comment]
@yfarjoun I do not plan to change the `SAMRecord.getAlignmentBlocks()`, my question is about if it could affect the performance if I don't use that method because the `SAMRecord` keeps the list of `AlignmentBlock`s in a field to avoid re-computation of them.

Of course, my idea is leave the class behaving as currently, but allowing it to return indels as well.

**Comment by yfarjoun** [comment]
Yes, I imagine that it will affect performance, but don't worry about
premature optimization...leave that for a second round.

**Comment by magicDGS** [comment]
PR #408

**Comment by magicDGS** [comment]
Closed by #408
