### ISSUE TITLE
CRAMFileReader.query does not propagate validationStringency to created iterators

### ISSUE THREAD

**Issue by akiezun** [samtools/htsjdk#394]
`CRAMFileReader.query` creates a new `CRAMIterator` but does not propagate validationStringency so it's always STRICT and blows up even if the CRAMFileReader's stringency is SILENT

**Comment by akiezun** [comment]
@vadimzalunin can you have a look? I'm not a gatekeeper so i won't assign it to you but please grab it if is it a bug

**Comment by droazen** [comment]
Assigning to @vadimzalunin -- please look at this when you have a chance, as it's a blocker for some downstream development.

**Comment by cmnbroad** [comment]
Closed via https://github.com/samtools/htsjdk/pull/399.
