### ISSUE TITLE
CRAMIterator fails on queryname sorted input with unmapped reads

### ISSUE THREAD

**Issue by cmnbroad** [samtools/htsjdk#404]
CRAMWriter can generate a CRAM file with queryname sorted reads, but when reading the file get an exception when iterating on the first record that is unmappped : 

htsjdk.samtools.util.RuntimeEOFException: java.lang.RuntimeException: Slice mapped outside of the reference.

	at htsjdk.samtools.CRAMIterator.hasNext(CRAMIterator.java:264)
	at htsjdk.samtools.SamReader$AssertingIterator.hasNext(SamReader.java:568)
	at org.broadinstitute.hellbender.tools.picard.sam.SortSam.doWork(SortSam.java:50)

**Comment by cmnbroad** [comment]
@vadimzalunin Can you take a look ?

**Comment by cmnbroad** [comment]
The stack for the original exception is:

Caused by: java.lang.RuntimeException: Slice mapped outside of the reference.
	at htsjdk.samtools.cram.structure.Slice.alignmentBordersSanityCheck(Slice.java:74)
	at htsjdk.samtools.cram.structure.Slice.validateRefMD5(Slice.java:84)
	at htsjdk.samtools.CRAMIterator.nextContainer(CRAMIterator.java:179)
	at htsjdk.samtools.CRAMIterator.hasNext(CRAMIterator.java:257)

**Comment by vadimzalunin** [comment]
@cmnbroad 
I can't reproduce this, htsjdk seems to read the file just fine: 
https://github.com/broadinstitute/gatk/blob/1ecb871ce375799f9245bf932ed5da40f045d7ec/src%2Ftest%2Fresources%2Forg%2Fbroadinstitute%2Fhellbender%2Ftools%2Fcount_reads.cram

Also tried enforcing unmapped flags on some random reads - no exception. 

Am I missing some test condition?

**Comment by cmnbroad** [comment]
Interesting. I should be able to get you a reproducible test case.

**Comment by cmnbroad** [comment]
I pushed a [commit](https://github.com/cmnbroad/htsjdk/commit/62c37af07b1d1322533197e81e0ad67df2a191a1) to a [branch](https://github.com/cmnbroad/htsjdk/commits/cn_cram_sort) on my [fork](https://github.com/cmnbroad/htsjdk) with a test case that repros this. The test code is in SAMFileReaderTest.java.

I think its a little more subtle than I first stated - you're right that we can read the original file, but if you write it out to another CRAM file in queryname sorted order through htsjdk and then try to read the resulting file, you get the exception. IIRC, I did try reading the intermediate file with samtools CLI and was able to view it ok, but I can't iterate through it with htsjdk.

**Comment by vadimzalunin** [comment]
@cmnbroad found it, thanks! Just some muddy logic around detection of slice sequence id. Working on PR...

**Comment by cmnbroad** [comment]
@vadimzalunin Any update on this ? BTW, is it the intention that queryname sorted records are supported by the CRAM spec ? CRAM seems to be optimized for coordinate sorting and the spec seems to require that, but the implementation seems to handle it with the exception of this issue.

**Comment by vadimzalunin** [comment]
@cmnbroad almost there, it somehow interleaved with https://github.com/samtools/htsjdk/pull/355, hence the delay. 
CRAM is able to handle unsorted data as well, it's just that focus has been on coordinate sorted.

**Comment by vadimzalunin** [comment]
@cmnbroad please review https://github.com/samtools/htsjdk/pull/432

**Comment by cmnbroad** [comment]
Closed via https://github.com/samtools/htsjdk/pull/432.
