### ISSUE TITLE
Extract annotation info

### ISSUE THREAD

**Issue by dianalemos** [samtools/htsjdk#429]
I don't know if here is the best place to put this if it's not please tell me where it is. 
I have a vcf file with variant annotations and now I want to extract that information. I never used this library before so I don't now much about all the methods. Right now the only information that I can see is what is present in the header. Can someone tell me how to access the data lines after that?

**Comment by lindenb** [comment]
I wrote something like this some times ago: https://github.com/lindenb/jvarkit/blob/master/src/main/java/com/github/lindenb/jvarkit/util/vcf/predictions/VepPredictionParser.java

(I wish this could be included in htsjdk)

**Comment by yfarjoun** [comment]
Is there a small set of standards for annotation information? My concern
would be that with VEP, SNPEff and other annotators, there would be too
many formats. If there is a standard (should it be defined in HTS-specs?)
then I think it could be fine to add a parser for it here, but otherwise I
worry that htsjdk would be burdened with keeping up with too many formats.

what do others think?

**Comment by lindenb** [comment]
> Is there a small set of standards for annotation information

the only one I know is  http://snpeff.sourceforge.net/VCFannotationformat_v1.0.pdf 

I saw people talking about a plugin system for htsjdk. May be we could write a SPI , something like:

```java
interface PredictionParser {
  public List<Prediction> getPredictions(VariantContext ctx);
  public String getType();//VEP...
}

interface Prediction  {
  public VariantContext getVariantContext();
  public Set<String> getSequenceOntologyTerms();
  public String getGene();
  (...)
  public Map<String,String> getAll();//all key/value
  }
```

**Comment by vdauwera** [comment]
For a generic way to do this that is pre-baked and easy to use by end-users, see GATK VariantsToTable.

**Comment by yfarjoun** [comment]
Geraldine's note made me realize that I was thinking about annotations
a-la-VEP, but perhaps the OP intended annotations as geraldine meant, i.e.
the INFO field values...perhaps the OP could clarify what is sought....

**Comment by vdauwera** [comment]
I think the OP probably meant functional annotations, but either way VTT
can retrieve any key-value pair that is either in INFO or FORMAT. If the
functional annotation is further structured (like snpeff output tends to
be) then there is a bit more unpacking to be done, but such unpacking isn't
really something we'd want in htsjdk anyway. There I can see plugins coming
in handy.

But anyway I got the impression that the OP was looking for an end-use
solution to do essentially what VTT does out of the box.

**Comment by dianalemos** [comment]
Thank you for all the help. 
Yes, what I want is to extract the annotations that are in the INFO field with the htsjdk library. I only want to extract that column but I don't know which method (in the library) or class access that information. 
I'm interested in htsjdk because I'm writing my code in Java, but I could use GATK all the same just to extract the column that I want.

**Comment by yfarjoun** [comment]
in htsjdk you can use getAttributeAsString (from VariantContext)

from the commandline you can use VTT as mentioned above.

if this answers your question, please close the issue.



On Sun, Jan 10, 2016 at 9:48 AM, Diana Lemos <notifications@github.com>
wrote:
>
> Thank you for all the help.
> Yes, what I want is to extract the annotations that are in the INFO field
with the htsjdk library. I only want to extract that column but I don't
know which method (in the library) or class access that information.
> I'm interested in htsjdk because I'm writing my code in Java, but I could
use GATK all the same just to extract the column that I want.
