### ISSUE TITLE
IndexFactory.writeIndex is incorrect for tabix indexes, missing BlockCompressedOutputStream

### ISSUE THREAD

**Issue by akiezun** [samtools/htsjdk#430]
IndexFactory.writeIndex is incorrect for tabix indexes (does not use BlockCompressedOutputStream) and thus loading the index will blow up (reading does use BlockCompressedInoutStream).

Courtesy of @droazen, we know that compressing the index is indeed the right thing:
"the tbi index itself is supposed to be block compressed. Cf., eg., the code for writing tbi indices in htslib (https://github.com/samtools/htslib/blob/1e2ed48935a58845cecb64880e8cf7553c7db852/hts.c):

    } else if (fmt == HTS_FMT_TBI) {
        BGZF *fp = bgzf_open(fnidx, "w");
        if (fp == NULL) return -1;
        bgzf_write(fp, "TBI\1", 4);
        hts_idx_save_core(idx, fp, HTS_FMT_TBI);
        bgzf_close(fp);
"

gatk has a workaround: https://github.com/broadinstitute/gatk/pull/1422

**Comment by magicDGS** [comment]
I think that this could be close, couldn't it?
