### ISSUE TITLE
GenotypeLikelihoods should handle anyploid, not just diploid 

### ISSUE THREAD

**Issue by ronlevine** [samtools/htsjdk#437]
`GenotypeLikelihoodsAllelePair GenotypeLikelihoods.getAllelePair(final int PLindex)` returns the cached alleles corresponding to the PLindex. This cache is diploid because the method that initializes it, `GenotypeLikelihoodsAllelePair[] GenotypeLikelihoods.calculatePLcache(final int altAlleles)`,  uses a diploid number of likelihoods ( `numLikelihoods(1 + altAlleles, 2)`) and adds an allele pair each PLindex, instead of the ploidy number of allele indices. If the methods are generalized, they should return
`ArrayList<Integer> ` instead of `GenotypeLikelihoodsAllelePair`.

**Comment by yfarjoun** [comment]
hmmm. I think that the optimization of using a GenotypeLikelihoodsAllelePair overweighs the generalizability of multipliody. 

is there a usecase for this?

**Comment by yfarjoun** [comment]
is it needed for select variants? perhaps a non-diploid method could be **added** rather than changing the signature of this function.

**Comment by ronlevine** [comment]
Here's the usecase: https://github.com/broadinstitute/gatk/issues/1382
The plan is to keep the diploid optimization.

**Comment by ronlevine** [comment]
@yfarjoun Could you review the accompanying pull request? It should be ready momentarily.

**Comment by yfarjoun** [comment]
It will not be this week, as I"m out conferencing in agbt. but if it can
wait for next week then sure.

Y.

**Comment by ronlevine** [comment]
@yfarjoun Thanks. I'll look at your comments next week while I'm in Miami.

**Comment by ronlevine** [comment]
I think this should be closed.
