### ISSUE TITLE
FastqRecord not implements Serializable

### ISSUE THREAD

**Issue by jayinhuang** [samtools/htsjdk#445]
We are tring to serailize FastqRecord, but the FastqRecord (htsjdk/src/java/htsjdk/samtools/fastq/FastqRecord.java) cannot be serializable. Can this be fixed?

**Comment by lindenb** [comment]
I've sent a pull request for this: https://github.com/samtools/htsjdk/pull/446

**Comment by akiezun** [comment]
I guess this can be closed now, right?

**Comment by magicDGS** [comment]
Could this be closed?
