### ISSUE TITLE
Support CSI as well as BAI indexes

### ISSUE THREAD

**Issue by peterjc** [samtools/htsjdk#447]
The original BAM index format (BAI) has a fixed bin size system, and suffers from a maximum reference sequence length of 512Mbp making it unsuitable for large chromosomes (e.g. many plants, some marsupials). The newer CSI indexing format supports longer references, and also different bin sizes - which ought to help with ultra-high coverage in RNA sequencing or viral samples.

On the C side, htslib and samtools now support both BAI and CSI indexes.

Currently htsjdk only appears to support BAI indexes.

The CSI specification lives at https://github.com/samtools/hts-specs/blob/master/CSIv1.tex and http://samtools.github.io/hts-specs/CSIv1.pdf and http://samtools.github.io/hts-specs/CSIv2.pdf

**Comment by jmarshall** [comment]
Ignore _CSIv2.pdf_ for the time being.  It is a draft from an experimental branch, and CSI v2 may well be different from what that document describes when it finally lands.

**Comment by nathanhaigh** [comment]
Any progress on this? It would be good to be able to load large (~1Gbp) plant pseudomolecules into IGV using CSI indexes.

**Comment by nathanhaigh** [comment]
What is required to add CSI support? I may be able to get a colleague to work on this but will need some pointers as to where to start etc.

**Comment by jrobinso** [comment]
Hey all any updates?   I might work on this myself but would like to know the status, if any, first.   As this is still open I assume that CSI is not yet supported.

**Comment by nathanhaigh** [comment]
Not as far as I'm aware. I'm trying to get CSI support in other tools like Sambamba: https://github.com/lomereiter/sambamba/issues/284

**Comment by nathanhaigh** [comment]
Have you begun working on this yet @jrobinso ?

**Comment by jrobinso** [comment]
@nathanhaigh Not yet.   IGV is taking all my time, very little left to contribute to htsjdk.

**Comment by homonecloco** [comment]
Are there any updates on this?

**Comment by lbergelson** [comment]
Htsjdk now supports reading CSI indexes as of 2.19.0
