### ISSUE TITLE
Cram to Bam Conversion Lost MD:Z Tag

### ISSUE THREAD

**Issue by vcaropr1** [samtools/htsjdk#455]
I attempted to use GATK 3.5 to convert a cram file back to a bam file to see if this format is truly lossless.  In doing so, I noticed the MD:Z tag for each record is lost.  I contacted GATK via their forums about the issue and they have determined that this appears to be at the htsjdk library level.  

Here is the link for additional information from the GATK forum (http://gatkforums.broadinstitute.org/gatk/discussion/6772/cram-to-bam-conversion-lost-md-z-tag-gatk-3-5#latest)

**Comment by droazen** [comment]
@vadimzalunin @cmnbroad Could one of you look into this?

**Comment by cmnbroad** [comment]
We should get the official word from @vadimzalunin, but it does look like htsjdk BAM->CRAM conversion deliberately drops the MD and NM tags (probably because they're derived from the original read bases which are not stored by CRAM, and can be regenerated during decompression), but does not regenerate them on CRAM->BAM conversion.

**Comment by cmnbroad** [comment]
Once we get the confirmation or explanation from Vadim, we should update the GATK forum thread.

**Comment by cmnbroad** [comment]
It looks like the NM tag *is* regenerated by default when going from CRAM to back to BAM, and only the MD tag is not. @vadimzalunin is there any reason we can't change the default (lossless) behavior in htsjdk to preserve all tags ?

**Comment by vadimzalunin** [comment]
Legacy reasons I think, in cramtools NM/MD tags by default are not re-generated. 
I'm fine with NM/MD tags generated by default. However this should be reflected somewhere in the documentation -- people may start asking the opposite question :)

**Comment by vadimzalunin** [comment]
@cmnbroad  should've read your comment more carefully. 
NM/MD tags are treated specially to achieve better compression on lossy modes, which was one of the goals in cramtools. For lossless it doesn't matter as much, so I guess we can remove NM/MD bypass and treat them as normal tags. 
PS sorry for slow responses, I've been away for couple of weeks, back in the office next week.

**Comment by vcaropr1** [comment]
No worries, and thanks for the explanation!  We are exploring the options for using the cram format over bam for archieving purposes (and eventually a full transition) and just want to make sure the conversions are truly lossless.  

Thanks again @vadimzalunin !
-Vito C.

**Comment by cmnbroad** [comment]
We should think about whether the right thing to do for these tags is to just preserve them when they exist (rather than regenerating them, since we don't have a way to remember whether they existed or not), and only use regeneration on request when a lossy mode has been used.

**Comment by droazen** [comment]
@vadimzalunin This is becoming a more urgent issue for us, as it prevents us from being able to round-trip bam -> cram -> bam in htsjdk with no differences. I vote that in lossless mode, NM and MD should just be treated as normal tags to facilitate this goal. @eitanbanks @ktibbett do you agree?

**Comment by ktibbett** [comment]
@droazen , what does "treated as normal tags" mean?

**Comment by droazen** [comment]
@ktibbett It means: if they are already present, they are preserved (not stripped out) during conversion, and if they are not already present, they are not added automatically.

**Comment by yfarjoun** [comment]
I agree. lossless is clear: preserve the information as given.

**Comment by ktibbett** [comment]
Yep, sounds good.

**Comment by cmnbroad** [comment]
Closed via https://github.com/samtools/htsjdk/pull/487
