### ISSUE TITLE
Disable failing SRA tests until they can be made more robust

### ISSUE THREAD

**Issue by lbergelson** [samtools/htsjdk#459]
We're seeing intermittent SRA test failures despite #434.  This is causing headaches for production.  

We're seeing `IllegalArgumentException` "Invalid SRA accession was passed to SRA reader" in many tests.  Before running the tests we checked that `SRAAccession.isSupported()` The accession number usually passes, so I think it must be failing `NGS.isValid(acc)` (or `SRAAccession.isSupported() has changed between invocations... is that possible?`) 

Following the trail leads down to an undocumented native method call to  ` private native static boolean IsValid ( String spec );`  so it's hard to tell why things are failing.

These errors were transient and we've been unable to reproduce them.

We should place all the SRA tests into their own test group, and not run that as part of the standard tests until the tests are more robust and #442 is fixed.

**Comment by cmnbroad** [comment]
Can this be closed (fixed in https://github.com/samtools/htsjdk/pull/638 ?)

**Comment by magicDGS** [comment]
I think that this is already fix, no?

**Comment by lbergelson** [comment]
Marking this as done.
