### ISSUE TITLE
Improve error messages when instantiating an SRAFileReader

### ISSUE THREAD

**Issue by lbergelson** [samtools/htsjdk#460]
Currently constructing a new `SRAFileReader` calls `SRAAccession.isValid()` and throws an exception saying `Invalid SRA accession was passed to SRA reader` if `isValid` returns false.

Since is valid can fail for a number of reasons, this is not a very helpful message.  It's particularly not helpful because it could actually be a valid accession, but SRA is just not supported.

This should be improved so that someone instantiating an SRAReader can tell WHY it was considered invalid.

**Comment by lbergelson** [comment]
@a-nikitiuk @kwrodarmer  Can you take this one please.

**Comment by kwrodarmer** [comment]
Yes, we have already been working on a new reporting framework for this, as you have suggested, based upon various exception types.

**Comment by cmnbroad** [comment]
Can this be closed (fixed in https://github.com/samtools/htsjdk/pull/638 ?)

**Comment by a-nikitiuk** [comment]
Yes, it should be

**Comment by cmnbroad** [comment]
Closed via https://github.com/samtools/htsjdk/pull/638.
