### ISSUE TITLE
Fix inexplicable SRA test failures

### ISSUE THREAD

**Issue by lbergelson** [samtools/htsjdk#461]
We've seen a case of  `Invalid SRA accession was passed to SRA reader` in many tests. Before running the tests we checked that `SRAAccession.isSupported()`  The accession number usually passes, so I think it must be failing `NGS.isValid(acc)` (or `SRAAccession.isSupported()` has changed between invocations... is that possible?)

Following the trail leads down to an undocumented native method call  `private native static boolean IsValid ( String spec );` so it's hard to tell why things are failing.

These errors were transient and we've been unable to reproduce them, but they've caused a major headache for production so it's necessary that we prevent this from happening again.  See #459 for the temporary solution.

**Comment by lbergelson** [comment]
@a-nikitiuk @kwrodarmer  Here's a fun one for you.  Sorry I don't have more to go on.  There's a stack trace, but at the moment it's lost due to atlassian failures.  I'll update when that comes back online.

**Comment by kwrodarmer** [comment]
It would be helpful enough to at least give us a reproducible command line, or accession in question. These things have a lot to do with behaviors. We need to know, for example, if an accession leads to something already downloaded and in a user's cache area, or whether it is only accessible with dbGaP authorization, or whether the original submitter has for whatever reason withdrawn its publication.

**Comment by lbergelson** [comment]
Here's the testng output from one of them.  22 SRA tests failed with similar stack traces.  We're unable to reproduce the failure and subsequent attempts in the same environment passed.  

It's a bit worrisome that something like the contents of the users cache could affect test results.  Is there a way to isolate the tests from the rest of the system?
 
```
testLevelSize [testng] java.lang.IllegalArgumentException: Invalid SRA accession was passed to SRA reader: SRR1298981 [testng] at htsjdk.samtools.SRAFileReader.(SRAFileReader.java:64) [testng] at htsjdk.samtools.sra.SRAIndexTest.getIndex(SRAIndexTest.java:147) [testng] at htsjdk.samtools.sra.SRAIndexTest.testLevelSize(SRAIndexTest.java:59) [testng] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [testng] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [testng] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [testng] at java.lang.reflect.Method.invoke(Method.java:483) [testng] at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86) [testng] at org.testng.internal.Invoker.invokeMethod(Invoker.java:643) [testng] at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820) [testng] at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128) [testng] at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng] at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng] at org.testng.TestRunner.privateRun(TestRunner.java:782) [testng] at org.testng.TestRunner.run(TestRunner.java:632) [testng] at org.testng.SuiteRunner.runTest(SuiteRunner.java:366) [testng] at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361) [testng] at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319) [testng] at org.testng.SuiteRunner.run(SuiteRunner.java:268) [testng] at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng] at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng] at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244) [testng] at org.testng.TestNG.runSuitesLocally(TestNG.java:1169) [testng] at org.testng.TestNG.run(TestNG.java:1064) [testng] at org.testng.TestNG.privateMain(TestNG.java:1385) [testng] at org.testng.TestNG.main(TestNG.java:1354) [testng]
```

**Comment by kwrodarmer** [comment]
Did you **just** run into this error? The accession * SRR1298981* is public and perfectly accessible, but not small. I am able to access it without issue from outside of NCBI.

The contents of users' caches do not affect tests, only their diagnosis. It's possible to disable caching entirely during tests, but this obviously means that all data have to be retrieved over the network every time the test is run.

Speaking of running over the network, there are some cases of proxy usage that cause errors not observed with direct HTTP access. We are just about to release some compensating code within `ncbi-vdb`, but only users who have automatic library download enabled will get this update.

So where does this accession live, in your tests? It can be local, in which case it probably has a `.sra` extension. It can be local but in a user cache, in which case you will find it wherever they've established a cache *(by default in $HOME/ncbi in lieu of any user involvement)*, it can be partially in cache *(identified with a `.cache` extension)* or can be entirely remote. Whenever remote access is involved, we have to look at the HTTP connection and whether a proxy is involved.

**Comment by lbergelson** [comment]
Our production team ran into this error last night.  SRR1298981 is the accession that was given to us as a good accession to use for tests.  If it's large, is there a trivially small accession we could use for tests instead?   Can we commit a cached version to our test files so we can exercise the code without going over the internet?  

I don't believe we have any local version of this accession and it's likely accessed over the internet.  This isn't ideal for tests because it puts us at the mercy of internet connectivity.  A cached file that exercises the same code paths would be ideal.

**Comment by kwrodarmer** [comment]
Okay, fair enough. The accession you mention is 40G compressed, but that wouldn't account for the report. I've asked @a-nikitiuk to look at this more closely and give me details of what is happening. We'll report back asap.

In the meantime, there are quite small accessions that exercise everything, but I think we need to look at the tests and group them by whether network access is available or not. In the case of running offline, we can use a trivially small object that will exercise a lot (but not all) of the standard mechanism, which is enough to show that the HTSJDK integration works. It will not be enough to show that users can start throwing arbitrary accession numbers at GATK that are guaranteed to work.

We'll report back today with findings.

**Comment by lbergelson** [comment]
Annotating which tests require network access would be great.  Minimizing network access for the tests would be ideal.  We definitely don't want to be downloading 40G for any reason during a test.  Thanks for the help.

**Comment by lbergelson** [comment]
Here's the full set of test failures.  
[FailedAndSkippedSRATests.txt](https://github.com/samtools/htsjdk/files/118099/FailedAndSkippedSRATests.txt)

**Comment by cmnbroad** [comment]
Can this be closed (fixed in https://github.com/samtools/htsjdk/pull/638 ?)

**Comment by a-nikitiuk** [comment]
Yes

**Comment by cmnbroad** [comment]
Closed via https://github.com/samtools/htsjdk/pull/638.
