### ISSUE TITLE
CRAM writers produce v2.1 CRAM instead of v3.0 by default

### ISSUE THREAD

**Issue by cmnbroad** [samtools/htsjdk#467]
@vadimzalunin Is there any reason we're not creating v3.0 by default ?

**Comment by vadimzalunin** [comment]
@cmnbroad not really but let me double check...

**Comment by vadimzalunin** [comment]
https://github.com/samtools/htsjdk/pull/478

**Comment by cmnbroad** [comment]
Closed via https://github.com/samtools/htsjdk/pull/478.
