### ISSUE TITLE
CRAM files do not support zero for start/end coordinates when doing interval queries

### ISSUE THREAD

**Issue by bhandsaker** [samtools/htsjdk#481]
I believe there is a bug in CRAM support where it is not handling zero correctly for the start/end coordinates for query(), queryContained() and queryOverlapping().  The API specifies that zero should treated as either beginning of sequence (for start coordinate) or end of sequence (for end coordinate). In particular, using query(chr,0,0) should return the whole chromosome, but currently returns no records.

**Comment by droazen** [comment]
@vadimzalunin, could you take this one?

**Comment by cmnbroad** [comment]
@vadimzalunin I'm taking this one since I'm fixing some other bugs with indexing. Let me know if you've started on this already.

**Comment by cmnbroad** [comment]
Closed via #552.
