### ISSUE TITLE
CRAM: EOF container is not read through

### ISSUE THREAD

**Issue by vadimzalunin** [samtools/htsjdk#485]
htsjdk.samtools.cram.structure.ContainerIO#readContainer(int, java.io.InputStream, int, int)

For EOF containers the method reads only container header, leaving the remaining container bytes in the stream. While this does not cause any problems normally it may affect some higher-level activities like reading multi-cram streams.

**Comment by cmnbroad** [comment]
This was fixed long ago in #1440.
