### ISSUE TITLE
VCFFileReader query doesn't work for all regions

### ISSUE THREAD

**Issue by dianalemos** [samtools/htsjdk#496]
When I use this method for small regions in a file with millions of lines, it doesn't query that region. 
Example: CloseableIterator<VariantContext> vc = fileR.query("10", 122751783, 122779589);

**Comment by lbergelson** [comment]
Hi @dianalemos thanks for this report.  

If you make a smaller file with just the region around your query does it correctly query from that?  

When you say "doesn't query that region" what do you mean exactly, does it return an empty iterator, throw an exception, return features from somewhere else?

**Comment by dianalemos** [comment]
"doesn't query that region" the algorithm run without any error but doesn't return anything. 
For example: `CloseableIterator<VariantContext> vc = file.query("10", 49315876, 49326817)` I have this region in the file but when I run the code it doesn't recognize the region. The CloseableIterator is empty.
But if I start in a position closer to the beginning of the chromosome with the same end position as before, example: `CloseableIterator<VariantContext> vc = file.query("10", 125391, 49326817)` the algorithm returns the CloseableIterator with the region that I asked for. 
I did a smaller file but I used the beginning of chromosome 10 and that region doesn't seem to be the problem. I'm going to try another region.

**Comment by droazen** [comment]
@dianalemos Is your file indexed? If it is, can you try deleting and re-creating the index file?

**Comment by dianalemos** [comment]
I used tabix to generate the indexed file and then I read my file with `VCFFileReader file= new VCFFileReader(new File("file.vcf"), new File("fi.vcf.gz.tbi"), true); `

I tried to create different files but all of them work the same.

**Comment by droazen** [comment]
@dianalemos Your filenames (`file.vcf` and `fi.vcf.gz.tbi`) suggest that tabix was used to index a gzipped vcf called `fi.vcf.gz`, but then you attempted to use that index with a *non-gzipped* vcf called `file.vcf`. Could this be the problem?

**Comment by dianalemos** [comment]
That was the problem. I was totally destracted. Thank you.
