### ISSUE TITLE
runtime dependency on ant unnecessary(?) and ExternalCompression#bzip2 broken

### ISSUE THREAD

**Issue by bpow** [samtools/htsjdk#540]
### Subject of the issue
Described (and addressed) in PR #533. I don't know if adding an issue is needed as well for tracking or visibility.

htsjdk.samtools.cram.io.ExternalCompression does not have any tests, but I noticed that ExternalCompression#bzip2 uses BZip2CompressorInputStream, which per the commons compress documentation, is "An input stream that decompressed from the BZip2 format..." So, that's backwards.

I had noticed this because the runtime dependency on ant (used only for CBZip2InputStream, as far as I can tell) had worked its way back into the code base, despite there already being a smaller dependency (Commons Compress) that provides this functionality.

### Your environment
* version of htsjdk: 2.1.1
* version of java: 1.8.0_74
* which OS: Linux 4.2.0 (Ubuntu 15.10)

### Steps to reproduce

To demonstrate that round-trip of bzip2/unbzip2 does not work, here's a groovy script:

```groovy
@Grab(group='com.github.samtools', module='htsjdk', version='2.1.1')
import htsjdk.samtools.cram.io.ExternalCompression

message = "Time to test compression!"

if (message.equals(new String(ExternalCompression.gunzip(ExternalCompression.gzip(message.getBytes()))))) {
    print "Gzip worked!"
} else {
    print "Gzip is broken!"
}

if (message.equals(new String(ExternalCompression.unbzip2(ExternalCompression.bzip2(message.getBytes()))))) {
    print "BZip2 worked!"
} else {
    print "BZip2 is broken!"
}
```

This should print "Gzip worked!", then "BZip2 worked!", but instead throws an IOException of "Stream is not in the BZip2 format" since ExternalCompression#bzip2 is actually trying to uncompress.

### Expected behaviour

`ExternalCompression#bzip2` should compress.

### Actual behaviour

`ExternalCompression#bzip2` tries to uncompress.

**Comment by cmnbroad** [comment]
Closed via https://github.com/samtools/htsjdk/pull/533.
