### ISSUE TITLE
Change AD Number in VCF Header

### ISSUE THREAD

**Issue by davidbenjamin** [samtools/htsjdk#544]
See issue #1286 in broadinstitute/gsa-unstable.  VCF headers have

`##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">`

when they should have

`##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">`.

The former denotes an unlimited values for the AD field, the latter (correctly) denotes that there are as many AD values as there are alleles.

The necessary change is at line 186 of `htsjdk.variant.vcf.VCFStandardHeaderLines.java`, where `VCFHeaderLineCount.UNBOUNDED` should become `VCFHeaderLineCount.R`.

**Comment by davidbenjamin** [comment]
Made the change; the build is failing with `Invalid SRA accession was passed to SRA reader`  @lbergelson or @droazen any clue what that means?

**Comment by nh13** [comment]
@davidbenjamin I am seeing the same thing in my PR.  Logged an issue: https://github.com/samtools/htsjdk/issues/545

Sigh.

**Comment by davidbenjamin** [comment]
Thanks for letting me know @nh13!

**Comment by magicDGS** [comment]
This could be close, couldn't it?

**Comment by davidbenjamin** [comment]
Yes, closed by PR #546.
