### ISSUE TITLE
SRA tests fail with missing accession

### ISSUE THREAD

**Issue by nh13** [samtools/htsjdk#545]
### Description
See the travis build log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/119821702/log.txt

```
   [testng] FAILED: ("SRR1063272", 0, 99, "SRR1063272.R.1", "ACTCGACATTCTGCCTTCGACCTATCTTTCTCCTCTCCCAGTCATCGCCCAGTAGAATTACCAGGCAATGAACCAGGGCCTTCCATCCCAACGGCACAGCA", "@@CDDBDFFBFHFIEEFGIGGHIEHIGIGGFGEGAFDHIIIIIGGGDFHII;=BF@FEHGIEEH?AHHFHFFFFDC5'5=?CC?ADCD@AC??9BDDCDB<", 86, "101M", "supercont2.1", 60, true, false)
   [testng] java.lang.IllegalArgumentException: Invalid SRA accession was passed to SRA reader: SRR1063272
```

This blocks https://github.com/samtools/htsjdk/pull/516 and likely any other PR that encounters these issues

### Desired Actions
I would like to know why the test failed and  what are the plans to ensure that the test does not fail in the future.   This may not be a new issue, see https://github.com/samtools/htsjdk/issues/461, so I am looking for a detailed response and robust solution if this is a re-occurrence.

@a-nikitiuk could you take a look or route to the appropriate person?  

Thank-you in advance to anyone who has the chance to take a look.

**Comment by a-nikitiuk** [comment]
NCBI had network connectivity issues today that resulted in bad database connections. Some of the issues have been cleared up already, but we continue to work on the problem. It has nothing to do with the NGS code and it is simply a network problem which resulted in a failure to resolve SRA accession that you saw in the tests

**Comment by nh13** [comment]
@a-nikitiuk that makes a lot more sense.  Is there somewhere we could check the status of SRA network connectivity in case this happens again?  A status page (ex https://status.github.com/) would be great to see the current and past uptime.

The error message should be improved.  The message states that an invalid accession was given but really it was a problem querying SRA due to network issues.  Perhaps something like "network connection timeout".  @a-nikitiuk would you be able to update the error message?  I can imagine a user who doesn't have their internet connected would be confused by such a message for example, in addition to when there is network connection problems at SRA.   What do you think about modifying the error message?

**Comment by eitanbanks** [comment]
I agree that a better error message would be infinitely more helpful here.

**Comment by a-nikitiuk** [comment]
As for status page, you can look at https://www.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=announcement for any announcements in the future.

As for changing the error message, the current version of NGS API does not distinguish between network failure and a case when a provided accession does not exists. API only says, that it cannot resolve such accession to an SRA object, so we cannot change that message right now. However, we understand importance of a good error reporting and currently working on improvements in that area.

**Comment by tfenne** [comment]
@a-nikitiuk At least the error message should be changed to be not misleading, even if it is not currently possible to differentiate between the two.  I.e. it could read `could not resolve SRA accession; possible causes are an invalid SRA accession or that the SRA is currently unavailable.  See  https://www.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=announcement for SRA status`.

**Comment by yfarjoun** [comment]
:+1: for informative error messages.

**Comment by cmnbroad** [comment]
Can this be closed (fixed in https://github.com/samtools/htsjdk/pull/638 ?)

**Comment by a-nikitiuk** [comment]
Yes

**Comment by cmnbroad** [comment]
Closed via https://github.com/samtools/htsjdk/pull/638.
