### ISSUE TITLE
CRAMCompressionHeader skips unrecognized encoding tags

### ISSUE THREAD

**Issue by cmnbroad** [samtools/htsjdk#549]
I've not seen this actually happen, but it looks like CRAMCompressionHeader [just discards](https://github.com/samtools/htsjdk/blob/master/src/java/htsjdk/samtools/cram/structure/CompressionHeader.java#L173) any encoding key that it doesn't recognize, which seems like it could lead to data loss.

@vadimzalunin Can you take a look at this ? Shouldn't the code throw instead of log when this happpens?

**Comment by vadimzalunin** [comment]
I think this was done deliberately for compatibility some time ago. But I agree, default behaviour in htsjdk should be more strict.

**Comment by cmnbroad** [comment]
@vadimzalunin 4 of the tests fail when I change the code to throw when it detects these. Can you take a look ?
