### ISSUE TITLE
CRAM multi-interval queries return multiple instances of the same record

### ISSUE THREAD

**Issue by cmnbroad** [samtools/htsjdk#551]
If multiple intervals that do not overlap are specified, a single record will be returned multiple times, once for each interval that it matches.

**Comment by droazen** [comment]
@vadimzalunin This is a pretty serious problem with the existing htsjdk CRAM implementation -- could we get your thoughts on how to fix this?

**Comment by nh13** [comment]
Does that record overlap more than one interval?

**Comment by droazen** [comment]
@nh13 Yes, but with bam multi-interval queries you only get each record that overlaps the array of `QueryIntervals` once (not once per individual interval it overlaps), which is the correct behavior according to the `SamReader` API:

     * Iterate over records that overlap any of the given intervals.  This may be more efficient than querying
     * each interval separately, because multiple reads of the same SAMRecords is avoided.
    public SAMRecordIterator queryOverlapping(final QueryInterval[] intervals);

**Comment by cmnbroad** [comment]
The current implementation creates a new query iterator for each interval, which is why the records get returned once for each interval they overlap. This is also inefficient as the entire stream is re-parsed from the beginning for each interval.

There is a proposed fix in https://github.com/samtools/htsjdk/pull/552, which creates a single CRAMIterator backed by the minimal file spans required to satisfy the intervals, then filters to find the matching records from that. @vadimzalunin let us know your thoughts on this.

**Comment by vadimzalunin** [comment]
@cmnbroad  I like the proposed solution very much given that iterator implementation is shared between BAM and CRAM.

**Comment by yfarjoun** [comment]
hmmm. the description of #552 states that it doesn't fix #551...

**Comment by cmnbroad** [comment]
@yfarjoun PR #552 originally didn't include a fix for this, but it was added and is included, and is listed further down in the comments.

**Comment by yfarjoun** [comment]
OK. it would be good to change the PR comments to make it easier to see.
