### ISSUE TITLE
webpages on building are obsolete

### ISSUE THREAD

**Issue by akiezun** [samtools/htsjdk#566]
http://samtools.github.io/htsjdk/building.html#BuildingHtsJdk

current text is obsolete wrt Java versions

"Building HTSJDK library requires Java 1.6. It may be built with the Java 1.7 compiler, but for maximum compatibility with Java 1.6 JVM, you should compile using the Java 1.6 libraries. This can be done in one of the following ways:

Set an environment variable JAVA6_HOME that points to your Java 1.6 installation.
Pass to ant the argument -Djava6.home= where is the directory of your Java 1.6 installation.
If you do not have Java 1.6 installed on your build machine, you may supply the location of you Java 1.7 installation instead, but there may be problems running code compiled this way on Java 1.6 JVMs."

**Comment by davidbenjamin** [comment]
It's fine now: https://github.com/samtools/htsjdk
