### ISSUE TITLE
add ability for intel deflater to load itself from the packaged jar

### ISSUE THREAD

**Issue by lbergelson** [samtools/htsjdk#598]
Currently people using htsjdk through maven have to go through a bunch of work to get the intel deflater to work.  Every client has to figure out how to extract it from the jar and load it themselves.  

We should enable the intel deflater to load itself from the htjsdk jar automatically so clients can use it without effort.  This probably involves extracting it from the htsjdk into a temp location.  

When compressing a bam, the intelDeflater should be automatically extracted from the jar and used if possible.

**Comment by droazen** [comment]
Can you add an assignee @lbergelson ?

**Comment by lbergelson** [comment]
this is no longer relevant since we removed the intel deflater from htsjdk.
