### ISSUE TITLE
Gradle: Travis-Ci failed with "The command "eval ./gradlew assemble" failed. Retrying, 2 of 3."

### ISSUE THREAD

**Issue by lindenb** [samtools/htsjdk#605]
### Subject of the issue

I'm very new to gradle. When Travis-CI is executed, it fails at the beginning  https://travis-ci.org/lindenb/htsjdk/builds/130833473 . The error seems unrelated to the changes I made.

```
FAILURE: Build failed with an exception.

* Where:

Build file '/home/travis/build/lindenb/htsjdk/build.gradle' line: 35

* What went wrong:

A problem occurred evaluating root project 'htsjdk'.

> Cannot get property 'commitDistance' on null object

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 30.932 secs

The command "eval ./gradlew assemble" failed. Retrying, 2 of 3.

FAILURE: Build failed with an exception.

* Where:

Build file '/home/travis/build/lindenb/htsjdk/build.gradle' line: 35

* What went wrong:

A problem occurred evaluating root project 'htsjdk'.

> Cannot get property 'commitDistance' on null object
```

### Your environment
* version of htsjdk https://github.com/lindenb/htsjdk/commit/1d052a3e32db3e74b1bced00c31d726b39b384ee + commit
* version of java Travis/java 8
* which OS (Travis)

### Steps to reproduce

 https://travis-ci.org/lindenb/htsjdk/builds/130833473

### Expected behaviour
Compilation should be OK

### Actual behaviour

> Travis-CI error: Cannot get property 'commitDistance' on null object

https://travis-ci.org/lindenb/htsjdk/builds/130833473

**Comment by lbergelson** [comment]
Thanks for reporting.  This is almost certainly unrelated to changes you've made.  I'm looking into it.

**Comment by lbergelson** [comment]
@lindenb This seems to be a bug in the version plugin we're using.  If a repo has no tag it's returning a null.  I suspect it can be worked around by adding a tag somewhere in your branche's history.  I'm going to add a patch to work around this as well as reporting it to the plugin author since it looks like a trivial fix and seems like a bug.

**Comment by lindenb** [comment]
fixed with https://github.com/samtools/htsjdk/pull/606
