### ISSUE TITLE
SamReaderFactory fails to return CRAMReader for http resource

### ISSUE THREAD

**Issue by jrobinso** [samtools/htsjdk#614]
Hi, Jim here working on the CRAM conversion.  The call to "factory.open" in the code below fails with the following error

htsjdk.samtools.SAMFormatException: Unrecognized file format: org.broad.igv.util.stream.IGVSeekableBufferedStream@77b52d12

	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:258)
...

I recognize some of the classes below are IGV specific, but the interfaces are all htsjdk.   Hopefully this is an easy fix.

);
        IGVReferenceSource refSource = new IGVReferenceSource();
        String url = "http://1000genomes.s3.amazonaws.com/data/NA21144/alignment/NA21144.alt_bwamem_GRCh38DH.20150718.GIH.low_coverage.cram";
        String indexURL = url + ".crai";

        SeekableStream cramStream =  IGVSeekableStreamFactory.getInstance().getStreamFor(url);
        SeekableStream indexStream = IGVSeekableStreamFactory.getInstance().getStreamFor(indexURL);

        final SamReaderFactory factory = SamReaderFactory.makeDefault().referenceSource(refSource).validationStringency(ValidationStringency.SILENT);

        SamInputResource resource = SamInputResource.of(cramStream).index(indexStream);
        SamReader reader = factory.open(resource);

**Comment by droazen** [comment]
@cmnbroad Could you implement a quick patch for this issue? Should be fairly simple I would think.

**Comment by jrobinso** [comment]
Looking at the code, I don't see how it could be determined that the stream is on a CRAM file.  Perhaps SamInputSource should take an argument specifying the type when a stream is supplied in the constructor (SAM, BAM, or CRAM),  rather than leaving it to the factory to guess.

**Comment by droazen** [comment]
@jrobinso Well, it manages to identify BAM streams via `SamStreams.sourceLikeBam(SeekableStream)`. I imagine that something similar can be done for CRAM.

**Comment by tfenne** [comment]
FWIW I've also had zero luck getting Cram to work on http/ftp.  I recall trying all kinds of things, and hacking around in the code a little bit and it was nigh impossible.  Perhaps a test could be added for CRAM/http and CRAM/ftp to ensure that these work?

**Comment by jrobinso** [comment]
I don't intend to support CRAM via ftp in IGV,  and I"m really sorry I went down that road for BAMs  (FTPSeekableStream).  That was done originally to support loading 1kg files from Sanger.   So from my point of view FTP can be unsupported,  http/https is sufficient.

**Comment by droazen** [comment]
@tfenne Do you remember what the blocking issue was? `CRAMFileReader` does have a constructor that takes an input stream, which is why I thought/hoped this might be simple.

**Comment by tfenne** [comment]
It was a while ago, and I don’t recall.  Sorry.

**Comment by cmnbroad** [comment]
It should be easy enough to tell from the stream if its CRAM. I'll look into these other issues as well.

**Comment by tfenne** [comment]
Thinking about this a little more - I think the symptom I saw was that when doing a range query (query(QueryInterval)) against the HTTP stream it just hung indefinitely.  I was attempting to download a small number of regions from 1000G CRAM files and it never managed to pull any records.

**Comment by jrobinso** [comment]
I’m also trying 1KG files,  and am getting this at the moment  for http://1000genomes.s3.amazonaws.com/data/NA21144/alignment/NA21144.alt_bwamem_GRCh38DH.20150718.GIH.low_coverage.cram.crai <http://1000genomes.s3.amazonaws.com/data/NA21144/alignment/NA21144.alt_bwamem_GRCh38DH.20150718.GIH.low_coverage.cram.crai>

So I don’t know if the problem is with the file,  with reading the file over http, or with the htsjdk.   Is it to be expected that 1KG cram files are correctly formatted?


htsjdk.samtools.cram.CRAIIndex$CRAIIndexException: Malformed CRAI index entry: expecting 6 columns but got 2

	at htsjdk.samtools.cram.CRAIEntry.<init>(CRAIEntry.java:41)
	at htsjdk.samtools.cram.CRAIIndex.readIndex(CRAIIndex.java:40)
	at htsjdk.samtools.cram.CRAIIndex.openCraiFileAsBaiStream(CRAIIndex.java:125)
	at htsjdk.samtools.CRAMFileReader.<init>(CRAMFileReader.java:180)

**Comment by droazen** [comment]
@jrobinso Would you be able to attempt reading the same cram as a local file instead of over http?

**Comment by jrobinso** [comment]
Its 30GB to download but I’ll try tomorrow (downloading now).

Jim

**Comment by jrobinso** [comment]
The index loaded successfully as a local file.  I tried using this index with an http stream for the CRAM,  that did not work, error below

java.lang.NullPointerException
	at htsjdk.samtools.CRAMFileReader$MultiIntervalIterator.next(CRAMFileReader.java:532)
	at htsjdk.samtools.CRAMFileReader$MultiIntervalIterator.next(CRAMFileReader.java:494)

I will be able to test this CRAM as a local file tomorrow,  if that works I’ll try narrowing down the http problems before filing bugs.   I’m using the same SeekableStream classes that have worked for many years on BAM, BigWig, tabix, and tribble indexed files, so I doubt they are the cause.   But I’ll try to verify anyway.

Jim

**Comment by cmnbroad** [comment]
@jrobinso There is a branch in my fork [here](https://github.com/cmnbroad/htsjdk/tree/cn_igv) with a commit that has what I think you need. See the tests I added - I think they mirror what you're doing (only using local file urls - I tried it manually using http and it appeared to work).

It might be a good idea to try it before we commit it in case there are other issues. There is quite a bit of code in these code paths that could use tightening up.

One other thing: wherever possible, IGV should probably try to prefer a .bai over a .crai where one is available, since there is at least one bug in the .crai-.bai conversion https://github.com/samtools/htsjdk/issues/531.

**Comment by jrobinso** [comment]
Hi Chris,

This branch works for local files, but hot remote ones (http), I get the 
same error as before

htsjdk.samtools.SAMFormatException: Unrecognized file format: 
org.broad.igv.util.stream.IGVSeekableBufferedStream@1613674b
     at 
htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:258)
     at org.broad.igv.sam.reader.BAMReader.getSamReader(BAMReader.java:106)

This fails because SamStreams.sourceLikeBam at line 241 of 
SamReaderFactory retrurns false (properly, its not a bam, its a cram) 
and that triggers the exception at line 258.   Note my input type is 
InputResource.Type.SEEKABLE_STREAM.

The URL I'm using for testing is
https://s3.amazonaws.com/igv.broadinstitute.org/test/cram/cram_with_crai_index.cram

**Comment by jrobinso** [comment]
Scratch last comment (deleted), tested wrong branch.

**Comment by jrobinso** [comment]
OK, it works,  I've built IGV using this branch.  When its merged could you comment here so I can switch to the main branch?  Thanks for the quick turnaround.

**Comment by yfarjoun** [comment]
This is fantastic!!! thanks for all who made this happen!

**Comment by jrobinso** [comment]
When I say built I mean locally,  I will push this out to the snapshot 
build this evening.

**Comment by yfarjoun** [comment]
I know...I'm excited that progress is being made and that we might soon be
able to view CRAMs in IGV!

**Comment by cmnbroad** [comment]
@tfenne Just to circle back, reading CRAM from http through SamReaderFactory should work once this PR is in; reading from FTP (via SamReaderFactory anyway) fails due to a [cascade of errors](https://github.com/samtools/htsjdk/issues/623) which are not fixed in this PR.

**Comment by tfenne** [comment]
Thanks @cmnbroad that's great to hear about the http support.  Once it's on master I'll take it for a whirl.

**Comment by jrobinso** [comment]
Yossi, you can pull from source, build, and use this now to load crams from files or urls.  However, I’ve run into an issue making a release build.  We use the bcel to package the igv jar,  and the release version (5.2) does not support Java 8.   I don’t know how easy or difficult this will be to solve.  If you use bcel for your builds and have a solution let me know.

**Comment by jrobinso** [comment]
The development snapshot build of IGV now supports loading CRAM files from local files or http/https urls.  The snapshot is available at http://www.broadinstitute.org/software/igv/download_snapshot <http://www.broadinstitute.org/software/igv/download_snapshot>.   A note:  loading the first region of a sequence (chromosome) is excruciatingly slow.  I think this due to the htsjdk CRAMReferenceSource API requiring the entire sequence up front.   Loading subsequent regions from the same sequence is quick.   This was expected,  just a warning,  IGV has not froze just be patient or go for a Starbucks while it loads.   I will do some profiling to see if this can be improved.

Please file bug reports (other than slow loading) at github.com/igvteam/IGV/issues <http://github.com/igvteam/IGV/issues>.

Thanks to the htsjdk team for making the necessary modifications.

Jim

**Comment by cmnbroad** [comment]
Closed via #620.

**Comment by meganshand** [comment]
@jrobinso I just opened a cram file using the development snapshot build of IGV at Yossi's suggestion. I ran into an issue with the reference that I was surprised by. The cram file I'm using was aligned to hg38 using the Broad's production reference files. When I loaded the cram in IGV I got an MD5 error when I used the default hg38 reference in IGV. I can load the file just fine when I first use the Broad fasta file, but I was surprised that this didn't seem to match the default hg38. Do you have any idea why the two references wouldn't match? If you'd like me to open an issue in the IGV repo, please let me know, I just wasn't sure if this was an "issue" or if the references weren't expected to be identical.

**Comment by jrobinso** [comment]
What assembly are the Broad's production reference files?    Could you open an issue in IGV,  and if possible send me a pointer to the CRAM file and also the fasta.   You can send the file paths by private email if you like,  I have access to the Broad file system.

**Comment by meganshand** [comment]
I'll send you the data and open an issue. Thank you!

**Comment by jrobinso** [comment]
OK.  BTW this is why the MD5 check and exception is absolutely essential,  otherwise you would get incorrect SAM records with no obvious way to know they are incorrect.

**Comment by jrobinso** [comment]
@yfarjoun -- Discussion continued at https://github.com/igvteam/igv/issues/264.   The problem is the IGV hg38 is soft-masked, i.e. has lower-case actg.   Does anyone know how CRAM files are compressed if a soft-masked reference is used?  I've never seen lower case actg in a BAM sequence record.   I'm just unsure how case is treated, if at all,  in the CRAM compression and MD5 calculation.

**Comment by yfarjoun** [comment]
@vadimzalunin  can you comment on this?

**Comment by jrobinso** [comment]
I found it in the spec,  all bases are upper cased.  So its an igv bug,  the reference sequence for cram decompression should also be upper-cased.  Will fix.

1. M5 (sequence MD5 checksum) field of @SQ sequence record in the BAM header is required and UR (URI
for the sequence fasta optionally gzipped file) field is strongly advised. The rule for calculating MD5 is
to remove any non-base symbols (like \n, sequence name or length and spaces) and upper case the rest.

**Comment by jrobinso** [comment]
Actually I'm not sure this is an IGV bug, or rather it should be solved there.   One could argue the same rule referenced above that is used for MD5 calculation when creating the CRAM should be applied when calculating the MD5 for decompression.   In other words Slice.validateRefMD5() should upper-case the reference.   Otherwise its very possible to create a BAM with a soft-masked reference, and be un-able to read it with the same reference.

**Comment by cmnbroad** [comment]
That sounds right to me - htsjdk should do the upper casing.

**Comment by jrobinso** [comment]
@cmnbroad  - I just opened an issue on this (#645).   I'll wait to see what the htsjdk team decides.  I can easily upper-case on the IGV side, but wouldn't want to do it twice.  

You are receiving an array of bytes, not a string, you could just check for values >= 97 and subtract 32 in place when required.  I only mention this because these can be large strings (250MB)  and memory/efficiency might be important if this is done for every CRAM record.
