### ISSUE TITLE
Tests with gradle not working.

### ISSUE THREAD

**Issue by nh13** [samtools/htsjdk#621]
`./gradle test` and `./gradlew test --tests "*SamLocusIteratorTest"` fail.  I would like to run a single test.  I get the following error for the latter:
```
...
htsjdk.samtools.CRAMFileIndexTest.prepare FAILED
    java.lang.NoSuchFieldError: DEFAULT_RECORDS_PER_SLICE
        at htsjdk.samtools.CRAMFileIndexTest.cramFromBAM(CRAMFileIndexTest.java:258)
        at htsjdk.samtools.CRAMFileIndexTest.prepare(CRAMFileIndexTest.java:233)
Running Test: Test method testSimpleInsertion(htsjdk.samtools.util.SamLocusIteratorTest)
```

**Comment by nh13** [comment]
@droazen or @lbergelson can you take a look at this?  I am not up to speed on gradle.

**Comment by droazen** [comment]
@nh13 Hmm, I ran the same command (`./gradlew test --tests "*SamLocusIteratorTest"`) and `SamLocusIteratorTest` ran and passed. Can you do a `./gradlew clean` and try again, making sure there are quotes around the wildcard expression? Also, you can try this alternate syntax for running a single test: `./gradlew test -Dtest.single=SamLocusIteratorTest`

**Comment by droazen** [comment]
@nh13 Did you get this to work for you, or are you still getting the same error?

**Comment by nh13** [comment]
@droazen thanks for the advice, clean worked for me and I am able to execute the tests.  Thanks for the help!
