### ISSUE TITLE
SamReaderFactory fails if input source is a SeekableStream on a SAM file

### ISSUE THREAD

**Issue by jrobinso** [samtools/htsjdk#622]
I've run into an issue that is preventing me from replacing the deprecated direct construction of a ".sam" file reader with the factory pattern.   If passed a SeekableStream on a ".sam" file SamReaderFactory.open throws an exception at line 273
                throw new SAMFormatException("Unrecognized file format: " + data.asUnbufferedSeekableStream());

A SeekableStream is an InputStream and works just fine with SAM files.   I suggest the same logic that is used for the IndexStream cases be used for SeekableStream, namely that if not proven to be something else assume it is a ".sam" file.  In fact I don't know why there are 2 separate sets of case statements for SeekableStream and InputStream.

**Comment by cmnbroad** [comment]
I added a commit to #620 with the proposed fix for this.

**Comment by lbergelson** [comment]
@jrobinso I'm closing this one because I think it was resolved by #620 and we forgot to close the issue.  Please reopen if you're still having problems with this.

**Comment by jrobinso** [comment]
@lbergelson Yes I think it must be resolved, thanks for letting me know.   Also,  I've deprecated support for SAM files in IGV.
