### ISSUE TITLE
Option to force CRAMIterator to throw exception upon sequence slice MD5 mismatch.

### ISSUE THREAD

**Issue by jrobinso** [samtools/htsjdk#627]
IGV now supports CRAM files.  In this implementation, the sequence is provided by IGV from the user's currently loaded reference.   This works,  but I am concerned about sequence validation.  Its incumbent on the user to load alignments against the correct reference.  This has always been the case, but with BAM files the view is lit up with mismatches everywhere so its immediately obvious.  With CRAM it is not,  the view looks pretty normal.    I would like to do some validation using the MD5 values stored in the cram file.   I see this is optionally done in CRAMIterator,  but the errors are only logged (no exception).

Is it feasible to add an option to force CRAMIterator to throw an exception if there is an MD5 mismatch on a slice?   I.E. throw the error here in CRAMIterator (around line 180)?   Any other ideas?  

if (validationStringency != ValidationStringency.SILENT && !slice.validateRefMD5(refs)) {
    log.error(String
            .format("Reference sequence MD5 mismatch for slice: seq id %d, start %d, span %d, expected MD5 %s", slice.sequenceId,
                    slice.alignmentStart, slice.alignmentSpan, String.format("%032x", new BigInteger(1, slice.refMD5))));
}

**Comment by droazen** [comment]
@vadimzalunin @cmnbroad can you comment on this proposal?

**Comment by cmnbroad** [comment]
I think we definitely need this, and I planned to do it as part of https://github.com/samtools/htsjdk/issues/506, but we should leave this ticket open since the two things are related but technically independent.

I would suggest we make the switch be to opt-out, and make the default behavior be to throw.

**Comment by jrobinso** [comment]
That works for me.   It would be good if it weren't tied to the "ValidationStringency"  setting.

**Comment by tfenne** [comment]
I totally agree with @cmnbroad on opt-out ability.  It's totally frustrating to receive borked up files from somewhere and have no way at all to process or correct the files because `htsjdk` refuses to parse them at all.

**Comment by jrobinso** [comment]
Yes Tim, that's why I ask that it not be tied to ValidationStringency.  In IGV that is set to SILENT,  because it seems a substantial % of bam files in the world at large are borked.   However, for this one case I feel we have to validate,  or people will get really misled by loading an hg38 CRAM against an hg19 reference, for example.

**Comment by tfenne** [comment]
Absolutely @jrobinso - I'm all for validation, and even having the strictest validation on by default.  My pain has mostly been with VCFs in htsjdk fwiw.

**Comment by cmnbroad** [comment]
Closed via https://github.com/samtools/htsjdk/pull/671.
