### ISSUE TITLE
Histogram class is pathologically not serializable, despite being marked as Serializable

### ISSUE THREAD

**Issue by droazen** [samtools/htsjdk#630]
`Histogram` cannot be serialized via either Java or Kryo, despite being marked as `Serializable`, for two reasons:

-It has a non-static inner class (`Bin`). According to the Java Object Serialization Specification, serializing non-static inner classes has problems and should be avoided. Kryo does not appear to support this either (see discussion in, eg., https://groups.google.com/forum/#!topic/kryo-users/jgAU18bLyN0).

-It extends `TreeMap`, which has many transient fields and custom Java serialization routines. In extending this class, it appears that `Histogram` did not properly hook itself up with its superclass's custom serialization routines, causing major problems during both Java and Kryo serialization.

This is a blocking issue for porting htsjdk/Picard metrics to Spark. @yfarjoun @tfenne is there any appetite for a slight breaking change to `Histogram` to fix the serialization issues (likely just making the inner `Bin` class static and add a type parameter to it)?

**Comment by droazen** [comment]
Issue was raised by @cmnbroad

**Comment by tfenne** [comment]
@droazen I'm confused by this issue.  The declaration of Histogram is as follows:

```java
public class Histogram<K extends Comparable> extends TreeMap<K, Bin> {
```

It doesn't claim to be serializable.  That said, if you need to make it serializable, I see no problem with making it static and passing through the type parameter.

**Comment by cmnbroad** [comment]
Right - I think the strange bit is that although Histogram isn't marked serializable, Bin is. There is a [commit here](https://github.com/cmnbroad/htsjdk/commit/69674d400a20c692e1bb5aad53ea7cea40200e59) with the minimal changes we'd need. They don't solve all of the Histogram serialization issues since both kryo and java still incorrectly reify deserialized Histograms as TreeMap instances, but they make it very simple to write a custom serializer that delegates to the TreeMap serializer).

**Comment by tfenne** [comment]
@cmnbroad Bizarre.  At any rate that commit seems totally reasonable to me.

**Comment by lbergelson** [comment]
@tfenne `Histogram`inherits `Serializable` from `TreeMap`

I'm definitely a fan of converting Bin to a static parameterized class.  Or even a non-static parameterized class if that's somehow less breaking.  It's caused me pain in the past and intellij's linter hates it as it is.

**Comment by droazen** [comment]
Glad everyone is ok with making `Bin` static and parameterized. I think the other issue (deserialized `Histograms` coming back as `TreeMaps`) could be caused by the fact that `Histogram` inherits from a Serializable class `TreeMap` that has custom serialization routines, but does not provide custom serialization routines of its own that call into the superclass versions.

**Comment by akiezun** [comment]
I wrote code to fix this - see https://github.com/samtools/htsjdk/pull/631
