### ISSUE TITLE
CRAM MD5 validation should use upper-cased sequence

### ISSUE THREAD

**Issue by jrobinso** [samtools/htsjdk#645]
This issue was first reported on #614 and there is some discussion there that I will try to summarize.  It was noted that attempting to load hg38 CRAM files in IGV resulted in an MD5 validation error.  We determined this is because IGV's hg38 uses a soft-masked reference with lower-case actg.  According to the CRAM specification the reference should be upper-cased before calculating MD5  (quote below).   However, the Slice.validateRefMD5 function does not do this.   So the end result is its possible to create a CRAM file with a soft-masked reference that cannot be read without MD5 validation errors,  even against the same soft-masked reference.    I can "fix" the problem in IGV by supplying an upper-cased sequence,  but it could be a problem for other tools.

From CRAM spec:

"M5 (sequence MD5 checksum) field of @SQ sequence record in the BAM header is required and UR (URI for the sequence fasta optionally gzipped file) field is strongly advised. The rule for calculating MD5 is to remove any non-base symbols (like \n, sequence name or length and spaces) and upper case the rest."

**Comment by jrobinso** [comment]
This solved the issue on the IGV side

            // CRAM spec requires upper case
            for(int i=0; i<bases.length; i++) {
                if(bases[i] >= 97) bases[i] -= 32;
            }

**Comment by cmnbroad** [comment]
Closed via #671 .
