### ISSUE TITLE
TribbleIndexedFeatureReader cannot read header from .bgz files

### ISSUE THREAD

**Issue by tomwhite** [samtools/htsjdk#653]
`TribbleIndexedFeatureReader.isGZIPPath` only recognizes paths ending in _.gz_, so block gzip-compressed files are not picked up.

The fix is to check for any of the extensions defined in `AbstractFeatureReader.BLOCK_COMPRESSED_EXTENSIONS` rather than just _.gz_.

**Comment by magicDGS** [comment]
This could be close, couldn't it?

**Comment by cmnbroad** [comment]
@magicdgs The change @tomwhite made only helps Hadoop-BAM. This still needs to be fixed in htsjdk.

**Comment by magicDGS** [comment]
I can take this ticket, because it is easy to fix. So thanks for the answer, @cmnbroad!
