### ISSUE TITLE
Release 2.6.0?

### ISSUE THREAD

**Issue by nh13** [samtools/htsjdk#658]
@droazen @lbergelson would it be possible to perform a release?  It's been >2 weeks and I am looking forward to some of the new commits for my own work.  Let me know if I can help in any way.

**Comment by lbergelson** [comment]
Sure, I think we can do one tomorrow.

**Comment by nh13** [comment]
Thanks @lbergelson!

**Comment by lbergelson** [comment]
@nh13 2.5.1 released!

**Comment by nh13** [comment]
![image](https://cloud.githubusercontent.com/assets/846274/16736352/9730767e-475a-11e6-9f25-356cfa03dfff.png)
