### ISSUE TITLE
> 1 public class declarations in StreamInflatingIndexingOutputStream.java

### ISSUE THREAD

**Issue by delocalizer** [samtools/htsjdk#665]
StreamInflatingIndexingOutputStream.java declares both `StreamInflatingIndexingOutputStream` and `Indexer` classes in the same file, both public. This is not good. For one thing, it means my scala compiler can't actually find `StreamInflatingIndexingOutputStream` class in `htsjdk.samtools` package. As both StreamInflatingIndexingOutputStream and Indexer are useful, I suggest putting them in separate files rather than hiding one with protected/private.

**Comment by yfarjoun** [comment]
Indexer is only used inside `StreamInflatingIndexingOutputStream` any reason not to make it private?

**Comment by delocalizer** [comment]
For my purposes that is fine; I only want `StreamInflatingIndexingOutputStream`.

**Comment by tfenne** [comment]
Both `StreamInflatingIndexingOutputStream` and `Indexer` are both package private.  @delocalizer I think you're confused by the different default access level in scala vs. java.  What you're really requesting here is that `StreamInflatingIndexingOutputStream` be made public.

**Comment by delocalizer** [comment]
My apologies, that's absolutely correct: I assumed the default access level in Java was the same as Scala i.e. public. Yes, the actual request is that StreamInflatingIndexingOutputStream be public.

Date: Fri, 15 Jul 2016 03:41:34 -0700
