### ISSUE TITLE
update to a newer snappy version

### ISSUE THREAD

**Issue by lbergelson** [samtools/htsjdk#666]
HTSJDK currently is using `org.xerial.snappy:snappy-java:1.0.3-rc3`, the most recent version is `1.1.2.6`

Many other projects (spark, rely on newer versions of snappy which have eliminated the `LoadSnappy` class.  If these are required by other libraries they tend to replace the older htsjdk dependency causing htsjdk to break and fail with `NoClassDefinitionFound` if snappy is used.  A workaround is to disable snappy in htsjdk, but this removes any benefit of using snappy in the first place.

It looks like were using this old version of snappy because newer versions statically load themselves and can fail with an Error during static initialization.  

We may need to patch snappy in order to resolve this issue.

See https://github.com/broadinstitute/gatk/issues/2026 for an example of a failure due to loading multiple incompatible snappys.

**Comment by maarten-k** [comment]
I checked the changelog of snappy and there were some speed-ups (although minor):

```
1.0.4 Speeded up the decompressor somewhat; typically about 2–8%
1.0.5 3–10% faster decompression for the base case (x86-64).
1.1.0 Snappy now uses 64 kB block size instead of 32 kB. On average,
    this means it compresses about 3% denser (more so for some
    inputs), at the same or better speeds. 
1.1.1  Speed up decompression by ~2%; much more so (~13-20%) on
    a few benchmarks on given compilers and CPUs.
1.1.4 Improve compression performance by 5%.
Improve decompression performance by 20%.
```

> It looks like were using this old version of snappy because newer versions statically load themselves and can fail with an Error during static initialization.

It looks that org.xerial.snappy:snappy-java is well maintained and I could not reproduce this error(n=1).

I think it is worth the shot to update  org.xerial.snappy:snappy-java  to a recent version. This will also solve some upstream problems.

**Comment by lbergelson** [comment]
@maarten-k I'm definitely in favor of upgrading if we can be relatively sure it won't cause problems.  It's just silly that we're on an ancient beta version instead of a proper release.  

I can't remember if I actually encountered class loading error in my tests or if it's just a theoretical problem.  Traditionally htsjdk has had very minimal reliance on native code to avoid any sorts of hardware dependency issues.  The old version of snappy gives explicit control over loading the native code which lets us catch and throw reasonable errors while the newer versions didn't seem to have a mechanism for explicitly dealing with errors from failure to load the native code.  It may be that the new versions of snappy happen to work on all common platforms, but it may introduce risks of htsjdk failing with mysterious errors on uncommon machines.    

I didn't investigate any further since disabling snappy was a reasonable workaround for my use case.

**Comment by maarten-k** [comment]
Currently version has native binaries for:
>AIX/ppc
AIX/ppc64
FreeBSD/x86_64
Linux/aarch64
Linux/android-arm
Linux/arm
Linux/armv6
Linux/armv7
Linux/ppc64
Linux/ppc64le
Linux/s390x
Linux/x86
Linux/x86_64
Mac/x86
Mac/x86_64
SunOS/sparc
SunOS/x86
SunOS/x86_64
Windows/x86
Windows/x86_64

I think Linux/ppc64le includes power9 so I hope 99.99% of all machines were htslib would run on is covered. 

Maybe testing compressing a short string can function as a test while doing some aggressive exception management , but I think this is a bit hackerish and overdone . Another option is swap this native implementation for java only implementation but I could not find a well maintained version.

**Comment by lbergelson** [comment]
My worries may have been unfounded.  That seems like a pretty comprehensive list.
