### ISSUE TITLE
Exception in VCFEncoder when trying to write a missing value in the VCF "Filter" column

### ISSUE THREAD

**Issue by pabarcgar** [samtools/htsjdk#670]
### Subject of the issue
When I try to write to an VCF file a Variant containing a Missing value (.) in the FILTER column an exception is thrown:

```
java.lang.IllegalStateException: Key . found in VariantContext field FILTER at 20:61118 but this key isn't defined in the VCFHeader.  We require all VCFs to have complete VCF headers by default.
	at htsjdk.variant.vcf.VCFEncoder.fieldIsMissingFromHeaderError(VCFEncoder.java:173)
	at htsjdk.variant.vcf.VCFEncoder.getFilterString(VCFEncoder.java:154)
	at htsjdk.variant.vcf.VCFEncoder.encode(VCFEncoder.java:106)
	at htsjdk.variant.variantcontext.writer.VCFWriter.add(VCFWriter.java:222)
```
Both VCF 4.1 and 4.3 specifications say:

> FILTERs that have been applied to the data should be described as follows:
##FILTER = < ID=ID,Description="description">

> If filters have not been applied,
then this field should be set to the missing value. 

A missing value is not a filter and shouldn't be described in the header.

### Your environment
* version of htsjdk: 1.138, 2.5.1
* version of java: 1.8.0_51
* which OS: OS X 10.11.6 
(After watching the code, I can see this issue will happen in any enviroment).

### Steps to reproduce
```
        // setup writer
        VariantContextWriterBuilder builder = new VariantContextWriterBuilder();
        VariantContextWriter writer = builder.setOutputFile(outputFile)
                .setReferenceDictionary(sequenceDictionary)
                .unsetOption(Options.INDEX_ON_THE_FLY)
                .build();

       // create a VariantContext object and add it to the writer
        VariantContext variantContext = variantContextBuilder
                .chr(chromosome)
                .start(start)
                .stop(sop)
                .noID()
                .alleles(alleles)
                .filter(VCFConstants.UNFILTERED)
                .genotypes(genotypes).make();
      writer.add(variantContext); // -->THE EXCEPTION IS THROWN HERE
```
Just create a VCFWriter, add a header (not in my code example), create a variant (using the htsdjk  constant VCFConstants.UNFILTERED, so the missing filter value is supported) and try to write the variant.

### Expected behaviour
The Variant should be written to the output VCF file.

### Actual behaviour
An exception is thrown.

**Comment by lindenb** [comment]
That would be

```
.filter(VCFConstants.PASSES_FILTERS_v4) //PASS (no filter was set)
```

or

```
.unfiltered() // no filter was tested
```

isn't it ?

**Comment by pabarcgar** [comment]
That's correct. I got confused because of the Constant VCFConstants.UNFILTERED (that I see now that is used for parsing/writting VCF files). Closing the ticket.
