### ISSUE TITLE
Request for a release of htsjdk

### ISSUE THREAD

**Issue by kbergin** [samtools/htsjdk#674]
Hello, 

I have merged in a change to htsjdk that I need for Picard (#667). Would it be possible to have a release? 

Thanks,
Kylee

**Comment by droazen** [comment]
Sure, we'll do a release today -- waiting on merge of https://github.com/samtools/htsjdk/pull/675 first.

**Comment by kbergin** [comment]
@droazen Thank you!

**Comment by lbergelson** [comment]
@kbergin htsjdk 2.6.0 is now available on github
