### ISSUE TITLE
Attack of the zombies! (SAMFileReader/SAMFileTruncatedReader)

### ISSUE THREAD

**Issue by Lenbok** [samtools/htsjdk#695]
The release notes for 2.5.0 say that SAMFileReader and SAMFileTruncatedReader have been deleted.

However, they still exist on master. It looks like there has been a merge muckup that resurrected these files.

**Comment by lbergelson** [comment]
@Lenbok Thanks for pointing this out.  It must have been resurrected during the gradle transition.
