### ISSUE TITLE
How should I cite htsjdk ?

### ISSUE THREAD

**Issue by lindenb** [samtools/htsjdk#738]
Is there a `doi:`  describing the htsjdk library ?

**Comment by yfarjoun** [comment]
The samtools paper points (eventually) at the samtools github, underwhich
htsjdk is published...perhaps that can serve as a good doi?

(10.1093/bioinformatics/btp352
<https://dx.doi.org/10.1093%2Fbioinformatics%2Fbtp352>)

**Comment by lindenb** [comment]
Thanks.
BTW, I've tried to setup a doi from zenodo https://guides.github.com/activities/citable-code/ but one need to be the owner of the repository to create a doi.

**Comment by lindenb** [comment]
@yfarjoun  thanks + closing
 feel free to create a doi from https://zenodo.org/
