### ISSUE TITLE
Set default logging level to INFO instead of DEBUG

### ISSUE THREAD

**Issue by vdauwera** [samtools/htsjdk#739]
We're getting DEBUG messages bleeding through to GATK output, for example this is showing up during normal runs (not setting log level to debug):

    DEBUG	2016-11-04 15:31:23	BlockCompressedOutputStream	Using deflater: Deflater

coming from https://github.com/samtools/htsjdk/blob/master/src/main/java/htsjdk/samtools/util/BlockCompressedOutputStream.java#L166

            log.debug("Using deflater: " + deflater.getClass().getSimpleName());

It would be better to have the default level be INFO. Clients can set a different level if required.

**Comment by ronlevine** [comment]
Closing since  #740 is merged.
