### ISSUE TITLE
SAMFileReader vanished in Version 2.7.0

### ISSUE THREAD

**Issue by tillea** [samtools/htsjdk#767]
Hi,
since htsjdk was uploaded to Debian the packages fastqc and artemis do not build any more with the very same problem which can be seen in the Debian bug tracking system ( [fastqc](https://bugs.debian.org/846708), [artemis](https://bugs.debian.org/846671) ) where you have the build logs which end both by something like

  /<<BUILDDIR>>/artemis-16.0.0+dfsg/uk/ac/sanger/artemis/components/alignment/BamUtils.java:190: error: cannot find symbol
      SAMFileReader inputSam = samFileReaderHash.get(bamFile);
      ^
    symbol:   class SAMFileReader
    location: class BamUtils

I checked that htsjdk is featuring SAMFileReader in the file src/main/java/htsjdk/samtools/SAMFileReader.java - but it just vanished from there.

### Your environment
* version 2.7.0 of htsjdk
* version of java: openjdk-8-jdk 8u111
* Debian (unstable) - trying to build fastqc and artemis package

### Steps to reproduce
Please try to build fastqc.

Kind regards, Andreas.

**Comment by tillea** [comment]
Hi again,
I simply tried to add a copy of src/main/java/htsjdk/samtools/SAMFileReader.java from htsjdk 2.6.1 in 2.7.0, rebuild the Debian package with this.  If I now build fastqc everything seems to be fine.  Did you possibly removed the file by accicent and it just needs to be restored?
Kind regards, Andreas.

**Comment by magicDGS** [comment]
The file was removed in #699 because it was deprecated. I guess that either 1) fastqc/artemis should be updated to use the new API version, or 2) the classpath for them in Debian should include an older version.

**Comment by lbergelson** [comment]
closing, feel free to reopen a new issue if you need help migrating to the new code
