### ISSUE TITLE
SAM TLEN validation does not conform to SAM specifications

### ISSUE THREAD

**Issue by d-cameron** [samtools/htsjdk#768]
### Subject of the issue
TLEN is defined as the template length. For sequencing technologies that sequence entire templates (eg PacBio/nanopore), a non-zero TLEN with no mate coordinates is valid.

> Exception in thread "raw" java.lang.RuntimeException: htsjdk.samtools.SAMFormatException: Error parsing text SAM file. ISIZE must be zero if MRNM is not specified; File /dev/stdin; Line 1
> Line: m121117_092121_42141_c100431002550000001523045902011363_s1_p0/73424/12585_17331   0       chrM    1       50      7M1D33M1D4M1I2M1D7M1D6M1I2M1D21M1D9M1I6M1I12M1I7M1D8M1I18M1I7M1D3M1D3M1I12M1D1M1D28M1D3M1I4M1D4M1D5M2I1M2I3M1I11M1D10M1I3M1I1M1I1M1I7M1D3M1I3M1D9M1D15M1D4M1D8M1D20M1I15M1D1M1I29M1D3M1I9M2D6M1D6M2D1M1D3M1I10M1I8M1D26M1I4M1D5M1I8M1I5M1D6M1D6M1D5M1D21M1D2M1I1M1D5M1I9M1D10M1I2M2D5M1I7M1D17M2I8M1I14M1I10M1D4M1I10M1I24M1I10M2I6M1D9M1D15M1I12M1I5M1I1M2I12M1D4M1I21M1D32M1D13M1D21M1D14M1D7M1D19M1D12M2I42M1I8M4I7M1I9M1D19M1I27M2I12M1D23M1I7M1D13M1I9M1I21M1I3M2D34M1D9M1I4M2I24M2D10M1I6M1D7M1I19M1D12M1I4M1I9M1I21M1D5M2I3M1I9M1D10M1I8M1I10M1I1M1D11M2I3M1I3M1I9M1D5M1I3M2I3M1I4M1I9M1D3M1I6M1D31M1D13M1D4M1D9M1D3M1D30M1I7M1D20M7D3M2D10M1D1M1D1M1D17M1I12M1I2M1D13M1D12M1D14M1I6M1D4M2I17M2D4M1D11M1D16M1I11M1I14M1D5M1D2M1I2M3D1M2D1M1D8M1D10M1D15M1D2M1D3M1I13M1D15M4I3M1I3M1D4M1I10M1D8M1D53M1D6M1I2M1I4M11I1M4I2M1I5M1I33M1I16M1D2M1D3M2I11M1I2M1I6M1D7M2D12M1I4M1D7M1D26M1D19M1D6M1I8M1I4M1D11M2D2M1I11M2I1M1D2M1I3M3D6M1D5M1I10M1D16M1D5M3I13M1D1M1D3M1D3M1D3M1D21M1I6M1I15M1D4M1D2M1D1M1D3M1I10M1D3M1D2M2D1M1D6M1D2M2D8M2D4M1D7M2D5M1D2M2D7M1D1M1D2M1D10M1D31M1I11M2I7M1I4M1I14M1D1M1I10M1D1M2D5M1D6M2D2M1D1M1D6M1D1M1D2M1D7M1D21M1D5M1D8M1I9M1I10M1D8M1I2M1I8M1I22M1I13M2D1M1D7M1I4M3D1M1D9M1D5M1I8M1I6M2D4M1D7M1I4M1D6M1D5M1D11M1D7M1D1M1D10M2I7M1I6M1I3M1D6M2I11M1I4M1D7M1I5M1D29M1I4M1D8M1D15M1D5M1I7M1I5M1I7M1I3M1I2M1I20M1D4M1D7M1I4M2I5M1D10M2D3M1D23M2I1M1I19M1I8M1I7M1D7M1D4M1D4M1D3M1D6M2D8M1D5M1I2M1I3M2D4M1D12M1D2M1I1M1I4M1D12M1D4M1I14M1I28M1I36M3I6M1D6M1I12M2D6M1D9M1I1M1D1M1D9M1I8M1I3M1D3M1I7M1D22M1D1M1I22M1D26M1D11M2D28M2I5M1D15M1I3M1D22M1I2M2I6M1D11M1I5M1D5M1D7M1I8M2I18M1I2M1D5M1D4M1D22M1D3M1D10M2I7M1I12M1D4M2D1M1D60M1D9M1D6M     *       0       3534    GATCACAGTCTATCACCCTATTAACCACCCACGGGAGCGCCCATGGCTTTGGGATTTCGTCCTGGGGGTATGCACGCGATAGCATGCGAGACGCCTGGAGCCCGGAGCACCCTAATGTCGCGTATCTGTCCTTTGATTCCTGCCTCATCACCATTATTACGCAACCTACGTTCAAATACAGGCGGACATACTTACTAAAGTGTGTAAGTTAATAATCTCGTCAAGGGGACCATAATAATAAAATGGAATGTCCTGCCAATCAGCCGCTTCACACCAGACATCAAACAAAAAATTTCCACAAACCCCCCCTCCCCCGCTTCTGGCCACAGCAACTTAAACACATCTCGCCCAAACCCCAAAAACAAAGAACCCTAACACAGCCCTAACCAGTTCAAATTTATCTGGCGGGTATGCACTATTTAACAGCACCCCCCAACTAACACATTATTTTCGCCCTCCACTCCCCATACTAACTAACCCATCATACAACCCCGCCATCCTACCCAGCACACACAACGCCTGCTCAACCCCATACCCGACCCAAGCCACCCCAAAAGACACCCCCACAGTTTATTTAGGGCTTACCTCCCTCAAAGCAATACAACTGAAAATGTTAGAACGGGCTCACAATCACCCCATAAACAAATAGGTTTGGGCCCTAGCCTTTTTCTATAGCTCTTATAAGATAACACATGCAAACCATCCCCGTGTCCAGATGGGAGTTCACCCTCAAATCCACCACGATCAAAAGGGACAACATCAAGCACGCAGCAATGCAGCTCAAAACGCTAGCCTAGCCACACCCCACGGGAAACAGCAGTGATAACCTTTAGCCATAACGAAAATTAACTAAGCTATACTAACCCAGGGTTGGTCCCAGTTTCGTGCCAGCCACCGCGGTCACACGATTAACCCAAGTCCAATAGAACCCCCCCGGCGAAAAAGAGTGTTTAGATCACCCCCTCCCCAAATAAAGCTAAAACTCACCTGAGTGGTAAAAAAAACTCCAGGGACACAAAAAAGACTACGAACGATGGCTTTACATATCTGAACATCACAATAGCTTAAGACCCAAACTGGGATTAGAATACCACTATGCCTAGCCCTAAACCTCAACAGTTAAACAACAAAACTTGCTCCCGCCAGAACACTACGAGCCACAGCAAAACTCAAAGGGACCTGCGGTGCTTTCATATCCCTCTAGAGGACCTGTTCTGTAACCCGATTAAACCCCGAATCAACCTCACCACCTCTTGCCAGCCGATATAATACCGCCACCCCAGCAAACCCCCGATGAAAGGCTACAAGATAAGCGCAAGTAAACCTCACGGTAAAGACGTAGGTCCAATGGGTGGTAGCCCCATGAGGGGCAAAGAAAAGGCTACATTTTCTACCCCAGAAAACTACGAAGCCCTTATGAAATTAAGGTCGAAGGGGATTAGCAGTAAACTGAGAGTAGAGTGCTTAGTTTGAACAGGCCCTGAAGCGCGTACACATCACTCCTCAAGTTCTCCAAGGACATTTAACTAAAAACCCCTACGCCATTATATAGAGGAGCAAGTCGTAACAGGTAAGTGTACTGGAAAAGTGACTTGGGGACGAACCAGAGTGTATTAAACAAAGCACCCACTTACACTTAGGAGATTTTCAACTTAACCTTGACCGGTCTGACTAAACTAAGCACCACTCCACTTACTACCAACAAACTTAGCCAAACATTACCCCAAATAAAGTAAGGCGATAGAAAATGAAAAAAACCCTGCGCAAATAGATATATACCGCAAGGAAAGATGAAAAAATATAACAAAGCATAATATAGCAAGGACTAACCCCTATACTTCTGCCATTAATGGGGGGGGGGGGAAAAAATTTAACTTAGAAATAACTTTGCAAGGAGAGCCAAAGCTAAGGACCCCCGAAACCAGAGACTACCCCTAAGAACAGCCTAAAAAGACACACCCCTATGTAGCAAATATAGGGGAAGATTATAGGTAGAGGCGACAAACCTACCCGCCTGGTGATAGCTGGTTTCCAAGAATAGAATCTTTAGTCAACTTTAAATGCCCCACAGAACCAACCTGAAACCTTGTAATTTAAACTGTTAGTAAAAGAGGAACAGCTCTTGGACCCCACTAGGAAAAAACTGTGAGGAGGAAAAATTTAACACCCATAGTAAGGCCTAAAAAGCAGCCACCAATAAGAACTTCAAAGCTCAACACCATATAAAAATCCACATATAAGAACGCTCATACAATTGAAATCTATACCATAGAAGAACAATGTTAGTATAAGTAACATGAAAACATTCTCCCTCCGCATAAGCGCCTGCGTTCAGAATTAAAACACTGAATGGACAATTAACGCAATACTACAAAACACAGGTATATACCCTCCTGTCAACCCAACACAGGCATCTCATAGGAAAGGTTTAAAAAAAGGTAAAAGGAATCGGCAAATCCGTTACCCCGCCCTGTTTACCAAAACCATCACCTTCTAGCATCACCAATAAAGGCAACCGGCCAGTGACAATGTTATAACGGCCGGCGGTACTAACGTGCAAGGGGTGCATAACACTTTTTCTTAAATAGGACCTGAGAATGGCTCCAAACGAGGGTTTCAGCTTGTTCTTACTTTTTTAACCAGTGGAAATGACCTGCCCCGTAAGATGCGGGCATAACACAGCAAGACGAGAAAGACCTATGGACTTTAAATTATTAATCAACCAAGTACCTAAACAACACCCACAGGGTCCCGTAAACTACCAAACCTGCATTAAAATTCGGTTGGGGGCCCGACCCCGAGCAGAACAACTCCGAGCAGTACATGCTAAGACTTTATCACCAGTCAAAGCGAACTAACTATACTACAATTGACCAATAATTGACAACGAAAAGTTACTAGGGATACAGCAGCAAATTATTTAGAGTCCCCATAATCGAATAGGTTTACGACCTGATGTTTGGATCAGGACATCCCCGAGGGTGCAGCCGCTATTAAAGGTTCCGTTTGTTCAACGATAAAAGTCCTACGTGATCTGAGTTTTTCAGACGGAGTAAATCCAGGTCGGTCTATCACTTCAAATCTCCCCTGTACGCAAGGGACAGAGAAAATTAAGGCCACTGCACAAAGCGCCCTCCCCCTAAAATGATATCATCTCAACTTAGATTATACCCACACCCACCCAAGAACAGGTTTGTTAAGGGCAGAGCCCGGTAATCGCAAAAAACTTAAAAAACTTACAGTCAGAGGTTCCAATCCTCCTCTAAACAACATACCCAATGAGGCCAACTCCTACTCCTCCATTGACCCATCTAATCGGCAAGGGCAAATTCCTAATGCTTACCGAGACAAAAATCTAGCTATATACAACTACGCAAAGGCCCACGTTGTAGGCCCCCCTACGGGGCTACTACAACCTTCGACGCCATAAAACTCTTCACCAAAGAGCCCCTAAAACCCGCCACATCTACCATCAACCTCACATCACCGCCCGAC *       RG:Z:87b3dbc383 AS:i:-13445     XS:i:1252       XE:i:4747       XL:i:3495       XT:i:1  NM:i:1

### Your environment
htsjdk 2.6.0
picard 2.6.0

### Steps to reproduce
Create an unpaired read with a TLEN matching the sequence length and parse.

### Expected behaviour
Non-zero TLEN without mate coordinates is valid for unpaired reads. The exception should only be raised if the SAM flags indicate the read is paired.

### Actual behaviour
An exception is raised for valid PacBio input reads

**Comment by yfarjoun** [comment]
This is in the Sam spec. please discuss it there first:

   >It is set as 0 for single-segment template or when the information is unavailable.
