### ISSUE TITLE
Convert source tree from UTF8 chars into us-ascii

### ISSUE THREAD

**Issue by mmokrejs** [samtools/htsjdk#783]
Hi,
  java-8 is picky about UTF8 chars in the sources, it even bother about such comment in comments. Here are some I hit in current git checkout.

```
/scratch/var/tmp/portage/dev-java/htsjdk-9999/work/htsjdk-9999/src/test/java/htsjdk/samtools/util/PositionalOutputStreamTest.java:4: error: unmappable character for encoding ASCII
 * Copyright (c) 2015 Daniel G??mez-S??nchez
                              ^
```

**Comment by yfarjoun** [comment]
Thanks. @magicDGS, would you be able to change your copyright info to have only ascii characters?
