### ISSUE TITLE
CRAM MD5 slice validation fails on samtools .cram when reference contains ambiguity codes

### ISSUE THREAD

**Issue by cmnbroad** [samtools/htsjdk#800]
### Subject of the issue
The slice md5 validation check fails when reading crams that were created by samtools if the slice spans a reference sequence that contains ambiguity codes or '.' bases.
In https://github.com/samtools/htsjdk/pull/644, we added reference normalization using the CRAM normalizer, but samtools appears to not do this for purposes of creating the slice md5s; it appears to only upper case, so the validation can fail in that case.

This may be contributing to https://github.com/samtools/htsjdk/issues/778.

### Steps to reproduce
Create a CRAM with samtools that contains reads that map to a reference sequence containing ambiguity codes, and try to read it using Picard/htjdk. Get: Reference sequence MD5 mismatch for slice: sequence id 0, start 248277670, span 668735, expected MD5 27531c3c5449c67316a4fe39e6c928ea

### Actual behavior,
File should be readable.

**Comment by tlangs** [comment]
When will a fix for this issue be completed and merged?

**Comment by cmnbroad** [comment]
@vadimzalunin Ping. The PR #801 for this is assigned to you, so I'm adding you to the issue as well. We really just need the final tests and validation that the fix is correct wrt compression.

**Comment by cmnbroad** [comment]
Closed viahttps://github.com/samtools/htsjdk/issues/800
