### ISSUE TITLE
Please release a new version of htsjdk. 

### ISSUE THREAD

**Issue by yfarjoun** [samtools/htsjdk#805]
@lbergelson

**Comment by lbergelson** [comment]
We've been waiting on one of the tom white pull requests.  @droazen What's the status of that, have you taken a look at it or should I?

**Comment by lbergelson** [comment]
I can also just do a release now and then another once that goes in...

**Comment by yfarjoun** [comment]
Not that urgent, but there's a Picard PR that is waiting on it, and it's
been a while..so I thought I'd put an issue for it...

**Comment by lbergelson** [comment]
Yeah, sorry.  I think we told you we'd have it done a month ago...

**Comment by yfarjoun** [comment]
I thought it was done...:-)

**Comment by droazen** [comment]
Will take a look at the relevant PR now

**Comment by droazen** [comment]
Since that PR still scares me a bit, and I think we need to do another round, I suggest we do a release now without that change.

**Comment by lbergelson** [comment]
@yfarjoun 2.9.0 is out on maven central now.

**Comment by yfarjoun** [comment]
Thanks!
