### ISSUE TITLE
Samtools sort CIGAR operations limitation, despite not using BAM

### ISSUE THREAD

**Issue by AlexanderDilthey** [samtools/htsjdk#860]
samtools 1.4 sort gives me an error when trying to sort a SAM or CRAM file with more than 64K CIGAR operations.

Example command:

/data/projects/phillippy/software/samtools-1.4/samtools sort combined_with_header.sam -o combined_with_header_and_sorted.sam

Example output:

[E::bam_write1] too many CIGAR operations (66411 >= 64K for QNAME "CHM1.gi|929855600|gb|LJII01000029.1|")
samtools sort: failed to create temporary file "combined_with_header_and_sorted.sam.tmp.0000.bam": Value too large for defined data type

I have exactly the same problem when trying to sort a CRAM file.

**Comment by yfarjoun** [comment]
should this be posted in the samtools repository rather than the htsjdk?

**Comment by AlexanderDilthey** [comment]
Clearly yes! Sorry!
