### ISSUE TITLE
PR build failed due to FTP unavailability

### ISSUE THREAD

**Issue by vadimzalunin** [samtools/htsjdk#861]
Travis reports test failure in https://github.com/samtools/htsjdk/pull/834

The log file excerpt: 
[31m- testFTPOpenInputStream *** FAILED ***[0m
[31m  java.net.ConnectException: Connection timed out (Connection timed out)[0m
[31m  at java.net.PlainSocketImpl.socketConnect(Native Method)[0m
[31m  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)[0m
[31m  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)[0m
[31m  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)[0m
[31m  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)[0m
[31m  at java.net.Socket.connect(Socket.java:589)[0m
[31m  at java.net.Socket.connect(Socket.java:538)[0m
[31m  at java.net.Socket.<init>(Socket.java:434)[0m
[31m  at java.net.Socket.<init>(Socket.java:211)[0m
[31m  at htsjdk.samtools.util.ftp.FTPClient.pasv(FTPClient.java:138)[0m
[31m  ...[0m

I'm guessing ftp://ftp.broadinstitute.org/pub/igv/TEST/test.txt was unavailable while running test htsjdk.tribble.util.ParsingUtilsTest#testFTPOpenInputStream

The files seems to be available now, not sure what happened. Would it be possible to re-run the build?

**Comment by droazen** [comment]
@vadimzalunin I've re-started the travis build for that PR -- the ftp tests are prone to intermittent failures, unfortunately.
