### ISSUE TITLE
BAMFileReader does not expose constructors

### ISSUE THREAD

**Issue by binaryminary** [samtools/htsjdk#873]
Very simple oversight, while BAMFileReader has been made public to expose the class outside the package, the constructors have not been made "public" and therefore the class cannot be instantiated in other projects without hacking around this issue using reflection.

**Comment by yfarjoun** [comment]
You should use a factory for that:
```java
   final SamReader samReader = SamReaderFactory.makeDefault()
                    .referenceSequence(REFERENCE_SEQUENCE)
                    .open(SamInputResource.of(INPUT));
```

**Comment by binaryminary** [comment]
Ah many apologies, I had thought I searched for usages within the package but looks like I missed it. Thanks.

**Comment by yfarjoun** [comment]
no worries. Welcome to the project!

In general, I would recommend looking for usages in picard https://github.com/broadinstitute/picard/

or other libraries that use htsjdk.
