### ISSUE TITLE
Queries for non-existent contigs throw exception

### ISSUE THREAD

**Issue by jrobinso** [samtools/htsjdk#874]
I'm not sure if you consider this a bug, or not, or when exactly the behavior changed,  but doing queries against a contig (sequence, chromosome) not present in a SAM or BAM file now throws an illegal argument exception.   At some point in the past an empty iterator was returned.    Clients (such as IGV) sometimes query for regions present in the fasta but for whatever reason not present in the SAM or BAM file.    If this new behavior is the result of a deliberate decision  I will work around it by catching the exception in IGV,  I raise it here in case it was not a deliberate decision.   (i.e. decision to throw an exception as opposed to returning an empty iterator).

java.lang.IllegalArgumentException: Invalid reference index -1
	at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:533)

**Comment by yfarjoun** [comment]
I don't know if it was a decision on which deliberation occurred, or not, but it seems to be me that this is the proper behavior. An empty iterator would imply that the request is legal, but there are no records in the requested region/contig/locus. 

Asking for a contig that doesn't exists is illegal and normally implies that there's a dictionary mismatch. IGV has a user interface and so, of course, the user may ask for a non-existent contig directly. 

my 2cts.

**Comment by jrobinso** [comment]
OK, that makes sense.
