### ISSUE TITLE
Request: Release 2.10.1

### ISSUE THREAD

**Issue by nh13** [samtools/htsjdk#891]
I would request a release of htsjdk to include this [merged PR](https://github.com/samtools/htsjdk/pull/877) so I can use it in [Picard](https://github.com/broadinstitute/picard/pull/830)

**Comment by tfenne** [comment]
I don't know what the policy is in Picard ... but you could also depend on the exact snapshot version that commit generated, in the Broad's artifactory repo.

**Comment by lbergelson** [comment]
@nh13 I'll cut a 2.10.1 release tomorrow morning.

**Comment by nh13** [comment]
Thanks @lbergelson !

**Comment by lbergelson** [comment]
@nh13 2.10.1 is released and should be percolating through the sonatype system towards central.  Their site seems very sluggish today though so it might take a bit.  

In a related note, the Broad artifactory moved a few days ago.   It's supposed to be redirecting but gradle doesn't seem to follow redirects correctly when uploading so the most recent commits annoyingly haven't published snapshots.  I have a pr here https://github.com/samtools/htsjdk/pull/892 that should fix the problem.
