### ISSUE TITLE
Remove SRA code from htsjdk 

### ISSUE THREAD

**Issue by yfarjoun** [samtools/htsjdk#894]
I was wondering if we could remove the SRA code from htsjdk. To me it seems that SRA is the source of little more than headaches due to intermittently broken tests. 

Is anyone deriving enough utility from the SRA code that they are willing to make the code more robust so that we don't get intermittent test failures? This should still be done while still testing SRA, naturally... 

Discussion? Vote? or 🏏

**Comment by lindenb** [comment]
on my side, I've never used the SRA code

**Comment by magicDGS** [comment]
I've never used the SRA code either, although I was planning to explore it at some point. But if it is buggy and/or broken, I vote for removal, with plans to implement it in the future and make it more robust from scratch.

**Comment by tfenne** [comment]
Similarly, I _never_ use the SRA code and would be happy to see the problems that it causes go away.  @yfarjoun my impression was that the GATK valued having this here ... is that no longer the case?

**Comment by vdauwera** [comment]
This was proposed by ncbi and I'm aware of a few users who use it, but afaik it's not widely used. I'm reluctant to just remove functionality that some people might depend on, however. What kinhds of problems are we talking about? Can these be quarantined?

**Comment by ronlevine** [comment]
IIRC, the problem had to do with a server timeout when accessing the SRA data. @lbergelson was dealing more with this.

**Comment by yfarjoun** [comment]
@vdauwera perhaps ncbi should implement it as a tribble plugin that they maintain and test...(is that possible?) It's very frustrating to have tests fail due to server problems that we do not control, especially when we hardly know anyone that is using the functionality that is provided. alternatively, We could disable all the tests that use SRA and have bit rot.

**Comment by yfarjoun** [comment]
@vdauwera The "functionality" has been broken for several months at this point...were there any complaints?

**Comment by vdauwera** [comment]
If the break happened after we last cut a GATK release (nov 16 iirc) we wouldn't expect any complaints.

I thought we had asked the ncbi devs to address the test timeout issues. @ronlevine I think you were involved, do you remember anything about that?

**Comment by ronlevine** [comment]
@vdauwera If anyone was in communication with them, it was @lbergelson and/or @droazen.

**Comment by droazen** [comment]
We have not been in communication with them since the initial PR.

**Comment by vdauwera** [comment]
@a-nikitiuk Would you be able to comment on the status of SRA code and functionality?

**Comment by yfarjoun** [comment]
seems like no-one cares...we removed SRA from the testing framework....so no it will just rot away.
