### ISSUE TITLE
Suggestion/discussion: Integrating the java bigwig library into htsjdk ?

### ISSUE THREAD

**Issue by lindenb** [samtools/htsjdk#895]
pinging @jrobinso 

There was a java library for **bigwig**/**bigbed** hosted at code.google.com : https://code.google.com/archive/p/bigwig/ and AFAIK it's bundled in IGV. 

But the standalone library was not officially moved to github (?): ( https://github.com/search?l=Java&q=bigwig&type=Repositories&utf8=%E2%9C%93 )

As htsjdk is defined as the library for _'high-throughput sequencing data (HTS) formats.'_ I think htsjdk would be a good place to include the sources of bigwig .

**Comment by magicDGS** [comment]
This can be implemented in the tribble package as a codec, no? I like the idea to implement more stuff in tribble!

**Comment by jrobinso** [comment]
@lindenb bigwig / bigbed should probably be forked from igv and made its own project,  I would not be in favor of adding it to the htsjdk personally unless there is a solid commitment from that team to maintain it.   I do still get and fix bug reports occasionally.   In other words I don't want to have to submit a PR to htsjdk to fix a bug in igv.   I don't think it (bigwig) is a priority for the htsjdk team.

@magicDGS No, its not as simple as implementing a tribble codec.   

BTW I created tribble as a means, primarily, to index ascii annotation files.   While I was working on this Heng implemented tabix (over a weekend) making the tribble system redundant, or at least not as needed.  Personally I recommend tabix for ascii file indexing, its compressed and the index is better.

**Comment by jrobinso** [comment]
@lindenb If you open a request in the IGV github to fork bigwig/bigbed I'll get to it, not immediately but in a reasonable amount of time.   I'll do it anyway but a reminder helps.

**Comment by lindenb** [comment]
@jrobinso I see + I understand , no problem.

> I'll do it anyway but a reminder helps.

I'll do it, thanks :-)
