### ISSUE TITLE
SeekableStream subclasses should implement InputStream.available()

### ISSUE THREAD

**Issue by lbergelson** [samtools/htsjdk#898]
The default implementation of `InputStream.available()` just returns 0.  SeekableStream implementations should make a best effort implementation of this instead of using the lousy default.

**Comment by lbergelson** [comment]
This is more important than we thought due to a bug in `GZIPInputStream` where it relies on the result of `available` in order to determine EOF.

**Comment by droazen** [comment]
See full description of the interaction of the `GZIPInputStream` bug with htsjdk `SeekableStream` classes here: https://github.com/broadinstitute/gatk/issues/4224#issuecomment-360282461

**Comment by magicDGS** [comment]
Maybe a different way to go is to use [`GzipCompressorInputStream`](https://commons.apache.org/proper/commons-compress/apidocs/org/apache/commons/compress/compressors/gzip/GzipCompressorInputStream.html) from commons-compress instead, which is already a dependency of HTSJDK (similar proposal as #799)
