### ISSUE TITLE
SamFileValidator needs more checks, as does SetNmUqAndMd

### ISSUE THREAD

**Issue by yfarjoun** [samtools/htsjdk#899]
- check that if record is flagged as unpaired, mate reference is *
- check that if MateReferenceName is *, then MatePOSition is 0 
- check that SEQ.length() == QUAL.length()
- CIGAR length was different length than SEQ.length()
- Compare files dictionary to that of the reference
- also SetNmUqAndMd doesn't compare the file's dictionary to the reference's dictionary...

**Comment by yfarjoun** [comment]
@ronlevine can you fix this for us?

**Comment by ronlevine** [comment]
Will do.

**Comment by ronlevine** [comment]
I assume `SetNmUqAndMd` if referring to picard's `SetNmMdAndUqTags`.

**Comment by yfarjoun** [comment]
yes. sorry.

**Comment by ronlevine** [comment]
Much of the logic is in the unused `SAMTestUtil.assertReadValid`.

**Comment by yfarjoun** [comment]
hmmm. but for validation we need something better than exceptions on
errors...we are collecting informative errors...could you refactor that
(unused) function into one that can be used in ValidateSamFile? (and wrap
the refactored version with a assertReadValid)

**Comment by ronlevine** [comment]
Yes, the logic is the same but the error handling is different.  And, I am in the process on refactoring the logic...

**Comment by ronlevine** [comment]
Closing since #907 is merged and created an issue for [SetNmMdAndUqTags needs to compare the SAM file's dictionary to the reference's](https://github.com/broadinstitute/picard/issues/845).
