### ISSUE TITLE
Support for partial VCF writing - htsget extension for VCF

### ISSUE THREAD

**Issue by cyenyxe** [samtools/htsjdk#902]
### Motivation
The [htsget specification](https://samtools.github.io/hts-specs/htsget.html) allows to query multiple data blocks in parallel by providing links to different regions. When extending it to support VCF, it is necessary to return metadata and data blocks separately.

### Subject of the issue
The way the [VCFWriter class](https://github.com/samtools/htsjdk/blob/master/src/main/java/htsjdk/variant/variantcontext/writer/VCFWriter.java) currently works forces to initialize the header and inner `VCFEncoder` when the header is first written. The writer can't be fully initialized unless the header is written.

If the classes derived from `VariantContextWriter` supported setting and writing the header in 2 different steps, both the existing use cases and the htsget one would work.

**Comment by lbergelson** [comment]
This was closed by #904   Thanks everyone for the work on this!
