### ISSUE TITLE
Add option to use the maximum instead of the first overlap for LiftOver

### ISSUE THREAD

**Issue by ronlevine** [samtools/htsjdk#924]
### Subject of the issue
LiftOver uses the first chain overlapping the an interval that satisfies the "minimum fraction of bases that must remap" criteria. This makes it sensitive to the the order of items in the chain file. It should have the option of choosing the remapping that has the highest number of bases that overlap.

### Your environment
* version of htsjdk -  - 2.10.1
* version of java - 1.8.0_66-b17
* which OS - MacOS 10.12.5

### Steps to reproduce
Change the logic in the `for (final Chain chain : chains.getOverlaps(interval))` loop in `LiftOver.liftOver()` to choose the `targetIntersection` with the maximum number of bases rather than the first `candidateIntersection.intersectionLength >= minMatchSize)`.

### Expected behaviour
For a given interval, the remapped interval that satisfies the minimum overlap criteria and whose bases the have the `maximum overlap` with the input assembly.

### Actual behaviour
For a given interval, the `first` remapped interval that satisfies the minimum overlap criteria and whose bases overlap the input assembly.

**Comment by yfarjoun** [comment]
closing due to lack of interest.
