### ISSUE TITLE
BinningIndexBuilder assumes no feature can be at offset 0

### ISSUE THREAD

**Issue by cmnbroad** [samtools/htsjdk#943]
For feature files with no header (like a BED file, which may have no header), 0 is a legitimate offset, even if the file is block gzipped and the offset represents a virtual file offset. However, the binning indexer always sets the window for a bin to the lowest feature offset for that bin that is not 0. i.e., BED files can have the first feature at offset 0. 

Fixed in https://github.com/samtools/htsjdk/pull/906.

**Comment by cmnbroad** [comment]
A example where this issue manifests is in https://github.com/samtools/htsjdk/pull/820.

**Comment by magicDGS** [comment]
Dup of https://github.com/samtools/htsjdk/issues/393?

**Comment by cmnbroad** [comment]
@magicDGS I created this ticket so we could track the BinningIndexBuilder part of the issue separately from the .gz part. So there is some overlap, but not exactly a dup.

**Comment by cmnbroad** [comment]
Fixed via https://github.com/samtools/htsjdk/pull/906.
