### ISSUE TITLE
something wrong with the total depth output of mpileup  

### ISSUE THREAD

**Issue by liufengxia99** [samtools/htsjdk#965]
### Subject of the issue
the depth not right, much less than the 

### Your environment
samtools 1.3.1 or 1.5

### Steps to reproduce
/gpfs/software/pipeline/pipeline/tools/samtools mpileup -d 100000 -f /gpfs/software/pipeline/pipeline/database/ref/hg19/hg19.fasta -l /gpfs/software/pipeline/pipeline/region/region_59_188k/region_59_188_merged.bed /gpfs/project/59gene_188K/project_2samples_20170725.business/baidecheng_cf/qc/mapping/tumor/PM2017072404.final.bam > /gpfs/project/59gene_188K/project_2samples_20170725.business/baidecheng_cf/snv/pair/varscan/PM2017072404.pileup

### Expected behaviour
positonal depth is much less than the reality
samtools depth -r chr1:11856378-11856378 chr1_11856378.bam                       
chr1	11856378	2883

### Actual behaviour
the depth in my bam should about 2800X, while mpileup output is only 1330X, and the reads between forward and reverse strand diff greatly
les tumor.chr1.PM2017072404.pileup.gz|grep -P "chr1\t11856378"
chr1	11856378	G	1330	.$.$,$......AAA.A...A.,a,,,AA.Aa,,aaa..A,AAAA.aa,,a.A,aaaa,,,,aaaa,,,,a,,.AAAAAa,,,a,.....AAaaaa,,aaa,a,,a,aaaAA.A.a..AAA.......A..AA,,aaa,,,,a,,,,,,aaaa,A.Aa,,....,.A.,,,..aa,.,a..,A,,A..Aa,,a,AA.A......aa....A.....AA.A.A..A..AAA.a,,a,aaA..AAA.a.AA.A.AA,,aAa,a,,AA..A....A..,....A..A....AAAAA.A...AA..A..A..AAAA,AAA..A...A...A.A..AAAA.A..AAA...AA...A,.AAAA...AA...AA..A..AAAA.A..AAA..AA,aA.AaAa,.....A.AAA.A......A.A..AAA..A...AAAA..A...AA.......AA......aa...A.,A...A..A.AA..AAA.A..A.A..A.AA..A....AA.AAA....AA.AA.,..A..A..A.......AAA...AA..A...A.AAAA...A..A..AA.A..AA.AAAAAAA..A....AA.A.AA...AA.A.A...A....A..A...AA...AA...A.AA.AA.....AA.A..AAAAA.A...AAAA............A..AAA..A.AA.AA.....AAA...AAA...A.AAAAA......A...A..A......A.AA.AAA.AA...AA..A....A...AA.AAA...AA...AA...A..AAA.AAA........aAAA..AA...AA....,aa,,AA..A.AA......AA.AA..AAAA..AA.Aa,,,,A.A..AA.A......AAAA.AAAAA.AA..A..A..A.AA.....AA.A....A.AA.....AA..AAA.AA.AA...A.A.......AA.AAA.AA....A...AA..AA.AA......AA.AA...AA.AAA..A...AA..........A...AA..AA.A...AA...a...A.A.....A.AA....A...A..A..AAAA....A.AAA.AAAAA...AAAAAA....A.....A.A.A,a,,aaAA...A..AA.AA..AAA...A......A...A....AA...AA....A.AAAA.A...A.A....A.AA.A...AA.A.A.AA.A.AA.A.A.aAAA.AAAA..AA.AA.....AA.A.A.......AAA.A..A..A..Aa..A.AA....A.A...A.A..AA.A.AA....AA..AA,AAA.AAAA..AAAA...A.AAAA..A.AAA..AA.A.A.A,AAA....^].^].	[QB]Y^__SSSY`U_]]S]B0BBBT[_[?@@???bUTCbbbTeC3DDChgF5CDCAGFFCDDCGGG.CFFigf[ggDG4GDGjjjOlfgCDCDGGCDDFCFFDGDDCSSjgi@ljgddkfkljjjSjldgGFCCCGFGGDFFFGGFCCCDGgleDGFjjUjGlhjFAFjmDCGmGCgjFfGFekjSCGGDGgTmSkmllfmD=miiihkmimfhei`jegmfiQSgShCGG?GCD`khhhhkdhedjSUeSGFCSCFDGGdhmiTjillfmmBllkldKlSmlll;gggSlclilcemhhjlhmeddShGcggldTmKjcliigjgmfcagglflkeghmjjgTmmmgFjdgSgllkcglUlhcmjgmhTddemgjmhdSmmggFDSjTDggmmjlmmemhhcmdmlmhhmhmdlmfghmmfmmmddhhimhmmmhhmlglmhm@dlmmmmgCDmmmhmFhmlghlmfUhhkfTPhmfilhbgmhfmhhhmSimmmhhlegcmmmmdhhhhlGmmhmmhimhmmmmhmmTefmmmhammdmmmfmghfTmmmhmmdmmffhhmmhdmcgddffSmmTmmmmfSmhhhTmllgflSlgmm]clmlihmmfmmlSeimmdhimmhmhhmfhmiiQmdTVfmmgThddmhlmifchfmlglimmlllllglmggcildlffmcfmmmmmhhelmmhhhmcmhmhhfhhmmhmmmglmmhmmhmimmhmfmhhgfff`ghlelfflQflmQ:fllleemghcmmlcfmm]hfllmhfmhdhmfhhmlhhlmihhgfTlmghGllgemlfmfhgmlhfmlbmhhlmmlmjThmcTmmheccmlheldgmlmmhmhimfCmemmimmlhhhTmhhefhlhfllfimhmlhlhhjlmePgfmhmmmmhmhhmilmmcfmmfhglhghfgcllhifmlmmliahdmhheihgmfmmhmmehRjmhhmhejmllilghjhhmhmhhVhEflmgmmjfdlkkOhmmmmihmmiThjmggGcilhaclmhhmmmhmSiGmmmaBehmh^jelllZmlhLm^dRhmmmhUiggZmghdf^imhggegggjmGifllGmjgig_gmgmmhPgh\lmgjMhEmTgjmThhmmGhGmlhl\dimmfi^medhlmlghlKjldlfEhhmEmm\f_hghGGdldZlh_mlZflgGhGEgg\_ggaE]TdhEEDmZEgLiFfhhTdGdheFfelEmIG\FFcGGECD\GGgEGlLlGBhFFDFIEGlG_MGgelBZjhG\CgmdFhgGGdG4fFGDDhcJEFDCCbGGEDOBF_FDFVeV9icCFELTjleDiENECKg<T:FfbfB[
i don't how to supply my bam file

**Comment by lbergelson** [comment]
Hi @liufengxia99 

I think you meant to post this issue to https://github.com/samtools/samtools.  Samtools is a set of tools built on the c library htslib.  This is htsjdk, a separate library that implements similar functionality in java.  It's easy to get us mixed up because we're all under the samtools organization.  The development teams are different though without a lot of cross over. 

I'm closing this issue since we can't help you with it.  Please reopen it in the samtools/samtools repo.
