### ISSUE TITLE
optimizeIntervals fails to merge abutting intervals

### ISSUE THREAD

**Issue by jean-philippe-martin** [samtools/htsjdk#971]
### Subject of the issue

`QueryInterval.optimizeIntervals` does not merge adjacent intervals as I would have expected.

Here is test code to demonstrate the issue:

```
  @Test
  public void testOptimizeIntervals() throws Exception {
    QueryInterval[] intervals = new QueryInterval[] {
        new QueryInterval(0, 1519, 1520),
        new QueryInterval(0, 1521, 1525)
    };
    QueryInterval[] expected = new QueryInterval[] {
        new QueryInterval(0, 1519, 1525),
    };
    final QueryInterval[] got = QueryInterval.optimizeIntervals(intervals);
    Assert.assertEquals(expected, got);
  }
```

It fails because `got` still contains the two initial intervals, even though they touch.

### Your environment

I tried using htsjdk 2.10.1, java 8 and Linux.

### Steps to reproduce

Compile and run the test code above. Observe it fail.

### Expected behaviour

I expect abutting intervals to be merged.

### Actual behaviour

Overlapping intervals are merged, but abutting ones are not.

**Comment by yfarjoun** [comment]
fixed by #979
