### ISSUE TITLE
Gradle : running a single test ?

### ISSUE THREAD

**Issue by lindenb** [samtools/htsjdk#984]
not a real issue: I'm trying to run a **single test** with gradle but i cannot find the correct command-line. I've tried : 

`./gradlew -Dtest.single=htsjdk.variant.vcf.VCFEncoderTest test`

but it doesn't work. (is it possible to run such test ?)

Can someone please update the wiki https://github.com/samtools/htsjdk/wiki/Writing-tests-in-HTSJDK with the instruction to run a single test ?

thanks !

---

Why ? I'm working behind a strong firewall, it takes a very long time before gradle raises a ' java.net.ConnectException' for the tests requiring a connection.

```
ParsingUtilsTest:
[TestNG] Running:
  Command line suite

- testFTPDoesExist *** FAILED ***
  java.lang.AssertionError: expected [true] but found [false]
  at org.testng.Assert.fail(Assert.java:94)
  at org.testng.Assert.failNotEquals(Assert.java:496)
  at org.testng.Assert.assertEquals(Assert.java:125)
  at org.testng.Assert.assertEquals(Assert.java:288)

```

**Comment by lbergelson** [comment]
@lindenb What you're doing is what I would expect to work.  It looks like the change to add scala tests broke this functionality.  There's an issue in the scala test plugin we're using that matches this problem, but it hasn't had any resolution. (https://github.com/maiflai/gradle-scalatest/issues/28)  I'll comment there and see if the developer can help us.  

I don't see a great workaround yet, other than running tests in your IDE which should let you run one at a time.  Or maybe invoking TestNG directly, there must be a way to do that, but I don't know how.   I would probably disable the test that's causing you pain manually in any case.  (although even with no slow test 4 minutes to run the whole test suite makes iterating painful...)  Maybe we can make it timeout faster as well.

I think to fix this we're probably going to have to re-visit our integration of the scala-test plugin, this issue has some suggestions for having a mixed scala / java test suite in a way that sounds like it makes more sense for the project.
https://github.com/maiflai/gradle-scalatest/issues/14

And this pr to the plugin seems like it is pushing in a direction that works better for us.  
https://github.com/maiflai/gradle-scalatest/pull/47

Sorry I don't have a better solution, I always run my tests in intellij when I'm developing so I didn't notice this was broken.

**Comment by lindenb** [comment]
@lbergelson thanks for your quick response. :-)

**Comment by lbergelson** [comment]
Quick response, but we'll see how long the fix takes :/    

It's funny that you noticed this today, we opened https://github.com/broadinstitute/picard/issues/924 a few days ago which is the identical problem, but completely different cause.  Issues have been coming in groups lately.

**Comment by lbergelson** [comment]
I took a look at fixing this, and it seems like we can separate out the scalatest and java tests and run each independently which will let the java test filtering work correctly. 

It causes other problems that I haven't figured out how to solve yet, specifically I can't figure out how to get coverage collection to work for the scalatests.  if anyone has any thoughts they can check it out here: https://github.com/samtools/htsjdk/tree/lb_changing_scalatest_stuff
